import type {PDFFont,PDFPage,RGB} from "pdf-lib";
import {proposalSnapshot} from "./customer-proposal-types";
import type {Database} from "@/lib/database.types";

type Proposal=Database["public"]["Tables"]["journey_proposals"]["Row"];
type Enquiry=Database["public"]["Tables"]["enquiries"]["Row"];
const clean=(value:string)=>value.normalize("NFKD").replace(/[^\x20-\x7E]/g," ").replace(/\s+/g," ").trim();

export async function exportProposalPdf(proposal:Proposal,enquiry:Enquiry){
  const snapshot=proposalSnapshot(proposal.sent_snapshot??proposal.customer_snapshot);
  if(!snapshot)throw new Error("Generate a Phase 10 customer proposal before downloading the premium PDF.");
  const qrUrl=`https://api.qrserver.com/v1/create-qr-code/?size=240x240&data=${encodeURIComponent(snapshot.contact.whatsappUrl)}`;
  const [{PDFDocument,StandardFonts,rgb},logoBytes,qrBytes]=await Promise.all([import("pdf-lib"),fetch(snapshot.brand.logo).then(response=>{if(!response.ok)throw new Error("Roam Ceylon logo could not be loaded.");return response.arrayBuffer()}),fetch(qrUrl).then(response=>response.ok?response.arrayBuffer():null).catch(()=>null)]);
  const pdf=await PDFDocument.create();pdf.setTitle(`${proposal.proposal_reference} - Roam Ceylon Journey Proposal`);pdf.setAuthor("Roam Ceylon Atelier");pdf.setSubject(`Version ${proposal.version} prepared for ${enquiry.name}`);
  const regular=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold),serif=await pdf.embedFont(StandardFonts.TimesRomanBold),logo=await pdf.embedPng(logoBytes),qr=qrBytes?await pdf.embedPng(qrBytes):null;
  const forest=rgb(18/255,61/255,51/255),gold=rgb(195/255,140/255,45/255),ivory=rgb(1,253/255,248/255),stone=rgb(112/255,106/255,96/255),slate=rgb(35/255,43/255,40/255),white=rgb(1,1,1),line=rgb(230/255,222/255,205/255),sand=rgb(247/255,242/255,232/255);
  const width=595,height=842,margin=42,content=width-margin*2;
  const wrap=(value:string,font:PDFFont,size:number,max:number)=>{const result:string[]=[];let current="";for(const word of clean(value).split(" ").filter(Boolean)){const candidate=current?`${current} ${word}`:word;if(current&&font.widthOfTextAtSize(candidate,size)>max){result.push(current);current=word}else current=candidate}if(current)result.push(current);return result.length?result:[""]};
  let page:PDFPage=pdf.addPage([width,height]),cursor=0,pageNo=0;pdf.removePage(0);
  const footer=()=>{page.drawLine({start:{x:margin,y:38},end:{x:width-margin,y:38},thickness:.6,color:line});page.drawText(`${snapshot.proposalReference}  |  VERSION ${snapshot.version}`,{x:margin,y:22,size:6.5,font:bold,color:forest});page.drawText(`${snapshot.contact.hotline}  |  ${pageNo}`,{x:width-margin-125,y:22,size:6.5,font:bold,color:stone})};
  const newPage=()=>{if(pageNo)footer();pageNo+=1;page=pdf.addPage([width,height]);page.drawRectangle({x:0,y:0,width,height,color:ivory});page.drawRectangle({x:0,y:height-7,width,height:7,color:gold});const scaled=logo.scaleToFit(68,54);page.drawImage(logo,{x:margin,y:height-76,width:scaled.width,height:scaled.height});page.drawText("ROAM CEYLON",{x:128,y:height-47,size:17,font:serif,color:forest});page.drawText("THOUGHTFULLY CRAFTED. AUTHENTICALLY SRI LANKAN.",{x:128,y:height-63,size:6.2,font:bold,color:gold});cursor=height-105};
  const ensure=(space:number)=>{if(cursor-space<62)newPage()};
  const paragraph=(value:string,size=9,color:RGB=stone,indent=0,max=content-indent)=>{const rows=wrap(value,regular,size,max);ensure(rows.length*13+6);rows.forEach((row,index)=>page.drawText(row,{x:margin+indent,y:cursor-index*13,size,font:regular,color}));cursor-=rows.length*13+6};
  const heading=(eyebrow:string,title:string)=>{ensure(58);page.drawText(clean(eyebrow.toUpperCase()),{x:margin,y:cursor,size:6.5,font:bold,color:gold});cursor-=22;page.drawText(clean(title),{x:margin,y:cursor,size:20,font:serif,color:forest});cursor-=30};
  const divider=()=>{ensure(12);page.drawLine({start:{x:margin,y:cursor},end:{x:width-margin,y:cursor},thickness:.55,color:line});cursor-=15};
  const item=(title:string,subtitle:string)=>{const rows=wrap(subtitle,regular,8.2,content-16);ensure(26+rows.length*11);page.drawText(clean(title),{x:margin,y:cursor,size:10,font:bold,color:slate});rows.forEach((row,index)=>page.drawText(row,{x:margin,y:cursor-14-index*11,size:8.2,font:regular,color:stone}));cursor-=25+rows.length*11;divider()};
  const bullet=(value:string,positive=true)=>{const rows=wrap(value,regular,8.5,content-24);ensure(rows.length*11+8);page.drawText(positive?"+":"-",{x:margin,y:cursor,size:9,font:bold,color:positive?forest:stone});rows.forEach((row,index)=>page.drawText(row,{x:margin+16,y:cursor-index*11,size:8.5,font:regular,color:stone}));cursor-=rows.length*11+7};
  const money=(value:number)=>`${snapshot.pricing.currency} ${value.toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
  const formatDate=(value:string)=>value?new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}T00:00:00Z`)):"Flexible";

  newPage();page.drawRectangle({x:margin,y:cursor-260,width:content,height:260,color:forest});page.drawText(clean(snapshot.proposalReference),{x:margin+25,y:cursor-28,size:7,font:bold,color:gold});page.drawText(`VERSION ${snapshot.version}`,{x:width-margin-86,y:cursor-28,size:7,font:bold,color:ivory});page.drawText("YOUR SRI LANKAN",{x:margin+25,y:cursor-83,size:30,font:serif,color:white});page.drawText("JOURNEY",{x:margin+25,y:cursor-119,size:30,font:serif,color:white});page.drawText(`Thoughtfully crafted for ${clean(snapshot.traveller.name)}`,{x:margin+25,y:cursor-157,size:11,font:bold,color:gold});page.drawText(`${snapshot.journey.days} Days  |  ${snapshot.journey.nights} Nights  |  ${snapshot.traveller.total} Travellers`,{x:margin+25,y:cursor-190,size:9,font:regular,color:ivory});page.drawText(`${formatDate(snapshot.journey.startDate)} - ${formatDate(snapshot.journey.endDate)}`,{x:margin+25,y:cursor-215,size:9,font:regular,color:ivory});page.drawText(clean(snapshot.brand.line),{x:margin+25,y:cursor-240,size:7,font:bold,color:gold});cursor-=292;
  heading("A note from Roam Ceylon",`Dear ${snapshot.traveller.name.split(" ")[0]},`);paragraph(snapshot.introduction,11,slate);cursor-=8;
  heading("Journey at a glance",`${snapshot.journey.days} days across Sri Lanka`);snapshot.journey.route.forEach((stop,index)=>item(`${index+1}. ${stop.name}`,stop.nights?`${stop.nights} night${stop.nights===1?"":"s"}`:stop.kind));
  heading("Day by day","Your journey unfolds");for(const day of snapshot.days){const detail=[day.route,day.transport.length?`Transport: ${day.transport.join(", ")}`:"",day.stay?`Stay: ${day.stay}${day.room?` (${day.room})`:""}`:"",day.experiences.length?`Experiences: ${day.experiences.map(value=>value.name).join(", ")}`:"",day.meals.length?`Meals: ${day.meals.join(", ")}`:"",day.notes.join(" ")].filter(Boolean).join("  |  ");item(`DAY ${String(day.day).padStart(2,"0")}  -  ${day.title}`,`${day.date?formatDate(day.date):"Flexible date"}${detail?`  |  ${detail}`:""}`)}
  if(snapshot.stays.length){heading("Rest, considered","Your stays");snapshot.stays.forEach(stay=>item(`${stay.name} - ${stay.destination}`,`${stay.nights} nights | ${stay.rooms} room${stay.rooms===1?"":"s"} | ${stay.room} | ${stay.mealPlan} | ${stay.confirmation}`))}
  if(snapshot.transport.length){heading("Seamless movement","Getting around");snapshot.transport.forEach(leg=>item(`${leg.from} to ${leg.to}`,`${leg.service}${leg.details.length?` | ${leg.details.join(" | ")}`:""} | ${leg.confirmation}`))}
  if(snapshot.guides.length){heading("Local knowledge","Your guides");snapshot.guides.forEach(guide=>item(guide.name,`${guide.role}${guide.destination?` | ${guide.destination}`:""}${guide.languages.length?` | ${guide.languages.join(", ")}`:""} | ${guide.confirmation}`))}
  if(snapshot.experiences.length){heading("Moments worth travelling for","Your experiences");snapshot.experiences.forEach(experience=>item(`${experience.name} - ${experience.destination}`,`${experience.description}${experience.duration?` | ${experience.duration}`:""} | ${experience.admission} | ${experience.status.replaceAll("_"," ")}`))}
  if(snapshot.optionalItems.length){heading("Available by request","Optional additions");snapshot.optionalItems.forEach(optional=>item(optional.name,`${optional.description} | Not included in journey total${optional.price!==undefined&&optional.currency?` | ${optional.currency} ${optional.price.toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}`:""}`))}
  heading("Clear from the beginning","What is included");snapshot.inclusions.forEach(value=>bullet(value,true));cursor-=8;heading("Equally clear","What is not included");snapshot.exclusions.forEach(value=>bullet(value,false));
  heading("Your journey investment","One clear, considered price");page.drawRectangle({x:margin,y:cursor-76,width:content,height:76,color:forest});page.drawText("TOTAL JOURNEY PRICE",{x:margin+20,y:cursor-25,size:7,font:bold,color:gold});page.drawText(money(snapshot.pricing.total),{x:margin+20,y:cursor-57,size:23,font:serif,color:white});page.drawText(`${money(snapshot.pricing.perPerson)} per traveller`,{x:width-margin-165,y:cursor-53,size:8,font:bold,color:ivory});cursor-=96;snapshot.pricing.breakdown.forEach(lineItem=>item(lineItem.label,money(lineItem.amount)));
  heading("Payment schedule","A clear path to confirmation");if(snapshot.payment.depositAmount!==null){item("Deposit",`${money(snapshot.payment.depositAmount)} | ${snapshot.payment.depositDueDate?`Due ${formatDate(snapshot.payment.depositDueDate)}`:snapshot.payment.depositDueLabel}`);item("Remaining balance",`${money(snapshot.payment.balanceAmount??0)} | ${snapshot.payment.balanceDueDate?`Due ${formatDate(snapshot.payment.balanceDueDate)}`:"Due date confirmed before booking"}`)}else paragraph("Your journey designer will confirm the applicable deposit and balance dates before any payment is requested.");
  heading("Before you approve","Important information");snapshot.importantInformation.forEach(value=>bullet(value,true));if(snapshot.terms){cursor-=6;heading("Terms & booking notes","The details that support your journey");paragraph(snapshot.terms,8.2,stone)}
  heading("The value behind every detail","Your journey, taken care of");paragraph("From the moment you arrive until your final departure, Roam Ceylon coordinates the details behind your journey - stays, transport, experiences and local arrangements - so you can simply experience Sri Lanka. One thoughtful design, local expertise and one accountable travel partner throughout.",9.5,slate);
  heading("What happens next","From proposal to Sri Lanka");snapshot.nextSteps.forEach((value,index)=>item(`${index+1}.`,value));
  ensure(150);page.drawRectangle({x:margin,y:cursor-118,width:content,height:118,color:sand});page.drawText("NEED TO TALK ABOUT YOUR JOURNEY?",{x:margin+20,y:cursor-25,size:7,font:bold,color:gold});page.drawText(clean(snapshot.contact.hotline),{x:margin+20,y:cursor-50,size:15,font:serif,color:forest});page.drawText("Scan to chat with Roam Ceylon on WhatsApp.",{x:margin+20,y:cursor-70,size:8,font:regular,color:stone});const addressWidth=qr?170:220,addressX=qr?width-margin-285:width-margin-235,addressRows=wrap(snapshot.contact.address,regular,7.5,addressWidth);addressRows.forEach((row,index)=>page.drawText(row,{x:addressX,y:cursor-30-index*11,size:7.5,font:regular,color:stone}));if(qr)page.drawImage(qr,{x:width-margin-86,y:cursor-99,width:78,height:78});cursor-=138;
  footer();const bytes=await pdf.save({useObjectStreams:true}),blob=new Blob([new Uint8Array(bytes)],{type:"application/pdf"}),url=URL.createObjectURL(blob),linkElement=document.createElement("a");linkElement.href=url;linkElement.download=`${proposal.proposal_reference.toLowerCase()}-v${proposal.version}-journey-proposal.pdf`;linkElement.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
