import Image from "next/image";
import Link from "next/link";
import {ArrowLeft,ArrowRight,MapPin,Sparkles} from "lucide-react";
import {notFound} from "next/navigation";
import {UnescoBadge} from "@/components/destinations/unesco-badge";
import {Button} from "@/components/ui/button";
import {JourneyService} from "@/lib/journey/journey-service";
import {brand,editionDisplayName} from "@/lib/brand";

export default async function ThemePage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params;
  const data=await new JourneyService().getJourneyBootstrapData();
  const theme=data.themes.find(item=>item.slug===slug);
  if(!theme)notFound();
  const editionName=editionDisplayName(theme);
  const destinations=data.destinations.filter(item=>theme.destinationIds.includes(item.id));
  const experiences=data.experiences.filter(item=>item.themeIds.includes(theme.id)).slice(0,9);
  const gallery=[theme.hero_image_url,...theme.gallery,...destinations.map(item=>item.hero_image_url)].filter((value,index,values):value is string=>Boolean(value)&&values.indexOf(value)===index);
  return <main>
    <section className="relative min-h-[75svh] overflow-hidden bg-slate text-ivory">{theme.hero_image_url&&<Image src={theme.hero_image_url} alt={theme.image_alt||editionName} fill priority sizes="100vw" className="object-cover opacity-60"/>}<div className="absolute inset-0 bg-gradient-to-t from-slate via-slate/25 to-slate/20"/><div className="shell relative flex min-h-[75svh] flex-col justify-end pb-16"><Link href="/discover" className="mb-8 inline-flex items-center gap-2 text-sm"><ArrowLeft className="size-4"/>All Editions</Link><p className="eyebrow text-gold-light">Edition</p><h1 className="display mt-4 max-w-5xl">{editionName}</h1>{theme.short_description&&<p className="mt-6 max-w-2xl text-lg leading-8 text-ivory/80">{theme.short_description}</p>}{theme.badges.length?<div className="mt-6 flex flex-wrap gap-2">{theme.badges.map(badge=><span key={badge} className="rounded-full border border-gold-light/40 bg-slate/35 px-3 py-1.5 text-xs font-bold uppercase tracking-widest text-gold-light backdrop-blur">{badge}</span>)}</div>:null}<Button asChild variant="accent" className="mt-8 w-fit"><Link href={`/journey-builder?theme=${theme.id}&step=1`}>{brand.primaryCta}<ArrowRight/></Link></Button></div></section>
    {(theme.full_description||theme.why_choose.length)?<section className="section"><div className="shell grid gap-12 lg:grid-cols-[1.1fr_.9fr]"><div><p className="eyebrow">The inspiration</p><h2 className="heading mt-4">A journey shaped around the {editionName}.</h2>{theme.full_description&&<p className="prose-luxury mt-7 whitespace-pre-line">{theme.full_description}</p>}</div>{theme.why_choose.length?<div className="rounded-3xl bg-sand-light p-8"><p className="eyebrow">Why choose this Edition</p><div className="mt-6 grid gap-4">{theme.why_choose.map(reason=><div key={reason} className="flex gap-3 border-b border-stone/15 pb-4 text-sm leading-6"><Sparkles className="mt-1 size-4 shrink-0 text-gold"/>{reason}</div>)}</div></div>:null}</div></section>:null}
    {theme.highlights.length?<section className="bg-forest py-16 text-ivory"><div className="shell"><p className="eyebrow text-gold-light">Edition highlights</p><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{theme.highlights.map(item=><div key={item} className="rounded-2xl border border-ivory/15 bg-white/5 p-6 font-serif text-xl leading-snug"><Sparkles className="mb-5 size-5 text-gold-light"/>{item}</div>)}</div></div></section>:null}
    <section className="section"><div className="shell"><div className="max-w-3xl"><p className="eyebrow">Places that belong together</p><h2 className="heading mt-4">Destinations shaped by the {editionName}.</h2><p className="mt-5 leading-7 text-slate/60">Explore every published destination connected to this Edition, then shape the route around the places that move you.</p></div>{destinations.length?<div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{destinations.map(item=><Link key={item.id} href={`/destinations/${item.slug}`} className="group overflow-hidden rounded-3xl border border-stone/15 bg-white transition hover:-translate-y-1 hover:shadow-xl"><div className="relative aspect-[4/3] bg-sand">{item.hero_image_url&&<Image src={item.hero_image_url} alt={item.image_alt||item.name} fill sizes="33vw" className="object-cover transition duration-700 group-hover:scale-105"/>}{item.unesco_information&&<UnescoBadge className="absolute bottom-4 left-4"/>}</div><div className="p-6"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-gold"><MapPin className="size-3"/>{item.province||"Sri Lanka"}</p><h3 className="mt-3 font-serif text-2xl">{item.name}</h3><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate/60">{item.short_description}</p></div></Link>)}</div>:<p className="mt-8 rounded-2xl border border-dashed border-stone/30 p-7 text-stone">More destinations are being curated for this Edition.</p>}</div></section>
    {experiences.length?<section className="bg-sand-light py-20"><div className="shell"><p className="eyebrow">Signature moments</p><h2 className="heading mt-4">Experiences to remember.</h2><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{experiences.map(item=><Link key={item.id} href={`/experiences/${item.slug}`} className="group flex gap-4 rounded-2xl bg-white p-3 shadow-sm transition hover:-translate-y-1"><div className="relative size-28 shrink-0 overflow-hidden rounded-xl bg-sand">{item.hero_image_url&&<Image src={item.hero_image_url} alt={item.image_alt||item.name} fill sizes="112px" className="object-cover"/>}</div><div className="py-2"><span className="text-[.65rem] font-bold uppercase tracking-widest text-gold">{item.category||"Experience"}</span><h3 className="mt-2 line-clamp-2 font-serif text-lg leading-snug">{item.name}</h3><span className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-forest">Explore <ArrowRight className="size-3"/></span></div></Link>)}</div></div></section>:null}
    {theme.suggested_itinerary.length?<section className="section"><div className="shell"><p className="eyebrow">Suggested itinerary</p><h2 className="heading mt-4">A considered starting point.</h2><div className="mt-10 grid gap-4 md:grid-cols-2">{theme.suggested_itinerary.map((stop,index)=><div key={stop} className="flex gap-5 rounded-2xl border border-stone/15 bg-white p-6"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-gold font-serif text-lg text-slate">{index+1}</span><p className="leading-7 text-slate/70">{stop}</p></div>)}</div></div></section>:null}
    {theme.travel_inspiration?<section className="bg-sand-light py-20"><div className="shell max-w-4xl text-center"><p className="eyebrow">Travel inspiration</p><p className="mt-6 whitespace-pre-line font-serif text-3xl leading-relaxed text-forest md:text-4xl">{theme.travel_inspiration}</p></div></section>:null}
    {gallery.length>1?<section className="section"><div className="shell"><div className="grid gap-4 md:grid-cols-12">{gallery.slice(0,5).map((src,index)=><div key={src} className={`relative overflow-hidden rounded-3xl bg-sand ${index===0?"aspect-[16/9] md:col-span-7 md:row-span-2":"aspect-[4/3] md:col-span-5"}`}><Image src={src} alt={`${editionName} travel inspiration ${index+1}`} fill sizes="60vw" className="object-cover"/></div>)}</div><div className="mt-10 flex flex-col items-start justify-between gap-5 rounded-3xl bg-forest p-8 text-ivory md:flex-row md:items-center"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-gold-light"><Sparkles className="size-4"/>Your journey, your pace</p><h2 className="mt-3 font-serif text-3xl">Turn inspiration into a private route.</h2></div><Button asChild variant="accent"><Link href={`/journey-builder?theme=${theme.id}&step=1`}>Start with {editionName}<ArrowRight/></Link></Button></div></div></section>:null}
  </main>;
}
