import Image from "next/image";
import Link from "next/link";
import {ArrowLeft,ArrowRight,MapPin,Sparkles} from "lucide-react";
import {notFound} from "next/navigation";
import {UnescoBadge} from "@/components/destinations/unesco-badge";
import {Button} from "@/components/ui/button";
import {JourneyService} from "@/lib/journey/journey-service";
import {brand,editionDisplayName} from "@/lib/brand";

export default async function ThemePage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params;
  const data=await new JourneyService().getJourneyBootstrapData();
  const theme=data.themes.find(item=>item.slug===slug);
  if(!theme)notFound();
  const editionName=editionDisplayName(theme);
  const destinations=data.destinations.filter(item=>theme.destinationIds.includes(item.id));
  const experiences=data.experiences.filter(item=>item.themeIds.includes(theme.id)).slice(0,9);
  const gallery=[theme.hero_image_url,...theme.gallery,...destinations.map(item=>item.hero_image_url)].filter((value,index,values):value is string=>Boolean(value)&&values.indexOf(value)===index);
  return <main>
    <section className="relative min-h-[75svh] overflow-hidden bg-slate text-ivory">{theme.hero_image_url&&<Image src={theme.hero_image_url} alt={theme.image_alt||editionName} fill priority sizes="100vw" className="object-cover opacity-60"/>}<div className="absolute inset-0 bg-gradient-to-t from-slate via-slate/25 to-slate/20"/><div className="shell relative flex min-h-[75svh] flex-col justify-end pb-16"><Link href="/discover" className="mb-8 inline-flex items-center gap-2 text-sm"><ArrowLeft className="size-4"/>All Editions</Link><p className="eyebrow text-gold-light">Edition</p><h1 className="display mt-4 max-w-5xl">{editionName}</h1>{theme.short_description&&<p className="mt-6 max-w-2xl text-lg leading-8 text-ivory/80">{theme.short_description}</p>}{theme.badges.length?<div className="mt-6 flex flex-wrap gap-2">{theme.badges.map(badge=><span key={badge} className="rounded-full border border-gold-light/40 bg-slate/35 px-3 py-1.5 text-xs font-bold uppercase tracking-widest text-gold-light backdrop-blur">{badge}</span>)}</div>:null}<Button asChild variant="accent" className="mt-8 w-fit"><Link href={`/journey-builder?theme=${theme.id}&step=1`}>{brand.primaryCta}<ArrowRight/></Link></Button></div></section>
    {(theme.full_description||theme.why_choose.length)?<section className="section"><div className="shell grid gap-12 lg:grid-cols-[.7fr_1.3fr] lg:gap-24"><div><p className="editorial-index">01</p><p className="eyebrow mt-8">The inspiration</p><h2 className="heading mt-4">A journey shaped around the {editionName}.</h2></div><div>{theme.full_description&&<p className="prose-luxury whitespace-pre-line">{theme.full_description}</p>}{theme.why_choose.length?<div className="mt-10 divide-y divide-forest/20 border-y border-forest/20">{theme.why_choose.map((reason,index)=><div key={reason} className="grid grid-cols-[3rem_1fr] gap-4 py-5 text-base leading-7"><span className="font-serif text-xl text-gold">{String(index+1).padStart(2,"0")}</span>{reason}</div>)}</div>:null}</div></div></section>:null}
    {theme.highlights.length?<section className="editorial-noise bg-forest py-20 text-ivory md:py-28"><div className="shell"><p className="eyebrow text-gold-light">Edition highlights</p><div className="mt-10 divide-y divide-ivory/20 border-y border-ivory/20">{theme.highlights.map((item,index)=><div key={item} className="grid gap-4 py-7 md:grid-cols-[5rem_1fr]"><span className="font-serif text-3xl text-gold-light">{String(index+1).padStart(2,"0")}</span><p className="font-serif text-2xl leading-snug md:text-3xl">{item}</p></div>)}</div></div></section>:null}
    <section className="section"><div className="shell"><div className="max-w-3xl"><p className="eyebrow">Places that belong together</p><h2 className="heading mt-4">Destinations shaped by the {editionName}.</h2><p className="mt-5 leading-7 text-slate/60">Explore every published destination connected to this Edition, then shape the route around the places that move you.</p></div>{destinations.length?<div className="mt-12 grid gap-x-7 gap-y-12 md:grid-cols-2 lg:grid-cols-12">{destinations.map((item,index)=><Link key={item.id} href={`/destinations/${item.slug}`} className={`image-lift group block focus-ring ${index%4===0?"lg:col-span-7":"lg:col-span-5"}`}><div className={`relative overflow-hidden bg-sand ${index%4===0?"aspect-[16/10]":"aspect-[4/3]"}`}>{item.hero_image_url&&<Image src={item.hero_image_url} alt={item.image_alt||item.name} fill sizes="50vw" className="object-cover"/>}{item.unesco_information&&<UnescoBadge className="absolute bottom-4 left-4"/>}</div><div className="border-b border-forest/20 py-5"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-gold"><MapPin className="size-3"/>{item.province||"Sri Lanka"}</p><h3 className="mt-3 font-serif text-3xl">{item.name}</h3><p className="mt-3 line-clamp-2 text-sm leading-6 text-slate/60">{item.short_description}</p></div></Link>)}</div>:<p className="mt-8 border-y border-forest/20 py-7 text-stone">More destinations are being curated for this Edition.</p>}</div></section>
    {experiences.length?<section className="bg-sand py-20 md:py-28"><div className="shell"><p className="eyebrow">Signature moments</p><h2 className="heading mt-4">Experiences to remember.</h2><div className="mt-10 divide-y divide-forest/20 border-y border-forest/20">{experiences.map((item,index)=><Link key={item.id} href={`/experiences/${item.slug}`} className="group grid items-center gap-5 py-5 focus-ring sm:grid-cols-[4rem_9rem_1fr_auto]"><span className="font-serif text-2xl text-gold">{String(index+1).padStart(2,"0")}</span><div className="relative aspect-[4/3] overflow-hidden bg-sand">{item.hero_image_url&&<Image src={item.hero_image_url} alt={item.image_alt||item.name} fill sizes="144px" className="object-cover transition duration-700 group-hover:scale-105"/>}</div><div><span className="text-[.65rem] font-bold uppercase tracking-widest text-gold">{item.category||"Experience"}</span><h3 className="mt-2 font-serif text-xl leading-snug md:text-2xl">{item.name}</h3></div><ArrowRight className="hidden size-5 transition group-hover:translate-x-1 sm:block"/></Link>)}</div></div></section>:null}
    {theme.suggested_itinerary.length?<section className="section"><div className="shell"><p className="eyebrow">Suggested itinerary</p><h2 className="heading mt-4">A considered starting point.</h2><div className="mt-10 divide-y divide-forest/20 border-y border-forest/20">{theme.suggested_itinerary.map((stop,index)=><div key={stop} className="grid gap-5 py-7 md:grid-cols-[5rem_1fr]"><span className="font-serif text-3xl text-gold">{String(index+1).padStart(2,"0")}</span><p className="max-w-3xl leading-8 text-slate/70">{stop}</p></div>)}</div></div></section>:null}
    {theme.travel_inspiration?<section className="bg-sand-light py-20"><div className="shell max-w-4xl text-center"><p className="eyebrow">Travel inspiration</p><p className="mt-6 whitespace-pre-line font-serif text-3xl leading-relaxed text-forest md:text-4xl">{theme.travel_inspiration}</p></div></section>:null}
    {gallery.length>1?<section className="section"><div className="shell"><div className="grid gap-4 md:grid-cols-12">{gallery.slice(0,5).map((src,index)=><div key={src} className={`relative overflow-hidden rounded-3xl bg-sand ${index===0?"aspect-[16/9] md:col-span-7 md:row-span-2":"aspect-[4/3] md:col-span-5"}`}><Image src={src} alt={`${editionName} travel inspiration ${index+1}`} fill sizes="60vw" className="object-cover"/></div>)}</div><div className="mt-10 flex flex-col items-start justify-between gap-5 rounded-3xl bg-forest p-8 text-ivory md:flex-row md:items-center"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-gold-light"><Sparkles className="size-4"/>Your journey, your pace</p><h2 className="mt-3 font-serif text-3xl">Turn inspiration into a private route.</h2></div><Button asChild variant="accent"><Link href={`/journey-builder?theme=${theme.id}&step=1`}>Start with {editionName}<ArrowRight/></Link></Button></div></div></section>:null}
  </main>;
}
