import "server-only";
import {createPublicClient} from "@/lib/supabase/server";
import {asStrings,ensure,RepositoryError} from "./base";
import type {Destination,HeroMedia,JourneyDestination,JourneyExperience,JourneyGuide,JourneyStay,JourneyTheme,JourneyVehicle,Theme} from "@/lib/types";
import type {Database} from "@/lib/database.types";

const client=()=>{const value=createPublicClient();if(!value)throw new RepositoryError("Supabase connection","CONFIG","Public Supabase environment variables are not configured.");return value};
const unique=(ids:string[])=>[...new Set(ids)];
const optionalPrice=(value:unknown)=>typeof value==="number"&&Number.isFinite(value)?value:null;

export class ThemeRepository{
  async getPublished():Promise<Theme[]>{const rows=ensure("Read published themes",await client().from("themes").select("*").eq("status","published").eq("active",true).order("display_order").order("name"));return rows.map(row=>({...row,why_choose:asStrings(row.why_choose),suggested_itinerary:asStrings(row.suggested_itinerary),gallery:asStrings(row.gallery)}))}
  async getWithDestinations():Promise<JourneyTheme[]>{const themes=await this.getPublished();const ids=themes.map(x=>x.id);if(!ids.length)return[];const links=ensure("Read theme destination relationships",await client().from("theme_destinations").select("*").in("theme_id",ids));return themes.map(theme=>({...theme,destinationIds:links.filter(x=>x.theme_id===theme.id).map(x=>x.destination_id)}))}
}
export class DestinationRepository{
  async getPublished():Promise<Destination[]>{const rows=ensure("Read published destinations",await client().from("destinations").select("*").eq("status","published").eq("active",true).order("display_order").order("name"));return rows.map(x=>({...x,gallery:asStrings(x.gallery),local_highlights:asStrings(x.local_highlights),nearby_attractions:asStrings(x.nearby_attractions),travel_tips:asStrings(x.travel_tips)}))}
  async getByThemeIds(themeIds:string[]):Promise<JourneyDestination[]>{if(!themeIds.length)return[];const links=ensure("Read destinations for themes",await client().from("theme_destinations").select("*").in("theme_id",themeIds));const ids=unique(links.map(x=>x.destination_id));if(!ids.length)return[];const rows=ensure("Read linked published destinations",await client().from("destinations").select("*").eq("status","published").eq("active",true).in("id",ids).order("display_order").order("name"));return rows.map(row=>({...row,gallery:asStrings(row.gallery),local_highlights:asStrings(row.local_highlights),nearby_attractions:asStrings(row.nearby_attractions),travel_tips:asStrings(row.travel_tips),themeIds:unique(links.filter(x=>x.destination_id===row.id).map(x=>x.theme_id))}))}
}
export class ExperienceRepository{
  private map(row:Database["public"]["Tables"]["experiences"]["Row"]){return {...row,gallery:asStrings(row.gallery),highlights:asStrings(row.highlights),unique_points:asStrings(row.unique_points),included:asStrings(row.included),things_to_know:asStrings(row.things_to_know),nearby_attractions:asStrings(row.nearby_attractions),traveller_tips:asStrings(row.traveller_tips),badges:asStrings(row.badges),price_per_person_usd:optionalPrice(row.price_per_person_usd)}}
  async getEditorial():Promise<JourneyExperience[]>{
    const rows=ensure("Read editorial experiences",await client().from("experiences").select("*").eq("status","published").eq("active",true).order("featured",{ascending:false}).order("display_order").order("name"));
    if(!rows.length)return[];
    const ids=rows.map(row=>row.id);
    const [links,themes]=await Promise.all([
      client().from("experience_destinations").select("*").in("experience_id",ids).then(result=>ensure("Read experience destinations",result)),
      client().from("experience_themes").select("*").in("experience_id",ids).then(result=>ensure("Read experience themes",result))
    ]);
    const destinationIds=unique(links.map(link=>link.destination_id));
    const destinations=destinationIds.length?ensure("Read experience destinations",await client().from("destinations").select("id,name,slug,latitude,longitude").in("id",destinationIds)):[];
    return rows.map(row=>{const rowDestinationIds=unique(links.filter(link=>link.experience_id===row.id).map(link=>link.destination_id));const rowDestinations=destinations.filter(destination=>rowDestinationIds.includes(destination.id));return {...this.map(row),destinationIds:rowDestinationIds,destinationNames:rowDestinations.map(destination=>destination.name),destinations:rowDestinations,themeIds:unique(themes.filter(link=>link.experience_id===row.id).map(link=>link.theme_id))}});
  }
  async getByDestinationIds(destinationIds:string[]):Promise<JourneyExperience[]>{if(!destinationIds.length)return[];const links=ensure("Read experiences for destinations",await client().from("experience_destinations").select("*").in("destination_id",destinationIds));const ids=unique(links.map(x=>x.experience_id));if(!ids.length)return[];const [rowsResult,themeLinksResult,destinationRowsResult]=await Promise.all([client().from("experiences").select("*").eq("status","published").eq("active",true).in("id",ids).order("display_order").order("name"),client().from("experience_themes").select("*").in("experience_id",ids),client().from("destinations").select("id,name,slug,latitude,longitude").in("id",destinationIds)]);const rows=ensure("Read linked published experiences",await rowsResult),themeLinks=ensure("Read experience themes",await themeLinksResult),destinations=ensure("Read experience destinations",await destinationRowsResult);return rows.map(row=>{const rowDestinationIds=unique(links.filter(x=>x.experience_id===row.id).map(x=>x.destination_id));const rowDestinations=destinations.filter(destination=>rowDestinationIds.includes(destination.id));return {...this.map(row),destinationIds:rowDestinationIds,destinationNames:rowDestinations.map(destination=>destination.name),destinations:rowDestinations,matchedDestinationIds:unique(links.filter(x=>x.experience_id===row.id&&destinationIds.includes(x.destination_id)).map(x=>x.destination_id)),themeIds:unique(themeLinks.filter(x=>x.experience_id===row.id).map(x=>x.theme_id))}})}
}
export class AccommodationRepository{
  async getByDestinationIds(destinationIds:string[]):Promise<JourneyStay[]>{if(!destinationIds.length)return[];const rows=ensure("Read published accommodation",await client().from("accommodations").select("*").eq("status","published").eq("active",true).eq("is_sample",false).in("destination_id",destinationIds).order("featured",{ascending:false}).order("name"));return rows.filter((x):x is typeof x&{destination_id:string}=>Boolean(x.destination_id)).map(x=>({...x,gallery:asStrings(x.gallery),amenities:asStrings(x.amenities),nightly_rate_usd:optionalPrice(x.nightly_rate_usd),destinationId:x.destination_id}))}
}
export class VehicleRepository{
  async getPublished(destinationIds:string[]=[]):Promise<JourneyVehicle[]>{const rows=ensure("Read published vehicles",await client().from("vehicles").select("*").eq("status","published").eq("active",true).eq("is_sample",false).order("featured",{ascending:false}).order("listing_title"));const links=destinationIds.length?ensure("Read vehicle destinations",await client().from("vehicle_destinations").select("*").in("destination_id",destinationIds)):[];const linkedIds=new Set(links.map(x=>x.vehicle_id));return rows.filter(row=>row.nationwide||linkedIds.has(row.id)||asStrings(row.available_destination_ids).some(id=>destinationIds.includes(id))).map(row=>({...row,gallery:asStrings(row.gallery),daily_rate_usd:optionalPrice(row.daily_rate_usd),per_km_rate_usd:optionalPrice(row.per_km_rate_usd),destinationIds:unique(links.filter(x=>x.vehicle_id===row.id).map(x=>x.destination_id)),price_guide:row.daily_price_guide||row.price_guide}))}
}
export class GuideRepository{
  async getMatching({themeIds,destinationIds,experienceIds}:{themeIds:string[];destinationIds:string[];experienceIds:string[]}):Promise<JourneyGuide[]>{const rows=ensure("Read published guides",await client().from("guides").select("*").eq("status","published").eq("active",true).eq("is_sample",false).order("featured",{ascending:false}).order("name"));if(!rows.length)return[];const ids=rows.map(x=>x.id);const [destinations,themes,experiences]=await Promise.all([client().from("guide_destinations").select("*").in("guide_id",ids).then(x=>ensure("Read guide destinations",x)),client().from("guide_themes").select("*").in("guide_id",ids).then(x=>ensure("Read guide themes",x)),client().from("guide_experiences").select("*").in("guide_id",ids).then(x=>ensure("Read guide experiences",x))]);return rows.map(row=>{const destinationMatches=destinations.filter(x=>x.guide_id===row.id).map(x=>x.destination_id),themeMatches=themes.filter(x=>x.guide_id===row.id).map(x=>x.theme_id),experienceMatches=experiences.filter(x=>x.guide_id===row.id).map(x=>x.experience_id);return {...row,gallery:asStrings(row.gallery),daily_rate_usd:optionalPrice(row.daily_rate_usd),languages:asStrings(row.languages),specialities:asStrings(row.specialities),destinationIds:destinationMatches,themeIds:themeMatches,experienceIds:experienceMatches,relevance:destinationMatches.filter(x=>destinationIds.includes(x)).length*4+themeMatches.filter(x=>themeIds.includes(x)).length*2+experienceMatches.filter(x=>experienceIds.includes(x)).length*3+(row.verified?1:0)}}).filter(x=>x.nationwide||x.relevance!>0).sort((a,b)=>b.relevance!-a.relevance!||Number(b.verified)-Number(a.verified)||a.name.localeCompare(b.name))}
}
export class HomepageRepository{
  async getHero():Promise<HeroMedia>{
    const row=ensure<Database["public"]["Tables"]["homepage_content"]["Row"]>("Read homepage hero",await client().from("homepage_content").select("*").eq("id",true).eq("status","published").eq("active",true).single());
    if(!row)throw new RepositoryError("Read homepage hero","NOT_FOUND","No published homepage record exists.");
    return {title:row.hero_title||"Discover Sri Lanka. Your Way.",subtitle:row.hero_subtitle||"Create a personalised journey through timeless heritage, tropical coastlines, wild landscapes and authentic local experiences.",posterUrl:row.hero_video_poster_url||row.hero_background_image_url,desktopVideoUrl:row.hero_video_url,mobileVideoUrl:row.hero_video_mobile_url,alt:row.hero_video_alt||"Sri Lankan landscape",overlayStrength:Number(row.hero_video_overlay_strength??.58),enabled:row.hero_video_enabled,autoplay:row.hero_video_autoplay,loop:row.hero_video_loop,muted:true};
  }
}
