import assert from "node:assert/strict";import {readFileSync} from "node:fs";import test from "node:test";
const read=(path:string)=>readFileSync(new URL(path,import.meta.url),"utf8");
const migration=()=>read("../supabase/migrations/202608120007_accounting_integrity.sql");

test("financial commands are service-only, capability checked and row locked",()=>{const sql=migration();for(const name of ["initialize_journey_account_command","record_accounting_transaction_command","create_manual_settlement_command","reverse_supplier_settlement_command","close_journey_account_command"]){assert.match(sql,new RegExp(`function public\\.${name}`));assert.match(sql,new RegExp(`revoke all on function public\\.${name}`))}assert.match(sql,/auth\.role\(\)<>'service_role'/);assert.match(sql,/private\.staff_has_permission/);assert.match(sql,/for update/)});
test("accepted proposal is the immutable account commercial basis",()=>{const sql=migration();assert.match(sql,/join public\.journey_proposal_acceptances/);assert.match(sql,/proposal\.status='approved'/);assert.match(sql,/proposal_row\.total_selling_price/);assert.match(sql,/proposal_row\.commercial_snapshot/);assert.match(sql,/source','accepted_proposal'/);assert.doesNotMatch(read("../lib/accounting/post-journey-account.ts"),/allocationCommercialSnapshot|PackagePricingService/)});
test("later allocation edits do not rewrite an accepted account",()=>{const source=read("../lib/accounting/allocation-accounting.ts");assert.match(source,/isAcceptedProposalAccount/);assert.match(source,/if\(account&&isAcceptedProposalAccount\(account\)\)return \{account,synced:false\}/)});
test("posted events and account aggregates cannot be generically rewritten",()=>{const sql=migration();assert.match(sql,/accounting_transactions_immutable/);assert.match(sql,/Posted financial events are immutable/);assert.match(sql,/journey_accounts_guard_financial_basis/);assert.match(sql,/revoke insert,update,delete on public\.journey_accounts/)});
test("payment and settlement commands enforce idempotency and authoritative linkage",()=>{const sql=migration();assert.match(sql,/idempotency_key=key_base\|\|':payment'/);assert.match(sql,/id=p_settlement_id and account_id=p_account_id/);assert.match(sql,/currency<>account_row\.currency/);assert.match(sql,/Payment and waiver exceed the outstanding supplier balance/);assert.match(sql,/Refund exceeds the net amount received/)});
test("reversal is compensating, linked, immutable and replay safe",()=>{const sql=migration();assert.match(sql,/reverses_transaction_id/);assert.match(sql,/accounting_transactions_reversal_source_idx/);assert.match(sql,/supplier_payment_reversal/);assert.match(sql,/idempotency_key in\(key_base\|\|':payment-reversal'/);assert.doesNotMatch(read("../app/api/admin/accounting/reversals/route.ts"),/\.delete\(|\.update\(/)});
test("accounting APIs accept strict command payloads rather than generic writes",()=>{for(const file of ["post","transactions","settlements","reversals","close"]){const source=read(`../app/api/admin/accounting/${file}/route.ts`);assert.match(source,/\.strict\(\)/);assert.doesNotMatch(source,/\.from\("accounting_transactions"\)\.insert|\.from\("journey_accounts"\)\.update|\.from\("journey_settlements"\)\.update/)}assert.match(read("../app/api/admin/accounting/transactions/route.ts"),/record_accounting_transaction_command/)});
