import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import test from "node:test";
import {defaultRolePermissions,staffPermissions} from "../lib/admin/permissions.ts";

test("Super Admin retains every capability",()=>assert.deepEqual(defaultRolePermissions.super_admin,staffPermissions));
test("Journey Designer can curate and prepare proposals without direct accounting, cost, margin or payment access",()=>{const role=defaultRolePermissions.journey_designer;assert(role.includes("journey.design.edit"));assert(role.includes("journey.proposal.create"));assert(!role.includes("finance.revenue.view"));assert(!role.includes("finance.costs.view"));assert(!role.includes("finance.margin.view"));assert(!role.includes("finance.payments.manage"))});
test("Finance can manage accounting while Content cannot read traveller finance",()=>{assert(defaultRolePermissions.finance.includes("finance.payments.manage"));assert(defaultRolePermissions.finance.includes("finance.costs.view"));assert.deepEqual(defaultRolePermissions.content_marketing,["admin.dashboard.view","cms.view","cms.edit"])});
test("Partner Manager allocates suppliers without company margin reporting",()=>{assert(defaultRolePermissions.partner_manager.includes("suppliers.allocate"));assert(!defaultRolePermissions.partner_manager.includes("finance.margin.view"))});
test("server APIs and RLS enforce capabilities instead of relying on hidden UI",()=>{const migration=readFileSync(new URL("../supabase/migrations/202608100003_journey_studio_and_rbac.sql",import.meta.url),"utf8"),allocations=readFileSync(new URL("../app/api/admin/journey-allocations/route.ts",import.meta.url),"utf8"),accounting=readFileSync(new URL("../app/api/admin/accounting/transactions/route.ts",import.meta.url),"utf8");assert.match(migration,/journey_supplier_allocations_capability_select/);assert.match(migration,/finance\.costs\.view/);assert.match(migration,/accounting_transactions_finance_read/);assert.match(allocations,/supplier_cost:canSeeCosts/);assert.match(accounting,/finance\.payments\.manage/)});
test("legacy editor is not an authorization role",()=>{const helper=readFileSync(new URL("../lib/admin/authenticated-staff.ts",import.meta.url),"utf8");assert.doesNotMatch(helper,/\[\"admin\",\"editor\"\]/);assert.match(helper,/profile\.role==="admin"/);assert.match(helper,/profile_staff_roles/)});
test("legacy SEC-005 APIs require precise capabilities",()=>{const quote=readFileSync(new URL("../app/api/admin/quotes/route.ts",import.meta.url),"utf8"),conversion=readFileSync(new URL("../app/api/admin/partner-applications/[id]/convert/route.ts",import.meta.url),"utf8");assert.match(quote,/journey\.proposal\.create/);assert.match(conversion,/suppliers\.manage/);assert.doesNotMatch(`${quote}\n${conversion}`,/\[\"admin\",\"editor\"\]/)});
test("high-risk finance actions use capabilities rather than profile role checks",()=>{const reversal=readFileSync(new URL("../app/api/admin/accounting/reversals/route.ts",import.meta.url),"utf8"),close=readFileSync(new URL("../app/api/admin/accounting/close/route.ts",import.meta.url),"utf8");assert.match(reversal,/finance\.settlements\.reverse/);assert.match(close,/finance\.accounts\.override/);assert.doesNotMatch(`${reversal}\n${close}`,/profile\.role/)});
