import Link from "next/link";import {Compass,HeartHandshake,Leaf,ShieldCheck} from "lucide-react";
import {Hero} from "@/components/home/hero";import {FadeIn} from "@/components/animate/fade-in";import {MediaCard} from "@/components/site/media-card";import {SectionHeading} from "@/components/site/section-heading";import {Button} from "@/components/ui/button";import {listContent} from "@/lib/data";
import {SriLankaMap} from "@/components/map/sri-lanka-map";import {HomepageRepository} from "@/lib/repositories/content";import type {HeroMedia} from "@/lib/types";

export default async function Home(){
  const [themes,destinations]=await Promise.all([listContent("themes"),listContent("destinations")]);
  const fallbackPoster=destinations.find(x=>x.slug==="ella")?.hero_image_url||themes[0]?.hero_image_url||"/og.png";
  const fallbackHero:HeroMedia={title:"Discover Sri Lanka. Your Way.",subtitle:"Create a personalised journey through timeless heritage, tropical coastlines, wild landscapes and authentic local experiences.",posterUrl:fallbackPoster,desktopVideoUrl:null,mobileVideoUrl:null,alt:"Sri Lankan landscape",overlayStrength:.58,enabled:false,autoplay:false,loop:true,muted:true};
  const configuredHero=await new HomepageRepository().getHero().catch(()=>fallbackHero);
  const hero:HeroMedia=process.env.NODE_ENV==="development"?{...configuredHero,developmentYoutubePreviewId:"eWJWA9hv4yw"}:configuredHero;
  return <><Hero media={hero} themes={themes} destinations={destinations}/><section id="discover" className="section"><div className="shell"><SectionHeading eyebrow="Begin with a feeling" title="What calls you to Sri Lanka?" copy="Choose a rhythm, not a package. Every theme opens a different path through the island."/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{themes.map((item,i)=><FadeIn delay={i*.06} key={item.id}><MediaCard href={`/discover?theme=${item.slug}`} image={item.hero_image_url} alt={item.image_alt} title={item.name} description={item.short_description} tall/></FadeIn>)}</div></div></section>
  <section className="section bg-sand-light"><div className="shell"><SectionHeading eyebrow="Places worth the journey" title="The island, one extraordinary place at a time."/><div className="grid gap-5 md:grid-cols-3">{destinations.slice(0,6).map(item=><MediaCard key={item.id} href={`/destinations/${item.slug}`} image={item.hero_image_url} alt={item.image_alt} title={item.name} eyebrow={item.province} description={item.short_description} unesco={Boolean(item.unesco_information)}/>)}</div><div className="mt-10 text-center"><Button asChild variant="outline"><Link href="/destinations">Explore every destination</Link></Button></div></div></section>
  <section className="section bg-sand-light"><div className="shell"><SectionHeading eyebrow="Explore the island" title="See where your journey could take you."/><SriLankaMap destinations={destinations}/></div></section>
  <section className="section bg-forest text-ivory"><div className="shell"><SectionHeading eyebrow="Why Roam Ceylon" title="Local intelligence. Quietly exceptional journeys." copy="Technology makes planning effortless. People make the journey unforgettable."/><div className="grid gap-10 md:grid-cols-4">{[[Compass,"Designed around you","No fixed itineraries. Every route starts with what matters to you."],[Leaf,"Rooted here","Sri Lanka–based planners with knowledge that goes beyond guidebooks."],[ShieldCheck,"Considered choices","Clear standards, honest information and partners reviewed by people."],[HeartHandshake,"One human connection","A named consultant who knows your journey from idea to arrival."]].map(([Icon,title,copy])=><div key={String(title)}><Icon className="mb-5 size-7 text-gold-light"/><h3 className="font-serif text-2xl">{String(title)}</h3><p className="mt-3 text-sm leading-7 text-ivory/65">{String(copy)}</p></div>)}</div></div></section>
  <section className="section"><div className="shell rounded-[2.5rem] bg-sand p-10 text-center md:p-20"><p className="eyebrow mb-4">Your island. Your pace.</p><h2 className="heading mx-auto max-w-3xl">Start with curiosity. Leave with a journey.</h2><Button asChild variant="primary" size="lg" className="mt-8"><Link href="/journey-builder">Build your Sri Lanka journey</Link></Button></div></section></>;
}
