export type Json=string|number|boolean|null|{[key:string]:Json|undefined}|Json[];
type Status="draft"|"in_review"|"published"|"archived";
type ContentBase={id:string;slug:string;status:Status;active:boolean;created_at:string;updated_at:string};

export interface Database{
  public:{
    Tables:{
      themes:{Row:ContentBase&{name:string;short_description:string|null;full_description:string|null;hero_image_url:string|null;image_alt:string|null;icon:string|null;display_order:number;why_choose:Json;suggested_itinerary:Json;gallery:Json;travel_inspiration:string|null};Insert:Partial<Database["public"]["Tables"]["themes"]["Row"]>;Update:Partial<Database["public"]["Tables"]["themes"]["Row"]>;Relationships:[]};
      destinations:{Row:ContentBase&{name:string;province:string|null;region:string|null;short_description:string|null;full_description:string|null;hero_image_url:string|null;image_alt:string|null;gallery:Json;latitude:number|null;longitude:number|null;display_order:number;coming_soon:boolean;historical_importance:string|null;cultural_significance:string|null;why_visit:string|null;unesco_information:string|null;nature_wildlife:string|null;local_highlights:Json;best_time_to_visit:string|null;weather:string|null;nearby_attractions:Json;travel_tips:Json};Insert:Partial<Database["public"]["Tables"]["destinations"]["Row"]>;Update:Partial<Database["public"]["Tables"]["destinations"]["Row"]>;Relationships:[]};
      theme_destinations:{Row:{theme_id:string;destination_id:string};Insert:{theme_id:string;destination_id:string};Update:Partial<{theme_id:string;destination_id:string}>;Relationships:[]};
      experiences:{Row:ContentBase&{name:string;category:string|null;short_description:string|null;full_description:string|null;hero_image_url:string|null;image_alt:string|null;gallery:Json;duration:string|null;difficulty:string|null;best_season:string|null;highlights:Json;unique_points:Json;included:Json;things_to_know:Json;nearby_attractions:Json;traveller_tips:Json;badges:Json;family_friendly:boolean;suitable_for_children:boolean;private_option:boolean;priority:string|null;featured:boolean;display_order:number;price_per_person_usd:number|null};Insert:Partial<Database["public"]["Tables"]["experiences"]["Row"]>;Update:Partial<Database["public"]["Tables"]["experiences"]["Row"]>;Relationships:[]};
      experience_destinations:{Row:{experience_id:string;destination_id:string};Insert:{experience_id:string;destination_id:string};Update:Partial<{experience_id:string;destination_id:string}>;Relationships:[]};
      experience_themes:{Row:{experience_id:string;theme_id:string};Insert:{experience_id:string;theme_id:string};Update:Partial<{experience_id:string;theme_id:string}>;Relationships:[]};
      accommodations:{Row:ContentBase&{name:string;destination_id:string|null;property_type:string|null;star_rating:number|null;short_description:string|null;full_description:string|null;hero_image_url:string|null;image_alt:string|null;gallery:Json;address:string|null;price_range:string|null;nightly_rate_usd:number|null;pricing_tier:string|null;amenities:Json;featured:boolean;verified:boolean;is_sample:boolean};Insert:Partial<Database["public"]["Tables"]["accommodations"]["Row"]>;Update:Partial<Database["public"]["Tables"]["accommodations"]["Row"]>;Relationships:[]};
      vehicles:{Row:ContentBase&{listing_title:string;vehicle_type:string|null;vehicle_model:string|null;short_description:string|null;hero_image_url:string|null;image_alt:string|null;gallery:Json;passenger_capacity:number|null;luggage_capacity:string|null;air_conditioned:boolean;driver_included:boolean;nationwide:boolean;available_destination_ids:Json;price_guide:string|null;daily_price_guide:string|null;daily_rate_usd:number|null;per_km_rate_usd:number|null;featured:boolean;verified:boolean;is_sample:boolean};Insert:Partial<Database["public"]["Tables"]["vehicles"]["Row"]>;Update:Partial<Database["public"]["Tables"]["vehicles"]["Row"]>;Relationships:[]};
      vehicle_destinations:{Row:{vehicle_id:string;destination_id:string};Insert:{vehicle_id:string;destination_id:string};Update:Partial<{vehicle_id:string;destination_id:string}>;Relationships:[]};
      guides:{Row:ContentBase&{name:string;short_bio:string|null;full_bio:string|null;profile_image_url:string|null;image_alt:string|null;gallery:Json;languages:Json;years_experience:number|null;specialities:Json;licence_number:string|null;featured:boolean;verified:boolean;is_sample:boolean;nationwide:boolean;daily_rate_usd:number|null};Insert:Partial<Database["public"]["Tables"]["guides"]["Row"]>;Update:Partial<Database["public"]["Tables"]["guides"]["Row"]>;Relationships:[]};
      guide_destinations:{Row:{guide_id:string;destination_id:string};Insert:{guide_id:string;destination_id:string};Update:Partial<{guide_id:string;destination_id:string}>;Relationships:[]};
      guide_themes:{Row:{guide_id:string;theme_id:string};Insert:{guide_id:string;theme_id:string};Update:Partial<{guide_id:string;theme_id:string}>;Relationships:[]};
      guide_experiences:{Row:{guide_id:string;experience_id:string};Insert:{guide_id:string;experience_id:string};Update:Partial<{guide_id:string;experience_id:string}>;Relationships:[]};
      homepage_content:{Row:{id:boolean;hero_title:string|null;hero_subtitle:string|null;hero_background_image_url:string|null;hero_video_url:string|null;hero_video_mobile_url:string|null;hero_video_poster_url:string|null;hero_video_alt:string|null;hero_video_overlay_strength:number;hero_video_enabled:boolean;hero_video_autoplay:boolean;hero_video_loop:boolean;hero_video_muted:boolean;primary_cta:Json;secondary_cta:Json;status:Status;active:boolean};Insert:Partial<Database["public"]["Tables"]["homepage_content"]["Row"]>;Update:Partial<Database["public"]["Tables"]["homepage_content"]["Row"]>;Relationships:[]};
      website_settings:{Row:{id:boolean;website_name:string;contact_phone:string|null;enquiry_email:string|null};Insert:Partial<Database["public"]["Tables"]["website_settings"]["Row"]>;Update:Partial<Database["public"]["Tables"]["website_settings"]["Row"]>;Relationships:[]};
      enquiries:{Row:{id:string;created_at:string;updated_at:string;name:string;email:string;phone:string|null;nationality:string|null;summary:string|null;trip_state:Json;status:string;travel_start_date:string|null;travel_end_date:string|null;adults:number;children:number;selected_themes:Json;selected_destinations:Json;selected_experiences:Json;experience_participants:Json;selected_stays:Json;selected_vehicle:string|null;selected_guide:string|null;traveller_notes:string|null;internal_notes:string|null};Insert:{name:string;email:string;phone?:string|null;nationality?:string|null;summary?:string|null;trip_state?:Json;status?:string;travel_start_date?:string|null;travel_end_date?:string|null;adults?:number;children?:number;selected_themes?:Json;selected_destinations?:Json;selected_experiences?:Json;experience_participants?:Json;selected_stays?:Json;selected_vehicle?:string|null;selected_guide?:string|null;traveller_notes?:string|null;internal_notes?:string|null};Update:Partial<Database["public"]["Tables"]["enquiries"]["Row"]>;Relationships:[]};
      journey_requests:{Row:{id:string;journey_reference:string;customer_name:string;whatsapp_number:string;email_address:string;country:string|null;arrival_date:string|null;departure_date:string|null;special_requests:string|null;journey_snapshot:Json;status:"new"|"preparing_proposal"|"proposal_sent"|"accepted"|"cancelled";created_at:string;updated_at:string};Insert:{customer_name:string;whatsapp_number:string;email_address:string;country?:string|null;arrival_date?:string|null;departure_date?:string|null;special_requests?:string|null;journey_snapshot:Json;status?:"new"|"preparing_proposal"|"proposal_sent"|"accepted"|"cancelled"};Update:Partial<Database["public"]["Tables"]["journey_requests"]["Row"]>;Relationships:[]};
      journey_accounts:{Row:{id:string;account_number:string;enquiry_id:string;traveller_name:string;traveller_email:string;status:"open"|"part_paid"|"paid"|"settled"|"void";currency:string;selling_price:number;internal_cost:number;gross_profit:number;profit_margin:number;amount_received:number;amount_refunded:number;supplier_paid:number;supplier_savings:number;travel_start_date:string|null;travel_end_date:string|null;quote_snapshot:Json;posted_at:string;settled_at:string|null;created_at:string;updated_at:string;created_by:string|null};Insert:Partial<Database["public"]["Tables"]["journey_accounts"]["Row"]>&{enquiry_id:string;traveller_name:string;traveller_email:string;selling_price:number;internal_cost:number;gross_profit:number;profit_margin:number;quote_snapshot:Json};Update:Partial<Database["public"]["Tables"]["journey_accounts"]["Row"]>;Relationships:[]};
      journey_settlements:{Row:{id:string;account_id:string;source_key:string;payee_type:"accommodation"|"vehicle"|"guide"|"experience"|"destination"|"operations"|"other";entity_id:string|null;payee_name:string;description:string|null;currency:string;amount_due:number;amount_paid:number;waived_amount:number;waiver_reason:string|null;due_date:string|null;status:"pending"|"part_paid"|"paid"|"waived";notes:string|null;created_at:string;updated_at:string};Insert:Partial<Database["public"]["Tables"]["journey_settlements"]["Row"]>&{account_id:string;source_key:string;payee_type:"accommodation"|"vehicle"|"guide"|"experience"|"destination"|"operations"|"other";payee_name:string;amount_due:number};Update:Partial<Database["public"]["Tables"]["journey_settlements"]["Row"]>;Relationships:[]};
      accounting_transactions:{Row:{id:string;account_id:string;settlement_id:string|null;transaction_type:"customer_receipt"|"customer_refund"|"supplier_payment"|"supplier_waiver";amount:number;currency:string;payment_date:string;payment_method:string|null;reference:string|null;notes:string|null;created_at:string;created_by:string|null};Insert:Partial<Database["public"]["Tables"]["accounting_transactions"]["Row"]>&{account_id:string;transaction_type:"customer_receipt"|"customer_refund"|"supplier_payment"|"supplier_waiver";amount:number};Update:Partial<Database["public"]["Tables"]["accounting_transactions"]["Row"]>;Relationships:[]};
      accounting_attachments:{Row:{id:string;account_id:string;settlement_id:string;transaction_id:string;file_name:string;storage_path:string;mime_type:string;file_size:number;created_at:string;created_by:string|null};Insert:Partial<Database["public"]["Tables"]["accounting_attachments"]["Row"]>&{account_id:string;settlement_id:string;transaction_id:string;file_name:string;storage_path:string;mime_type:string;file_size:number};Update:Partial<Database["public"]["Tables"]["accounting_attachments"]["Row"]>;Relationships:[]};
      partner_applications:{Row:{id:string;application_reference:string;partner_type:"accommodation"|"vehicle"|"guide";applicant_name:string;business_name:string|null;email:string;phone:string|null;preferred_contact_method:string|null;address:string|null;district:string|null;province:string|null;website:string|null;social_url:string|null;introduction:string|null;destination_ids:Json;application_data:Json;status:"submitted"|"under_review"|"needs_information"|"approved"|"rejected"|"converted";internal_notes:string|null;submitted_at:string|null;reviewed_at:string|null;reviewed_by:string|null;created_at:string;updated_at:string};Insert:Partial<Database["public"]["Tables"]["partner_applications"]["Row"]>&{partner_type:"accommodation"|"vehicle"|"guide";applicant_name:string;email:string};Update:Partial<Database["public"]["Tables"]["partner_applications"]["Row"]>;Relationships:[]};
      partner_application_files:{Row:{id:string;application_id:string;file_type:string;file_name:string;storage_path:string;bucket_id:"partner-application-media"|"partner-application-documents";mime_type:string;is_private:boolean;sort_order:number;created_at:string};Insert:Partial<Database["public"]["Tables"]["partner_application_files"]["Row"]>&{application_id:string;file_type:string;file_name:string;storage_path:string;bucket_id:"partner-application-media"|"partner-application-documents";mime_type:string};Update:Partial<Database["public"]["Tables"]["partner_application_files"]["Row"]>;Relationships:[]};
      partner_application_history:{Row:{id:string;application_id:string;from_status:string|null;to_status:string;note:string|null;changed_by:string|null;created_at:string};Insert:Partial<Database["public"]["Tables"]["partner_application_history"]["Row"]>&{application_id:string;to_status:string};Update:Partial<Database["public"]["Tables"]["partner_application_history"]["Row"]>;Relationships:[]};
      partner_commercial_settings:{Row:{id:boolean;application_fee_enabled:boolean;application_fee_amount:number;listing_fee_enabled:boolean;listing_fee_amount:number;commission_enabled:boolean;commission_percentage:number;featured_placement_enabled:boolean;currency:string;updated_at:string;updated_by:string|null};Insert:Partial<Database["public"]["Tables"]["partner_commercial_settings"]["Row"]>;Update:Partial<Database["public"]["Tables"]["partner_commercial_settings"]["Row"]>;Relationships:[]};
      journey_pricing_settings:{Row:{id:boolean;currency:string;accommodation_tiers:Json;activity_per_guest_usd:number;route_distance_factor:number;estimate_factor:number;guide_default_daily_rate_usd:number|null;seasons:Json;updated_at:string;updated_by:string|null};Insert:Partial<Database["public"]["Tables"]["journey_pricing_settings"]["Row"]>;Update:Partial<Database["public"]["Tables"]["journey_pricing_settings"]["Row"]>;Relationships:[]};
      profiles:{Row:{id:string;email:string|null;full_name:string|null;role:"admin"|"editor"|"partner";created_at:string;updated_at:string};Insert:Partial<Database["public"]["Tables"]["profiles"]["Row"]>;Update:Partial<Database["public"]["Tables"]["profiles"]["Row"]>;Relationships:[]};
      tour_pricing_config:{Row:{id:boolean;currency:string;room_occupancy:number;child_cost_factor:number;route_distance_buffer_percent:number;driver_salary_per_day:number|null;fuel_price_per_litre:number|null;vehicle_km_per_litre:number|null;tolls_per_journey:number|null;parking_per_day:number|null;guide_accommodation_per_night:number|null;airport_transfer_each_way:number|null;administration_fixed:number|null;administration_percent:number|null;contingency_percent:number|null;service_fee_fixed:number|null;service_fee_percent:number|null;target_profit_margin_percent:number|null;seasonal_rules:Json;active:boolean;updated_at:string;updated_by:string|null};Insert:Partial<Database["public"]["Tables"]["tour_pricing_config"]["Row"]>;Update:Partial<Database["public"]["Tables"]["tour_pricing_config"]["Row"]>;Relationships:[]};
      tour_supplier_costs:{Row:{id:string;entity_type:"accommodation"|"vehicle"|"guide"|"experience"|"destination";entity_id:string;cost_category:string;unit:"per_room_night"|"per_vehicle_day"|"per_kilometre"|"per_guide_day"|"per_person"|"per_transfer"|"fixed";amount:number;currency:string;valid_from:string|null;valid_to:string|null;seasonal_rules:Json;partner_commission_percent:number|null;active:boolean;notes:string|null;created_at:string;updated_at:string;created_by:string|null;updated_by:string|null};Insert:Partial<Database["public"]["Tables"]["tour_supplier_costs"]["Row"]>;Update:Partial<Database["public"]["Tables"]["tour_supplier_costs"]["Row"]>;Relationships:[]};
      pricing_plans:{Row:{id:string;entity_type:"accommodation"|"vehicle"|"guide"|"experience"|"destination";entity_id:string;name:string;description:string|null;price:number;currency:string;charging_method:string;minimum_quantity:number|null;maximum_quantity:number|null;image_url:string|null;notes:string|null;details:Json;seasonal_rules:Json;sort_order:number;active:boolean;created_at:string;updated_at:string;created_by:string|null;updated_by:string|null};Insert:Partial<Database["public"]["Tables"]["pricing_plans"]["Row"]>&{entity_type:"accommodation"|"vehicle"|"guide"|"experience"|"destination";entity_id:string;name:string;price:number;charging_method:string};Update:Partial<Database["public"]["Tables"]["pricing_plans"]["Row"]>;Relationships:[]};
    };
    Views:{[_ in never]:never};
    Functions:{[_ in never]:never};
    Enums:{content_status:Status};
    CompositeTypes:{[_ in never]:never};
  };
}
