export type Json=string|number|boolean|null|{[key:string]:Json|undefined}|Json[];
type Status="draft"|"in_review"|"published"|"archived";
type ContentBase={id:string;slug:string;status:Status;active:boolean;created_at:string;updated_at:string};

export interface Database{
  public:{
    Tables:{
      themes:{Row:ContentBase&{name:string;short_description:string|null;hero_image_url:string|null;image_alt:string|null;icon:string|null;display_order:number};Insert:Partial<Database["public"]["Tables"]["themes"]["Row"]>;Update:Partial<Database["public"]["Tables"]["themes"]["Row"]>;Relationships:[]};
      destinations:{Row:ContentBase&{name:string;province:string|null;region:string|null;short_description:string|null;full_description:string|null;hero_image_url:string|null;image_alt:string|null;gallery:Json;latitude:number|null;longitude:number|null;display_order:number;coming_soon:boolean};Insert:Partial<Database["public"]["Tables"]["destinations"]["Row"]>;Update:Partial<Database["public"]["Tables"]["destinations"]["Row"]>;Relationships:[]};
      theme_destinations:{Row:{theme_id:string;destination_id:string};Insert:{theme_id:string;destination_id:string};Update:Partial<{theme_id:string;destination_id:string}>;Relationships:[]};
      experiences:{Row:ContentBase&{name:string;category:string|null;short_description:string|null;full_description:string|null;hero_image_url:string|null;image_alt:string|null;gallery:Json;duration:string|null;difficulty:string|null;family_friendly:boolean;suitable_for_children:boolean;private_option:boolean;priority:string|null;featured:boolean;display_order:number;price_per_person_usd:number|null};Insert:Partial<Database["public"]["Tables"]["experiences"]["Row"]>;Update:Partial<Database["public"]["Tables"]["experiences"]["Row"]>;Relationships:[]};
      experience_destinations:{Row:{experience_id:string;destination_id:string};Insert:{experience_id:string;destination_id:string};Update:Partial<{experience_id:string;destination_id:string}>;Relationships:[]};
      experience_themes:{Row:{experience_id:string;theme_id:string};Insert:{experience_id:string;theme_id:string};Update:Partial<{experience_id:string;theme_id:string}>;Relationships:[]};
      accommodations:{Row:ContentBase&{name:string;destination_id:string|null;property_type:string|null;star_rating:number|null;short_description:string|null;hero_image_url:string|null;image_alt:string|null;gallery:Json;address:string|null;price_range:string|null;nightly_rate_usd:number|null;pricing_tier:string|null;amenities:Json;featured:boolean;verified:boolean;is_sample:boolean};Insert:Partial<Database["public"]["Tables"]["accommodations"]["Row"]>;Update:Partial<Database["public"]["Tables"]["accommodations"]["Row"]>;Relationships:[]};
      vehicles:{Row:ContentBase&{listing_title:string;vehicle_type:string|null;short_description:string|null;hero_image_url:string|null;image_alt:string|null;passenger_capacity:number|null;luggage_capacity:string|null;driver_included:boolean;nationwide:boolean;available_destination_ids:Json;price_guide:string|null;daily_price_guide:string|null;daily_rate_usd:number|null;per_km_rate_usd:number|null;featured:boolean;verified:boolean;is_sample:boolean};Insert:Partial<Database["public"]["Tables"]["vehicles"]["Row"]>;Update:Partial<Database["public"]["Tables"]["vehicles"]["Row"]>;Relationships:[]};
      vehicle_destinations:{Row:{vehicle_id:string;destination_id:string};Insert:{vehicle_id:string;destination_id:string};Update:Partial<{vehicle_id:string;destination_id:string}>;Relationships:[]};
      guides:{Row:ContentBase&{name:string;short_bio:string|null;profile_image_url:string|null;image_alt:string|null;gallery:Json;languages:Json;years_experience:number|null;specialities:Json;featured:boolean;verified:boolean;is_sample:boolean;nationwide:boolean;daily_rate_usd:number|null};Insert:Partial<Database["public"]["Tables"]["guides"]["Row"]>;Update:Partial<Database["public"]["Tables"]["guides"]["Row"]>;Relationships:[]};
      guide_destinations:{Row:{guide_id:string;destination_id:string};Insert:{guide_id:string;destination_id:string};Update:Partial<{guide_id:string;destination_id:string}>;Relationships:[]};
      guide_themes:{Row:{guide_id:string;theme_id:string};Insert:{guide_id:string;theme_id:string};Update:Partial<{guide_id:string;theme_id:string}>;Relationships:[]};
      guide_experiences:{Row:{guide_id:string;experience_id:string};Insert:{guide_id:string;experience_id:string};Update:Partial<{guide_id:string;experience_id:string}>;Relationships:[]};
      homepage_content:{Row:{id:boolean;hero_title:string|null;hero_subtitle:string|null;hero_background_image_url:string|null;hero_video_url:string|null;hero_video_mobile_url:string|null;hero_video_poster_url:string|null;hero_video_alt:string|null;hero_video_overlay_strength:number;hero_video_enabled:boolean;hero_video_autoplay:boolean;hero_video_loop:boolean;hero_video_muted:boolean;primary_cta:Json;secondary_cta:Json;status:Status;active:boolean};Insert:Partial<Database["public"]["Tables"]["homepage_content"]["Row"]>;Update:Partial<Database["public"]["Tables"]["homepage_content"]["Row"]>;Relationships:[]};
      website_settings:{Row:{id:boolean;website_name:string;contact_phone:string|null;enquiry_email:string|null};Insert:Partial<Database["public"]["Tables"]["website_settings"]["Row"]>;Update:Partial<Database["public"]["Tables"]["website_settings"]["Row"]>;Relationships:[]};
      enquiries:{Row:{id:string;created_at:string;updated_at:string;name:string;email:string;phone:string|null;nationality:string|null;summary:string|null;trip_state:Json;status:string;travel_start_date:string|null;travel_end_date:string|null;adults:number;children:number;selected_themes:Json;selected_destinations:Json;selected_experiences:Json;selected_stays:Json;selected_vehicle:string|null;selected_guide:string|null;traveller_notes:string|null;internal_notes:string|null};Insert:{name:string;email:string;phone?:string|null;nationality?:string|null;summary?:string|null;trip_state?:Json;status?:string;travel_start_date?:string|null;travel_end_date?:string|null;adults?:number;children?:number;selected_themes?:Json;selected_destinations?:Json;selected_experiences?:Json;selected_stays?:Json;selected_vehicle?:string|null;selected_guide?:string|null;traveller_notes?:string|null;internal_notes?:string|null};Update:Partial<Database["public"]["Tables"]["enquiries"]["Row"]>;Relationships:[]};
      journey_pricing_settings:{Row:{id:boolean;currency:string;accommodation_tiers:Json;activity_per_guest_usd:number;route_distance_factor:number;estimate_factor:number;guide_default_daily_rate_usd:number|null;seasons:Json;updated_at:string;updated_by:string|null};Insert:Partial<Database["public"]["Tables"]["journey_pricing_settings"]["Row"]>;Update:Partial<Database["public"]["Tables"]["journey_pricing_settings"]["Row"]>;Relationships:[]};
      profiles:{Row:{id:string;email:string|null;full_name:string|null;role:"admin"|"editor"|"partner";created_at:string;updated_at:string};Insert:Partial<Database["public"]["Tables"]["profiles"]["Row"]>;Update:Partial<Database["public"]["Tables"]["profiles"]["Row"]>;Relationships:[]};
      tour_pricing_config:{Row:{id:boolean;currency:string;room_occupancy:number;child_cost_factor:number;route_distance_buffer_percent:number;driver_salary_per_day:number|null;fuel_price_per_litre:number|null;vehicle_km_per_litre:number|null;tolls_per_journey:number|null;parking_per_day:number|null;guide_accommodation_per_night:number|null;airport_transfer_each_way:number|null;administration_fixed:number|null;administration_percent:number|null;contingency_percent:number|null;service_fee_fixed:number|null;service_fee_percent:number|null;target_profit_margin_percent:number|null;seasonal_rules:Json;active:boolean;updated_at:string;updated_by:string|null};Insert:Partial<Database["public"]["Tables"]["tour_pricing_config"]["Row"]>;Update:Partial<Database["public"]["Tables"]["tour_pricing_config"]["Row"]>;Relationships:[]};
      tour_supplier_costs:{Row:{id:string;entity_type:"accommodation"|"vehicle"|"guide"|"experience"|"destination";entity_id:string;cost_category:string;unit:"per_room_night"|"per_vehicle_day"|"per_kilometre"|"per_guide_day"|"per_person"|"per_transfer"|"fixed";amount:number;currency:string;valid_from:string|null;valid_to:string|null;seasonal_rules:Json;partner_commission_percent:number|null;active:boolean;notes:string|null;created_at:string;updated_at:string;created_by:string|null;updated_by:string|null};Insert:Partial<Database["public"]["Tables"]["tour_supplier_costs"]["Row"]>;Update:Partial<Database["public"]["Tables"]["tour_supplier_costs"]["Row"]>;Relationships:[]};
      pricing_plans:{Row:{id:string;entity_type:"accommodation"|"vehicle"|"guide"|"experience"|"destination";entity_id:string;name:string;description:string|null;price:number;currency:string;charging_method:string;minimum_quantity:number|null;maximum_quantity:number|null;image_url:string|null;notes:string|null;details:Json;seasonal_rules:Json;sort_order:number;active:boolean;created_at:string;updated_at:string;created_by:string|null;updated_by:string|null};Insert:Partial<Database["public"]["Tables"]["pricing_plans"]["Row"]>&{entity_type:"accommodation"|"vehicle"|"guide"|"experience"|"destination";entity_id:string;name:string;price:number;charging_method:string};Update:Partial<Database["public"]["Tables"]["pricing_plans"]["Row"]>;Relationships:[]};
    };
    Views:{[_ in never]:never};
    Functions:{[_ in never]:never};
    Enums:{content_status:Status};
    CompositeTypes:{[_ in never]:never};
  };
}
