import {CalendarDays,Check,ChevronDown,Clock3,Compass,MapPin,ShieldCheck,Sparkles,Users,X} from "lucide-react";
import type {ProposalSnapshot} from "@/lib/proposals/customer-proposal-types";

const date=(value:string)=>value?new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}T00:00:00Z`)):"Flexible";
const money=(value:number,currency:string)=>`${currency} ${value.toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const point=(lat:number,lon:number)=>({x:32+((lon-79.6)/2.4)*166,y:376-((lat-5.8)/4.2)*344});

export function ProposalDocument({snapshot,status,actions}:{snapshot:ProposalSnapshot;status:string;actions?:React.ReactNode}){
  const travellerSummary=[snapshot.traveller.adults&&`${snapshot.traveller.adults} adult${snapshot.traveller.adults===1?"":"s"}`,snapshot.traveller.children&&`${snapshot.traveller.children} child${snapshot.traveller.children===1?"":"ren"}`,snapshot.traveller.infants&&`${snapshot.traveller.infants} infant${snapshot.traveller.infants===1?"":"s"}`].filter(Boolean).join(" · ");
  return <article className="proposal-print min-h-screen bg-[#f7f3e9] text-slate">
    <section className="proposal-cover relative isolate min-h-[820px] overflow-hidden bg-forest text-ivory">
      {snapshot.coverImage?<div className="absolute inset-0 -z-20 bg-cover bg-center" style={{backgroundImage:`url(${snapshot.coverImage})`}}/>:null}<div className="absolute inset-0 -z-10 bg-gradient-to-b from-slate/45 via-forest/55 to-forest"/>
      <div className="mx-auto flex min-h-[820px] max-w-6xl flex-col px-6 py-10 md:px-12 md:py-14"><div className="flex items-start justify-between gap-5"><div className="rounded-3xl bg-ivory/95 p-3 shadow-2xl"><img src={snapshot.brand.logo} alt="Roam Ceylon" className="h-24 w-40 object-contain"/></div><div className="text-right text-[.66rem] font-bold uppercase tracking-[.22em] text-ivory/70"><p>{snapshot.proposalReference}</p><p className="mt-2">Version {snapshot.version}</p><p className="mt-2">{status.replaceAll("_"," ")}</p></div></div>
        <div className="my-auto max-w-4xl py-16"><p className="text-xs font-bold uppercase tracking-[.28em] text-gold-light">{snapshot.brand.line}</p><h1 className="mt-8 max-w-3xl font-serif text-6xl leading-[.96] md:text-8xl">Your Sri Lankan journey.</h1><div className="mt-10 h-px w-28 bg-gold"/><p className="mt-9 text-lg text-ivory/75">Thoughtfully crafted for</p><p className="mt-2 font-serif text-4xl md:text-5xl">{snapshot.traveller.name}</p></div>
        <div className="grid gap-5 border-t border-ivory/20 pt-8 sm:grid-cols-3"><CoverMetric icon={CalendarDays} label="Journey" value={`${snapshot.journey.days} days · ${snapshot.journey.nights} nights`}/><CoverMetric icon={Users} label="Travellers" value={travellerSummary}/><CoverMetric icon={Compass} label="Travel dates" value={`${date(snapshot.journey.startDate)} — ${date(snapshot.journey.endDate)}`}/></div>
      </div>
    </section>

    <div className="mx-auto max-w-6xl px-5 py-16 md:px-10 md:py-24">
      <section className="proposal-section grid gap-10 rounded-[2rem] bg-white p-8 shadow-sm md:grid-cols-[.65fr_1.35fr] md:p-12"><div><p className="eyebrow">A note from Roam Ceylon</p><h2 className="mt-4 font-serif text-4xl">Dear {snapshot.traveller.name.split(" ")[0]},</h2></div><p className="font-serif text-2xl leading-relaxed text-slate/80">{snapshot.introduction}</p></section>

      <ProposalHeading eyebrow="Your journey, beautifully connected" title="Journey at a glance"/>
      <section className="proposal-section grid overflow-hidden rounded-[2rem] bg-forest text-ivory lg:grid-cols-[.8fr_1.2fr]"><JourneyMap snapshot={snapshot}/><div className="p-8 md:p-12"><div className="grid gap-0">{snapshot.journey.route.map((stop,index)=><div key={stop.key} className="grid grid-cols-[2rem_1fr] gap-4"><div className="relative flex justify-center"><span className={`z-10 mt-1 size-3 rounded-full border-2 ${stop.kind==="destination"?"border-gold bg-gold":"border-ivory/70 bg-forest"}`}/>{index<snapshot.journey.route.length-1?<span className="absolute bottom-0 top-4 border-l border-dashed border-ivory/30"/>:null}</div><div className="pb-7"><span className="text-[.62rem] font-bold uppercase tracking-[.2em] text-gold-light">{stop.kind}</span><strong className="mt-1 block font-serif text-xl">{stop.name}</strong>{stop.nights?<small className="mt-1 block text-ivory/55">{stop.nights} night{stop.nights===1?"":"s"}</small>:null}</div></div>)}</div></div></section>

      <ProposalHeading eyebrow="Day by day" title="Your journey unfolds"/>
      <div className="grid gap-5">{snapshot.days.map(day=><article key={day.day} className="proposal-card grid overflow-hidden rounded-[1.75rem] bg-white md:grid-cols-[180px_1fr]"><div className="bg-sand-light p-7"><span className="text-xs font-bold uppercase tracking-[.2em] text-gold">Day {String(day.day).padStart(2,"0")}</span><strong className="mt-3 block font-serif text-xl">{day.date?date(day.date):"Flexible"}</strong><span className="mt-2 flex items-center gap-2 text-xs text-stone"><MapPin className="size-3.5"/>{day.destination}</span></div><div className="p-7 md:p-9"><h3 className="font-serif text-3xl">{day.title}</h3>{day.route?<p className="mt-2 text-sm font-semibold text-gold">{day.route}</p>:null}<div className="mt-6 grid gap-4 sm:grid-cols-2">{day.arrival?<DayFact label="Arrival" value={day.arrival}/>:null}{day.transport.length?<DayFact label="Transport" value={day.transport.join(" · ")}/>:null}{day.stay?<DayFact label="Stay" value={`${day.stay}${day.room?` · ${day.room}`:""}`}/>:null}{day.meals.length?<DayFact label="Meals" value={day.meals.join(" · ")}/>:null}{day.guides.length?<DayFact label="Guide" value={day.guides.join(" · ")}/>:null}{day.experiences.map(item=><DayFact key={item.name} label={item.timing} value={item.name}/>)}</div>{day.notes.length?<div className="mt-6 rounded-xl bg-sand-light p-4 text-sm leading-6 text-stone">{day.notes.join(" ")}</div>:null}</div></article>)}</div>

      {snapshot.destinations.length?<><ProposalHeading eyebrow="The places within your story" title="Destination chapters"/><div className="grid gap-6 md:grid-cols-2">{snapshot.destinations.map(destination=><article key={destination.id} className="proposal-card overflow-hidden rounded-[1.75rem] bg-white">{destination.image?<div className="h-56 bg-cover bg-center" style={{backgroundImage:`url(${destination.image})`}}/>:null}<div className="p-7"><div className="flex items-center justify-between gap-3"><h3 className="font-serif text-3xl">{destination.name}</h3><span className="rounded-full bg-sand-light px-3 py-2 text-xs font-bold text-forest">{destination.nights} night{destination.nights===1?"":"s"}</span></div><p className="mt-4 text-sm leading-7 text-stone">{destination.summary}</p>{destination.highlights.length?<div className="mt-5 flex flex-wrap gap-2">{destination.highlights.map(item=><span key={item} className="rounded-full border border-gold/25 px-3 py-1.5 text-xs">{item}</span>)}</div>:null}</div></article>)}</div></>:null}

      {snapshot.stays.length?<><ProposalHeading eyebrow="Rest, considered" title="Your stays"/><div className="grid gap-6 md:grid-cols-2">{snapshot.stays.map((stay,index)=><article key={`${stay.name}-${index}`} className="proposal-card overflow-hidden rounded-[1.75rem] bg-white">{stay.image?<div className="h-52 bg-cover bg-center" style={{backgroundImage:`url(${stay.image})`}}/>:null}<div className="p-7"><p className="eyebrow">Your stay in {stay.destination}</p><h3 className="mt-3 font-serif text-3xl">{stay.name}</h3><div className="mt-6 grid grid-cols-2 gap-4 text-sm"><Fact label="Nights" value={String(stay.nights)}/><Fact label="Rooms" value={String(stay.rooms)}/><Fact label="Room" value={stay.room}/><Fact label="Meal plan" value={stay.mealPlan}/>{stay.checkIn?<Fact label="Check-in" value={date(stay.checkIn)}/>:null}{stay.checkOut?<Fact label="Check-out" value={date(stay.checkOut)}/>:null}</div><Availability value={stay.confirmation}/>{stay.inclusions.length?<ul className="mt-5 grid gap-2 text-sm text-stone">{stay.inclusions.map(item=><li key={item} className="flex gap-2"><Check className="mt-1 size-4 shrink-0 text-gold"/>{item}</li>)}</ul>:null}</div></article>)}</div></>:null}

      {snapshot.transport.length?<><ProposalHeading eyebrow="Seamless movement" title="Getting around"/><section className="proposal-section overflow-hidden rounded-[2rem] bg-white">{snapshot.transport.map((leg,index)=><div key={`${leg.from}-${leg.to}-${index}`} className="grid gap-5 border-b border-stone/15 p-7 last:border-0 md:grid-cols-[1fr_2rem_1fr_1.2fr]"><div><span className="eyebrow">From</span><strong className="mt-2 block">{leg.from}</strong></div><ChevronDown className="hidden self-center text-gold md:block md:-rotate-90"/><div><span className="eyebrow">To</span><strong className="mt-2 block">{leg.to}</strong></div><div><span className="eyebrow">Your service</span><strong className="mt-2 block font-serif text-xl">{leg.service}</strong>{leg.details.map(item=><small key={item} className="mt-1 block text-stone">{item}</small>)}<Availability value={leg.confirmation}/></div></div>)}</section></>:null}

      {snapshot.guides.length?<><ProposalHeading eyebrow="Local knowledge, personally shared" title="Your guides"/><div className="grid gap-5 md:grid-cols-2">{snapshot.guides.map((guide,index)=><article key={`${guide.name}-${index}`} className="proposal-card rounded-[1.75rem] bg-forest p-7 text-ivory"><span className="text-xs font-bold uppercase tracking-widest text-gold-light">{guide.role}</span><h3 className="mt-3 font-serif text-3xl">{guide.name}</h3>{guide.destination?<p className="mt-2 text-ivory/60">{guide.destination}</p>:null}{guide.languages.length?<p className="mt-5 text-sm">{guide.languages.join(" · ")}</p>:null}<Availability value={guide.confirmation} dark/></article>)}</div></>:null}

      {snapshot.experiences.length?<><ProposalHeading eyebrow="Moments worth travelling for" title="Your experiences"/><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{snapshot.experiences.map((experience,index)=><article key={`${experience.name}-${index}`} className="proposal-card overflow-hidden rounded-[1.75rem] bg-white">{experience.image?<div className="h-52 bg-cover bg-center" style={{backgroundImage:`url(${experience.image})`}}/>:null}<div className="p-6"><div className="flex items-center justify-between gap-2"><span className="eyebrow">{experience.destination}</span><ExperienceStatus value={experience.status}/></div><h3 className="mt-3 font-serif text-2xl leading-tight">{experience.name}</h3><p className="mt-4 line-clamp-4 text-sm leading-6 text-stone">{experience.description}</p><div className="mt-5 grid gap-2 border-t border-stone/15 pt-4 text-xs text-stone">{experience.duration?<span className="flex gap-2"><Clock3 className="size-4 text-gold"/>{experience.duration}</span>:null}<span className="flex gap-2"><ShieldCheck className="size-4 text-gold"/>{experience.admission}</span></div></div></article>)}</div></>:null}

      {snapshot.optionalItems.length?<><ProposalHeading eyebrow="Available by request" title="Optional additions"/><section className="proposal-section grid gap-4 rounded-[2rem] border border-gold/25 bg-white p-8 md:grid-cols-2 md:p-10">{snapshot.optionalItems.map((item,index)=><article key={`${item.name}-${index}`} className="rounded-2xl bg-sand-light p-6"><span className="eyebrow">Not included in journey total</span><h3 className="mt-3 font-serif text-2xl">{item.name}</h3><p className="mt-3 text-sm leading-6 text-stone">{item.description}</p>{item.price!==undefined&&item.currency?<strong className="mt-5 block text-lg">{money(item.price,item.currency)}</strong>:null}</article>)}</section></>:null}

      <ProposalHeading eyebrow="Clear from the beginning" title="What your journey includes"/>
      <section className="proposal-section grid overflow-hidden rounded-[2rem] bg-white md:grid-cols-2"><div className="p-8 md:p-10"><h3 className="font-serif text-3xl text-forest">Included</h3><ul className="mt-6 grid gap-4">{snapshot.inclusions.map(item=><li key={item} className="flex gap-3 text-sm leading-6"><span className="grid size-6 shrink-0 place-items-center rounded-full bg-forest text-ivory"><Check className="size-3.5"/></span>{item}</li>)}</ul></div><div className="bg-sand-light p-8 md:p-10"><h3 className="font-serif text-3xl">Not included</h3><ul className="mt-6 grid gap-4">{snapshot.exclusions.map(item=><li key={item} className="flex gap-3 text-sm leading-6 text-stone"><span className="grid size-6 shrink-0 place-items-center rounded-full bg-white"><X className="size-3.5"/></span>{item}</li>)}</ul></div></section>

      <ProposalHeading eyebrow="Your journey investment" title="One clear, considered price"/>
      <section className="proposal-section overflow-hidden rounded-[2rem] bg-forest text-ivory"><div className="grid gap-8 p-8 md:grid-cols-[1fr_auto] md:p-12"><div><p className="text-sm text-ivory/60">Total journey price</p><strong className="mt-2 block font-serif text-5xl md:text-6xl">{money(snapshot.pricing.total,snapshot.pricing.currency)}</strong><p className="mt-4 text-sm text-ivory/60">For {travellerSummary} · Equivalent to {money(snapshot.pricing.perPerson,snapshot.pricing.currency)} per traveller</p></div><div className="self-center rounded-2xl bg-white/8 px-6 py-5 text-sm"><ShieldCheck className="mb-3 size-6 text-gold-light"/><strong>All stated mandatory charges included</strong><p className="mt-2 max-w-xs leading-6 text-ivory/55">Any item payable directly or subject to confirmation is identified within this proposal.</p></div></div><div className="border-t border-white/10 p-8 md:p-12"><div className="grid gap-3">{snapshot.pricing.breakdown.map(line=><div key={line.key} className="flex items-baseline justify-between gap-5 text-sm"><span className="text-ivory/65">{line.label}</span><strong>{money(line.amount,snapshot.pricing.currency)}</strong></div>)}</div></div></section>

      <div className="grid gap-7 lg:grid-cols-2"><section className="proposal-section mt-16 rounded-[2rem] bg-white p-8 md:p-10"><p className="eyebrow">Payment schedule</p><h2 className="mt-4 font-serif text-4xl">A clear path to confirmation</h2>{snapshot.payment.depositAmount!==null?<div className="mt-8 grid gap-4"><PaymentLine label="Deposit" value={snapshot.payment.depositAmount} currency={snapshot.pricing.currency} due={snapshot.payment.depositDueDate?`Due ${date(snapshot.payment.depositDueDate)}`:snapshot.payment.depositDueLabel}/><PaymentLine label="Remaining balance" value={snapshot.payment.balanceAmount??0} currency={snapshot.pricing.currency} due={snapshot.payment.balanceDueDate?`Due ${date(snapshot.payment.balanceDueDate)}`:"Due date confirmed before booking"}/>{snapshot.payment.paidAmount>0?<PaymentLine label="Payments received" value={snapshot.payment.paidAmount} currency={snapshot.pricing.currency} due="Recorded by Roam Ceylon"/>:null}</div>:<p className="mt-6 text-sm leading-7 text-stone">Your journey designer will confirm the applicable deposit and balance dates before any payment is requested.</p>}</section><section className="proposal-section mt-0 rounded-[2rem] bg-white p-8 md:mt-16 md:p-10"><p className="eyebrow">Important information</p><h2 className="mt-4 font-serif text-4xl">Before you approve</h2><ul className="mt-7 grid gap-4 text-sm leading-6 text-stone">{snapshot.importantInformation.map(item=><li key={item} className="flex gap-3"><Sparkles className="mt-1 size-4 shrink-0 text-gold"/>{item}</li>)}</ul>{snapshot.validUntil?<p className="mt-6 rounded-xl bg-sand-light p-4 text-sm font-semibold">Proposal valid until {date(snapshot.validUntil)}</p>:null}</section></div>

      {snapshot.traveller.requirements.length?<section className="proposal-section mt-16 rounded-[2rem] border border-gold/25 bg-white p-8 md:p-10"><p className="eyebrow">What matters to you</p><h2 className="mt-4 font-serif text-4xl">Your recorded requirements</h2><div className="mt-6 grid gap-3 text-sm leading-7 text-stone">{snapshot.traveller.requirements.map(item=><p key={item}>{item}</p>)}</div></section>:null}

      <section className="proposal-section mt-16 overflow-hidden rounded-[2rem] bg-forest text-ivory"><div className="grid gap-8 p-8 md:grid-cols-[.8fr_1.2fr] md:p-12"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-gold-light">The value behind every detail</p><h2 className="mt-4 font-serif text-4xl">Your journey, taken care of.</h2></div><p className="self-center text-sm leading-7 text-ivory/70">From the moment you arrive until your final departure, Roam Ceylon coordinates the details behind your journey — stays, transport, experiences and local arrangements — so you can simply experience Sri Lanka. One thoughtful design, local expertise and one accountable travel partner throughout.</p></div></section>

      <ProposalHeading eyebrow="What happens next" title="From proposal to Sri Lanka"/><ol className="grid gap-4 md:grid-cols-5">{snapshot.nextSteps.map((step,index)=><li key={step} className="proposal-card rounded-2xl bg-white p-5"><span className="font-serif text-3xl text-gold">{String(index+1).padStart(2,"0")}</span><p className="mt-4 text-sm leading-6">{step}</p></li>)}</ol>
      {snapshot.terms?<section className="proposal-section mt-16 rounded-[2rem] bg-white p-8 md:p-10"><p className="eyebrow">Terms & booking notes</p><p className="mt-5 whitespace-pre-wrap text-sm leading-7 text-stone">{snapshot.terms}</p></section>:null}
      {snapshot.benefits?.length?<BenefitSection snapshot={snapshot}/>:null}
      {actions?<div className="proposal-actions mt-16">{actions}</div>:null}
    </div>
    <footer className="proposal-footer bg-slate px-6 py-14 text-ivory"><div className="mx-auto grid max-w-6xl gap-8 md:grid-cols-[1fr_1fr_auto]"><div><strong className="font-serif text-3xl">Roam Ceylon</strong><p className="mt-3 text-sm text-gold-light">{snapshot.brand.line}</p></div><div className="grid gap-2 text-sm text-ivory/65"><a href={`tel:${snapshot.contact.hotline.replace(/\s/g,"")}`}>{snapshot.contact.hotline}</a><a href={snapshot.contact.whatsappUrl}>WhatsApp Roam Ceylon</a>{snapshot.contact.email?<a href={`mailto:${snapshot.contact.email}`}>{snapshot.contact.email}</a>:null}<p className="whitespace-pre-line">{snapshot.contact.address}</p>{snapshot.contact.websiteUrl?<a href={snapshot.contact.websiteUrl}>{snapshot.contact.websiteUrl.replace(/^https?:\/\//,"")}</a>:null}</div><div className="grid justify-items-start gap-3 md:justify-items-end"><img className="size-28 rounded-xl bg-white p-2" src={`https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=${encodeURIComponent(snapshot.contact.whatsappUrl)}`} alt="WhatsApp Roam Ceylon QR code"/><span className="text-xs text-ivory/55">Scan to chat on WhatsApp</span></div></div><div className="mx-auto mt-10 flex max-w-6xl flex-wrap gap-x-8 gap-y-2 border-t border-white/10 pt-6 text-[.65rem] text-ivory/45"><span>{snapshot.proposalReference} · Version {snapshot.version}</span>{snapshot.contact.businessRegistrationNumber?<span>Business Registration No. {snapshot.contact.businessRegistrationNumber}</span>:null}{snapshot.contact.sltdaRegistrationNumber?<span>SLTDA Registration No. {snapshot.contact.sltdaRegistrationNumber}</span>:null}</div></footer>
  </article>
}

function ProposalHeading({eyebrow,title}:{eyebrow:string;title:string}){return <div className="proposal-heading mb-8 mt-20"><p className="eyebrow">{eyebrow}</p><h2 className="mt-4 max-w-3xl font-serif text-4xl md:text-5xl">{title}</h2></div>}
function BenefitSection({snapshot}:{snapshot:ProposalSnapshot}){const benefits=snapshot.benefits??[],savings=benefits.reduce((sum,item)=>sum+item.verifiedSavings,0);return <><ProposalHeading eyebrow="Privileges chosen with care" title="The Roam Ceylon Difference"/><section className="proposal-section overflow-hidden rounded-[2rem] bg-white"><div className="grid gap-5 p-8 md:grid-cols-2 md:p-10">{benefits.map(item=><article key={`${item.code}-${item.scopeLabel??item.scope}`} className="rounded-2xl border border-gold/20 bg-sand-light p-6"><div className="flex flex-wrap items-center justify-between gap-2"><span className="eyebrow">{item.type.replaceAll("_"," ")}</span><BenefitConfidence value={item.confidence}/></div><h3 className="mt-3 font-serif text-2xl">{item.title}</h3><p className="mt-3 text-sm leading-6 text-stone">{item.description}</p>{item.scopeLabel?<p className="mt-3 text-xs font-semibold text-forest">{item.scopeLabel}</p>:null}{item.preferredRate!==undefined&&item.currency?<div className="mt-5 border-t border-gold/15 pt-4 text-sm"><strong>{money(item.preferredRate,item.currency)}{item.rateUnit?` · ${item.rateUnit}`:""}</strong>{item.verifiedSavings>0&&item.referenceRate!==undefined?<p className="mt-1 text-xs text-stone">Comparable reference {money(item.referenceRate,item.currency)} · verified value {money(item.verifiedSavings,item.currency)}</p>:null}</div>:null}</article>)}</div>{savings>0?<div className="border-t border-gold/20 bg-forest px-8 py-5 text-ivory md:px-10"><span className="text-sm text-ivory/65">Total verified preferred value</span><strong className="ml-3 font-serif text-2xl">{money(savings,benefits.find(item=>item.currency)?.currency??snapshot.pricing.currency)}</strong></div>:null}</section></>}
function BenefitConfidence({value}:{value:string}){const labels:Record<string,string>={guaranteed_by_roam_ceylon:"Guaranteed by Roam Ceylon",confirmed_partner_benefit:"Confirmed partner benefit",subject_to_availability:"Subject to availability"};return <span className="rounded-full bg-forest/8 px-3 py-1.5 text-[.58rem] font-bold uppercase tracking-wider text-forest">{labels[value]??value}</span>}
function CoverMetric({icon:Icon,label,value}:{icon:typeof CalendarDays;label:string;value:string}){return <div className="flex gap-3"><Icon className="mt-1 size-5 text-gold-light"/><div><span className="block text-[.62rem] font-bold uppercase tracking-widest text-ivory/50">{label}</span><strong className="mt-1 block text-sm">{value}</strong></div></div>}
function Fact({label,value}:{label:string;value:string}){return <div><span className="block text-[.62rem] font-bold uppercase tracking-widest text-stone">{label}</span><strong className="mt-1 block">{value}</strong></div>}
function DayFact({label,value}:{label:string;value:string}){return <div><span className="block text-[.62rem] font-bold uppercase tracking-widest text-gold">{label}</span><p className="mt-1 text-sm leading-6">{value}</p></div>}
function Availability({value,dark=false}:{value:string;dark?:boolean}){return <span className={`mt-5 inline-flex rounded-full px-3 py-1.5 text-[.62rem] font-bold uppercase tracking-wider ${dark?"bg-white/10 text-gold-light":value==="Confirmed"?"bg-forest/8 text-forest":"bg-gold/10 text-gold"}`}>{value}</span>}
function ExperienceStatus({value}:{value:string}){const labels:Record<string,string>={included:"Included",optional:"Optional",not_included:"Not included",subject_to_confirmation:"Subject to confirmation"};return <span className="rounded-full bg-forest px-2.5 py-1 text-[.55rem] font-bold uppercase tracking-wider text-ivory">{labels[value]??value}</span>}
function PaymentLine({label,value,currency,due}:{label:string;value:number;currency:string;due:string}){return <div className="flex items-end justify-between gap-4 border-b border-stone/15 pb-4"><div><span className="text-xs font-bold uppercase tracking-widest text-stone">{label}</span><small className="mt-1 block text-stone">{due}</small></div><strong className="font-serif text-2xl">{money(value,currency)}</strong></div>}
function JourneyMap({snapshot}:{snapshot:ProposalSnapshot}){const located=snapshot.journey.route.filter(stop=>Number.isFinite(stop.latitude)&&Number.isFinite(stop.longitude)),points=located.map(stop=>point(stop.latitude!,stop.longitude!)),polyline=points.map(item=>`${item.x},${item.y}`).join(" ");return <div className="relative min-h-[520px] p-8"><svg viewBox="0 0 220 400" role="img" aria-label="Map of the curated Sri Lanka journey" className="mx-auto h-[480px] max-w-full"><path d="M198.4 270.3 190.6 314.7 175.7 335.1 145.2 356.3 121.7 364.6 103 374.8 88.9 376.7 73.2 371.1 53.7 346.2 47.4 316.5 39.6 282.3 36.4 262 34.1 224 27.8 176.9 38 145.4 47.4 117.7 45.8 104.7 55.2 90.9 59.9 76.1 56 61.2 63 47.4 73.2 38.1 67 24.2 63 17.8 78.7 24.2 94.3 42.7 86.5 52 106.1 61.2 120.2 79.7 133.5 102.9 145.2 126 157 149.1 164.8 176.9 172.6 190.7 184.3 213.9 190.6 237Z" fill="rgba(255,253,248,.06)" stroke="rgba(255,253,248,.42)" strokeWidth="1.5"/>{polyline?<polyline points={polyline} fill="none" stroke="#d7ad65" strokeWidth="2.5" strokeDasharray="6 7" strokeLinecap="round"/>:null}{located.map((stop,index)=>{const p=points[index];return <g key={stop.key} transform={`translate(${p.x} ${p.y})`}><circle r="7" fill="#d7ad65" stroke="#fffdf8" strokeWidth="2"/><text y="2.5" textAnchor="middle" fontSize="7" fontWeight="700" fill="#123d33">{index+1}</text></g>})}</svg></div>}
