import Image from "next/image";
import Link from "next/link";
import {ArrowLeft,Check} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Badge} from "@/components/ui/badge";
import {GalleryCarousel} from "./gallery-carousel";

export function DetailPage({backHref,backLabel,title,eyebrow,image,alt,description,fullDescription,metadata=[],gallery=[]}:{backHref:string;backLabel:string;title:string;eyebrow?:string|null;image:string|null;alt:string|null;description?:string|null;fullDescription?:string|null;metadata?:Array<[string,string|null|undefined]>;gallery?:string[]}){
  const images=[image,...gallery].filter(Boolean) as string[];
  return <><section className="relative min-h-[72svh] bg-slate text-ivory">{image&&<Image src={image} alt={alt||title} fill priority sizes="100vw" className="object-cover opacity-65"/>}<div className="absolute inset-0 bg-gradient-to-t from-slate via-slate/20 to-transparent"/><div className="shell relative flex min-h-[72svh] flex-col justify-end pb-16"><Link href={backHref} className="mb-8 inline-flex w-fit items-center gap-2 text-sm"><ArrowLeft className="size-4"/>{backLabel}</Link>{eyebrow&&<Badge className="mb-5 w-fit">{eyebrow}</Badge>}<h1 className="display max-w-5xl">{title}</h1>{description&&<p className="mt-6 max-w-2xl text-lg leading-8 text-ivory/80">{description}</p>}</div></section><section className="section"><div className="shell grid gap-14 lg:grid-cols-[1fr_360px]"><article><p className="eyebrow mb-5">The experience</p><h2 className="heading">A closer look</h2><p className="prose-luxury mt-7 max-w-3xl">{fullDescription||description}</p>{images.length>1&&<GalleryCarousel images={images.slice(1)} title={title}/>}</article><aside className="h-fit rounded-3xl border border-stone/20 bg-white p-7 lg:sticky lg:top-28"><h2 className="font-serif text-2xl">Plan this into your journey</h2><div className="my-6 grid gap-4">{metadata.filter(([,value])=>value).map(([label,value])=><div key={label} className="flex items-center gap-3 border-b border-stone/15 pb-4"><Check className="size-4 text-gold"/><span><small className="block text-stone">{label}</small><strong className="text-sm">{value}</strong></span></div>)}</div><Button asChild className="w-full"><Link href="/journey-builder">Add to my journey</Link></Button><p className="mt-4 text-center text-xs text-stone">No payment or commitment required.</p></aside></div></section></>
}
