"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {ArrowRight,Route} from "lucide-react";
import {AdminShell} from "./admin-shell";
import {createClient} from "@/lib/supabase/client";
import type {Database} from "@/lib/database.types";

type Enquiry=Pick<Database["public"]["Views"]["staff_journey_request_summary"]["Row"],"id"|"journey_reference"|"traveller_name"|"travel_start_date"|"travel_end_date"|"status"|"created_at">;
type Curated=Pick<Database["public"]["Tables"]["curated_journeys"]["Row"],"enquiry_id"|"status"|"updated_at">;
const labels={not_started:"Not Started",designing:"Designing",ready_for_allocation:"Ready for Allocation",allocation_in_progress:"Allocation in Progress",ready_for_proposal:"Ready for Proposal"};
export function JourneyStudioInbox(){const router=useRouter(),[rows,setRows]=useState<Array<Enquiry&{studio:Curated|null}>>([]),[message,setMessage]=useState(""),[loading,setLoading]=useState(true);useEffect(()=>{void(async()=>{const database=createClient(),{data:{session}}=await database.auth.getSession();if(!session){router.replace("/admin/login");return}const [enquiries,curated]=await Promise.all([database.from("staff_journey_request_summary").select("id,journey_reference,traveller_name,travel_start_date,travel_end_date,status,created_at").order("created_at",{ascending:false}),database.from("curated_journeys").select("enquiry_id,status,updated_at")]);if(enquiries.error||curated.error)setMessage(enquiries.error?.message??curated.error?.message??"Journey Studio could not be loaded.");else setRows((enquiries.data??[]).map(enquiry=>({...enquiry,studio:(curated.data??[]).find(item=>item.enquiry_id===enquiry.id)??null})));setLoading(false)})()},[router]);return <AdminShell requiredPermission="journey.design.view"><div className="mx-auto max-w-7xl"><p className="eyebrow">Itinerary design</p><h1 className="mt-3 font-serif text-5xl">Journey Studio</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-stone">Transform immutable traveller briefs into considered, operationally sound Curated Journeys.</p>{message?<p role="alert" className="mt-6 rounded-xl bg-red-50 p-4 text-sm text-red-800">{message}</p>:null}<div className="mt-8 overflow-hidden rounded-3xl border border-stone/15 bg-white">{loading?<div className="h-60 animate-pulse bg-sand-light"/>:rows.length?<div className="divide-y divide-stone/15">{rows.map(row=><Link key={row.id} href={`/admin/journey-studio/${row.id}`} className="grid gap-3 p-5 transition hover:bg-sand-light md:grid-cols-[1fr_210px_190px_auto] md:items-center"><div><strong className="font-serif text-xl">{row.traveller_name??row.journey_reference}</strong><p className="mt-1 text-xs text-stone">{row.journey_reference}</p></div><span className="text-sm">{row.travel_start_date??"Dates open"}{row.travel_end_date?` → ${row.travel_end_date}`:""}</span><span className="rounded-full bg-forest/8 px-3 py-2 text-center text-xs font-bold text-forest">{row.studio?labels[row.studio.status]:"Brief awaiting curation"}</span><span className="flex items-center gap-2 text-sm font-semibold text-gold"><Route className="size-4"/>Open<ArrowRight className="size-4"/></span></Link>)}</div>:<div className="p-12 text-center text-stone">No journey requests are available.</div>}</div></div></AdminShell>}
