"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {FileText,ImageIcon,Search} from "lucide-react";
import {createClient} from "@/lib/supabase/client";
import type {Database} from "@/lib/database.types";

type Application=Database["public"]["Tables"]["partner_applications"]["Row"];
type Counts={media:number;documents:number};
const filters=[["all","All"],["accommodation","Accommodation"],["vehicle","Vehicles"],["guide","Guides"],["submitted","Submitted"],["under_review","Under review"],["needs_information","Needs information"],["approved","Approved"],["rejected","Rejected"],["converted","Converted"]] as const;
const labels:Record<string,string>={accommodation:"Accommodation",vehicle:"Vehicle",guide:"Guide",submitted:"Submitted",under_review:"Under review",needs_information:"Needs information",approved:"Approved",rejected:"Rejected",converted:"Converted"};

export function PartnerApplicationInbox(){
  const router=useRouter();const [rows,setRows]=useState<Application[]>([]);const [counts,setCounts]=useState<Record<string,Counts>>({});const [filter,setFilter]=useState("all");const [search,setSearch]=useState("");const [loading,setLoading]=useState(true);const [loadError,setLoadError]=useState("");
  useEffect(()=>{void (async()=>{const database=createClient();const {data:{session}}=await database.auth.getSession();if(!session){router.replace("/admin/login");return}const {data,error}=await database.from("partner_applications").select("*").order("created_at",{ascending:false});if(error){setLoadError(`Applications could not be loaded: ${error.message}`);setLoading(false);return}const applications=(data??[]).map(item=>{const raw=item as unknown as Record<string,unknown>;return {...item,partner_type:(raw.partner_type||raw.application_type) as Application["partner_type"],application_reference:String(raw.application_reference||`Legacy-${String(raw.id).slice(0,8).toUpperCase()}`),status:(raw.status==="pending"?"submitted":raw.status==="needs_changes"?"needs_information":raw.status) as Application["status"],submitted_at:String(raw.submitted_at||raw.created_at||"")} as Application});setRows(applications);if(applications.length){const {data:files}=await database.from("partner_application_files").select("application_id,bucket_id").in("application_id",applications.map(item=>item.id));const next:Record<string,Counts>={};for(const file of files??[]){next[file.application_id]??={media:0,documents:0};if(file.bucket_id==="partner-application-media")next[file.application_id].media+=1;else next[file.application_id].documents+=1}setCounts(next)}setLoading(false)})()},[router]);
  const visible=useMemo(()=>rows.filter(item=>(filter==="all"||item.partner_type===filter||item.status===filter)&&`${item.applicant_name} ${item.business_name} ${item.email} ${item.phone} ${item.district} ${item.application_reference}`.toLowerCase().includes(search.toLowerCase())),[rows,filter,search]);
  return <main className="min-h-screen bg-[#f4f3ef] p-6 md:p-10"><div className="mx-auto max-w-7xl"><Link href="/admin/dashboard" className="text-sm font-semibold text-forest">← Admin dashboard</Link><p className="eyebrow mb-3 mt-8">Marketplace review</p><h1 className="font-serif text-4xl md:text-5xl">Partner applications</h1><p className="mt-3 text-slate/60">Review applicants, request clarification and convert approved applications into unpublished draft listings.</p>{loadError&&<div role="alert" className="mt-6 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{loadError}<span className="mt-2 block">Confirm the latest Supabase migration is applied and your profile has an admin or editor role.</span></div>}<div className="mt-8 flex flex-wrap gap-2">{filters.map(([key,label])=><button key={key} onClick={()=>setFilter(key)} className={`rounded-full px-4 py-2 text-xs font-semibold ${filter===key?"bg-forest text-white":"bg-white text-stone"}`}>{label}</button>)}</div><label className="mt-5 flex max-w-xl items-center gap-3 rounded-2xl border border-stone/15 bg-white px-4"><Search className="size-4 text-stone"/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search name, business, contact, base or reference…" className="w-full bg-transparent py-4 text-sm outline-none"/></label><div className="mt-7 overflow-hidden rounded-3xl border border-stone/15 bg-white">{loading?<div className="h-64 animate-pulse bg-sand-light"/>:loadError?<div className="p-12 text-center text-stone">Resolve the database message above, then reload this page.</div>:visible.length?<div className="divide-y divide-stone/15">{visible.map(item=>{const fileCounts=counts[item.id]??{media:0,documents:0};return <Link key={item.id} href={`/admin/partner-applications/${item.id}`} className="grid gap-3 p-5 transition hover:bg-sand-light md:grid-cols-[1fr_170px_150px_120px] md:items-center"><div><div className="flex flex-wrap items-center gap-2"><strong className="font-serif text-xl">{item.business_name||item.applicant_name}</strong><span className="rounded-full bg-gold/10 px-2 py-1 text-[.65rem] font-bold uppercase text-gold">{labels[item.partner_type]||item.partner_type}</span></div><p className="mt-1 text-sm text-stone">{item.applicant_name} · {item.district||"Base not provided"} · {item.application_reference}</p></div><span className="text-sm capitalize">{labels[item.status]||item.status}</span><span className="text-xs text-stone">{item.submitted_at?new Date(item.submitted_at).toLocaleDateString():"Draft"}</span><span className="flex gap-3 text-xs text-stone"><span className="flex items-center gap-1"><ImageIcon className="size-3"/>{fileCounts.media}</span><span className="flex items-center gap-1"><FileText className="size-3"/>{fileCounts.documents}</span></span></Link>})}</div>:<div className="p-12 text-center text-stone">No applications match these filters.</div>}</div></div></main>;
}
