"use client";

import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {Check,ChevronLeft,ChevronRight,FileText,ImagePlus,Plus,Trash2} from "lucide-react";
import {Button} from "@/components/ui/button";
import {cn} from "@/lib/utils";

type PartnerType="accommodation"|"vehicle"|"guide";
type Values=Record<string,string|boolean>;
type Entry=Record<string,string|boolean>;
const provinces=["Central","Eastern","North Central","Northern","North Western","Sabaragamuwa","Southern","Uva","Western"];
const districts=["Ampara","Anuradhapura","Badulla","Batticaloa","Colombo","Galle","Gampaha","Hambantota","Jaffna","Kalutara","Kandy","Kegalle","Kilinochchi","Kurunegala","Mannar","Matale","Matara","Monaragala","Mullaitivu","Nuwara Eliya","Polonnaruwa","Puttalam","Ratnapura","Trincomalee","Vavuniya"];
const initial:Values={applicantName:"",businessName:"",email:"",countryCode:"+94",phone:"",preferredContactMethod:"whatsapp",address:"",district:"",province:"",website:"",socialUrl:"",introduction:"",heardFrom:"",consent:false,accurate:false,honeypot:"",propertyType:"Hotel",destination:"",totalRooms:"",guestCapacity:"",pricingBasis:"Per room per night",startingPrice:"",currency:"USD",yearEstablished:"",starCategory:"",mealPlans:"",checkIn:"",checkOut:"",amenities:"",parking:"Yes",driverAccommodation:"No",guideAccommodation:"No",accessibility:"",sustainablePractices:"",operatorType:"Company",operatingBase:"",coverage:"Island-wide",vehicleCount:"1",airportTransfers:"Yes",islandWide:"Yes",driverIncluded:"Yes",guideType:"National guide",homeBase:"",languages:"English",yearsExperience:"",specialistKnowledge:"",destinationsCovered:"",experiencesSupported:"",halfDayFee:"",fullDayFee:"",multiDay:"Yes",overnightTrips:"Yes",driverGuide:"No",licenceNumber:"",associationMembership:"",availabilityNotes:""};
const steps=["Contact","Professional details","Service details","Files & confirmation"];
const fieldsByType={
  accommodation:[["propertyType","Property type"],["destination","Destination or nearest town"],["totalRooms","Rooms or units"],["guestCapacity","Maximum guest capacity"],["yearEstablished","Year established"],["starCategory","Star category"],["startingPrice","Indicative starting price"],["pricingBasis","Pricing basis"],["mealPlans","Meal plans available"],["checkIn","Check-in time"],["checkOut","Check-out time"],["amenities","Amenities"],["parking","Parking available"],["driverAccommodation","Driver accommodation"],["guideAccommodation","Guide accommodation"],["accessibility","Accessibility information"],["sustainablePractices","Sustainable practices"]],
  vehicle:[["operatorType","Owner type"],["operatingBase","Operating base"],["coverage","Service coverage"],["vehicleCount","Number of vehicles"],["airportTransfers","Airport transfers"],["islandWide","Island-wide trips"],["driverIncluded","Driver included"],["languages","Languages spoken by drivers"]],
  guide:[["guideType","Guide type"],["homeBase","Home base"],["destinationsCovered","Destinations covered"],["languages","Languages"],["yearsExperience","Years of experience"],["specialistKnowledge","Specialist knowledge"],["experiencesSupported","Experiences supported"],["halfDayFee","Half-day indicative fee"],["fullDayFee","Full-day indicative fee"],["multiDay","Multi-day availability"],["overnightTrips","Overnight trips"],["driverGuide","Driver-guide availability"],["licenceNumber","Licence number"],["associationMembership","Association membership"],["availabilityNotes","Availability notes"]]
} as const;

export function PartnerApplicationForm({initialType}:{initialType:PartnerType}){
  const router=useRouter();
  const [type,setType]=useState<PartnerType>(initialType);
  const [step,setStep]=useState(0);
  const [values,setValues]=useState<Values>(initial);
  const [entries,setEntries]=useState<Entry[]>([]);
  const [media,setMedia]=useState<File[]>([]);
  const [documents,setDocuments]=useState<File[]>([]);
  const [error,setError]=useState("");
  const [submitting,setSubmitting]=useState(false);
  useEffect(()=>{try{const saved=localStorage.getItem("roam-ceylon-partner-draft");if(saved){const draft=JSON.parse(saved);queueMicrotask(()=>{setType(draft.type||initialType);setValues({...initial,...draft.values});setEntries(draft.entries||[])})}}catch{}},[initialType]);
  useEffect(()=>{localStorage.setItem("roam-ceylon-partner-draft",JSON.stringify({type,values,entries}))},[type,values,entries]);
  const set=(key:string,value:string|boolean)=>setValues(current=>({...current,[key]:value}));
  const required=step===0?["applicantName","businessName","email","phone","preferredContactMethod"]:step===1?["address","district","province","introduction","heardFrom"]:step===2?fieldsByType[type].slice(0,type==="guide"?6:4).map(([key])=>key):[];
  const next=()=>{const missing=required.filter(key=>!values[key]);if(missing.length){setError("Please complete the required fields before continuing.");return}if(values.website&&!isUrl(String(values.website))||values.socialUrl&&!isUrl(String(values.socialUrl))){setError("Please enter complete website and social links, including https://.");return}setError("");setStep(current=>Math.min(3,current+1))};
  const addEntry=()=>setEntries(items=>[...items,type==="accommodation"?{name:"",description:"",capacity:"",price:"",pricingBasis:String(values.pricingBasis)}:{category:"Car",model:"",year:"",registration:"",capacity:"",luggage:"",airConditioning:"Yes",driverIncluded:"Yes",rate:"",airportRate:"",extraKmRate:"",notes:""}]);
  const updateEntry=(index:number,key:string,value:string|boolean)=>setEntries(items=>items.map((item,itemIndex)=>itemIndex===index?{...item,[key]:value}:item));
  const submit=async()=>{
    if(!values.consent||!values.accurate){setError("Confirm consent and the accuracy of the submitted information.");return}
    setSubmitting(true);setError("");
    const payload={partnerType:type,applicantName:values.applicantName,businessName:values.businessName,email:values.email,phone:`${values.countryCode} ${values.phone}`,preferredContactMethod:values.preferredContactMethod,address:values.address,district:values.district,province:values.province,website:values.website,socialUrl:values.socialUrl,introduction:values.introduction,heardFrom:values.heardFrom,consent:values.consent,accurate:values.accurate,honeypot:values.honeypot,applicationData:{...values,entries}};
    const body=new FormData();body.set("payload",JSON.stringify(payload));media.forEach(file=>body.append("media",file));documents.forEach(file=>body.append("documents",file));
    const response=await fetch("/api/partner-applications",{method:"POST",body});const result=await response.json();
    setSubmitting(false);if(!response.ok){setError(result.error||"Application could not be submitted.");return}
    localStorage.removeItem("roam-ceylon-partner-draft");router.push(`/partners/application-received?reference=${encodeURIComponent(result.reference)}&type=${encodeURIComponent(result.type)}`);
  };
  return <main className="bg-[#f4f3ef] py-16 md:py-24"><div className="shell max-w-5xl"><p className="eyebrow mb-4">Partner application</p><h1 className="font-serif text-4xl md:text-6xl">Tell us what you bring to the journey.</h1><p className="mt-5 max-w-2xl leading-7 text-slate/60">Your draft is saved on this device. Submission starts a manual Roam Ceylon review and never creates a public listing automatically.</p>
    <div className="mt-10 flex gap-2 overflow-x-auto">{steps.map((label,index)=><div key={label} className={cn("flex min-w-fit items-center gap-2 rounded-full px-4 py-2 text-xs font-bold",index===step?"bg-forest text-white":index<step?"bg-gold/15 text-forest":"bg-white text-stone")}>{index<step?<Check className="size-3"/>:index+1} {label}</div>)}</div>
    {error&&<div role="alert" className="mt-6 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</div>}
    <section className="mt-6 rounded-3xl border border-stone/15 bg-white p-6 md:p-9">{step===0&&<Grid><Select label="Partner type" value={type} onChange={value=>{setType(value as PartnerType);setEntries([])}} options={[["accommodation","Accommodation"],["vehicle","Vehicle or fleet"],["guide","Local guide"]]}/><Text label="Full name *" value={values.applicantName} onChange={value=>set("applicantName",value)}/><Text label="Business or professional name *" value={values.businessName} onChange={value=>set("businessName",value)}/><Text label="Email *" type="email" value={values.email} onChange={value=>set("email",value)}/><div className="grid grid-cols-[90px_1fr] gap-2"><Text label="Code" value={values.countryCode} onChange={value=>set("countryCode",value)}/><Text label="Phone / WhatsApp *" value={values.phone} onChange={value=>set("phone",value)}/></div><Select label="Preferred contact *" value={values.preferredContactMethod} onChange={value=>set("preferredContactMethod",value)} options={[["whatsapp","WhatsApp"],["email","Email"],["phone","Phone"]]}/><input tabIndex={-1} autoComplete="off" className="hidden" value={String(values.honeypot)} onChange={event=>set("honeypot",event.target.value)}/></Grid>}
    {step===1&&<Grid><Area label="Full address *" value={values.address} onChange={value=>set("address",value)}/><Select label="District *" value={values.district} onChange={value=>set("district",value)} options={districts.map(item=>[item,item])}/><Select label="Province *" value={values.province} onChange={value=>set("province",value)} options={provinces.map(item=>[item,item])}/><Text label="Website (optional)" type="url" value={values.website} onChange={value=>set("website",value)}/><Text label="Social media page (optional)" type="url" value={values.socialUrl} onChange={value=>set("socialUrl",value)}/><Area label="Short introduction *" value={values.introduction} onChange={value=>set("introduction",value)}/><Select label="How did you hear about us? *" value={values.heardFrom} onChange={value=>set("heardFrom",value)} options={["Recommendation","Search engine","Social media","Tourism network","Roam Ceylon team","Other"].map(item=>[item,item])}/></Grid>}
    {step===2&&<><Grid>{fieldsByType[type].map(([key,label])=>key==="propertyType"?<Select key={key} label={`${label} *`} value={values[key]} onChange={value=>set(key,value)} options={["Hotel","Boutique hotel","Villa","Guest house","Resort","Homestay","Eco lodge","Apartment","Hostel","Other"].map(item=>[item,item])}/>:key==="guideType"?<Select key={key} label={`${label} *`} value={values[key]} onChange={value=>set(key,value)} options={["National guide","Chauffeur guide","Site guide","Nature guide","Wildlife guide","Adventure guide","Cultural guide","Language specialist","Other"].map(item=>[item,item])}/>:key==="pricingBasis"?<Select key={key} label={label} value={values[key]} onChange={value=>set(key,value)} options={["Per room per night","Per person per night","Per villa per night","Per unit per night","Contact for quotation"].map(item=>[item,item])}/>:["parking","driverAccommodation","guideAccommodation","airportTransfers","islandWide","driverIncluded","multiDay","overnightTrips","driverGuide"].includes(key)?<Select key={key} label={label} value={values[key]} onChange={value=>set(key,value)} options={[["Yes","Yes"],["No","No"]]}/>:<Text key={key} label={`${label}${required.includes(key)?" *":""}`} value={values[key]} onChange={value=>set(key,value)}/>)}</Grid>{type!=="guide"&&<div className="mt-8 border-t border-stone/15 pt-7"><div className="flex items-center justify-between"><div><h2 className="font-serif text-2xl">{type==="accommodation"?"Room or unit types":"Vehicles"}</h2><p className="mt-1 text-sm text-stone">Add one or more. Roam Ceylon will refine final listing details later.</p></div><Button variant="outline" onClick={addEntry}><Plus/>Add</Button></div><div className="mt-5 grid gap-4">{entries.map((entry,index)=><div key={index} className="grid gap-3 rounded-2xl bg-sand-light p-5 md:grid-cols-3">{Object.keys(entry).map(key=><Text key={key} label={labelFor(key)} value={entry[key]} onChange={value=>updateEntry(index,key,value)}/>) }<button className="text-left text-sm text-red-700" onClick={()=>setEntries(items=>items.filter((_,itemIndex)=>itemIndex!==index))}><Trash2 className="mr-1 inline size-4"/>Remove</button></div>)}</div></div>}</>}
    {step===3&&<div className="grid gap-7"><Uploads title="Photos" icon={ImagePlus} accept="image/jpeg,image/png,image/webp" files={media} setFiles={setMedia} max={10} help="JPG, PNG or WebP. Up to 10 MB each."/><Uploads title="Verification documents" icon={FileText} accept="application/pdf,image/jpeg,image/png" files={documents} setFiles={setDocuments} max={6} help="PDF, JPG or PNG. Stored privately and never added to a public listing."/><label className="flex gap-3 rounded-2xl border border-stone/20 p-4 text-sm"><input type="checkbox" checked={Boolean(values.consent)} onChange={event=>set("consent",event.target.checked)}/>I consent to Roam Ceylon contacting me about this application.</label><label className="flex gap-3 rounded-2xl border border-stone/20 p-4 text-sm"><input type="checkbox" checked={Boolean(values.accurate)} onChange={event=>set("accurate",event.target.checked)}/>I confirm that the submitted information is accurate.</label></div>}
    <div className="mt-9 flex justify-between"><Button variant="ghost" disabled={step===0||submitting} onClick={()=>setStep(current=>current-1)}><ChevronLeft/>Back</Button>{step<3?<Button onClick={next}>Continue<ChevronRight/></Button>:<Button variant="accent" disabled={submitting} onClick={()=>void submit()}>{submitting?"Submitting and uploading…":"Submit for review"}</Button>}</div></section></div></main>;
}
const isUrl=(value:string)=>{try{return ["http:","https:"].includes(new URL(value).protocol)}catch{return false}};
const labelFor=(key:string)=>({name:"Room type",description:"Short description",capacity:"Maximum guests / passengers",price:"Indicative price",pricingBasis:"Pricing basis",category:"Vehicle category",model:"Make and model",year:"Year",registration:"Registration number",luggage:"Luggage capacity",airConditioning:"Air-conditioning",driverIncluded:"Driver included",rate:"Daily rate",airportRate:"Airport transfer rate",extraKmRate:"Extra kilometre rate",notes:"Notes"}[key]||key);
const fieldClass="rounded-xl border border-stone/25 bg-white px-4 py-3 outline-none focus:border-gold";
function Grid({children}:{children:React.ReactNode}){return <div className="grid gap-5 md:grid-cols-2">{children}</div>}
function Text({label,value,type="text",onChange}:{label:string;value:string|boolean;type?:string;onChange:(value:string)=>void}){return <label className="grid gap-2 text-sm font-semibold">{label}<input type={type} value={String(value)} onChange={event=>onChange(event.target.value)} className={fieldClass}/></label>}
function Area({label,value,onChange}:{label:string;value:string|boolean;onChange:(value:string)=>void}){return <label className="grid gap-2 text-sm font-semibold md:col-span-2">{label}<textarea rows={4} value={String(value)} onChange={event=>onChange(event.target.value)} className={fieldClass}/></label>}
function Select({label,value,onChange,options}:{label:string;value:string|boolean;onChange:(value:string)=>void;options:Array<readonly [string,string]>}){return <label className="grid gap-2 text-sm font-semibold">{label}<select value={String(value)} onChange={event=>onChange(event.target.value)} className={fieldClass}><option value="">Select…</option>{options.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>}
function Uploads({title,icon:Icon,accept,files,setFiles,max,help}:{title:string;icon:typeof ImagePlus;accept:string;files:File[];setFiles:(files:File[])=>void;max:number;help:string}){return <div><div className="flex items-center gap-3"><Icon className="size-5 text-gold"/><div><h2 className="font-serif text-xl">{title}</h2><p className="text-xs text-stone">{help}</p></div></div><label className="mt-4 grid cursor-pointer place-items-center rounded-2xl border border-dashed border-stone/30 p-7 text-center text-sm hover:border-gold"><input type="file" multiple accept={accept} className="sr-only" onChange={event=>setFiles([...files,...Array.from(event.target.files||[])].slice(0,max))}/>Choose files</label><div className="mt-3 grid gap-2">{files.map((file,index)=><div key={`${file.name}-${index}`} className="flex justify-between rounded-xl bg-sand-light px-4 py-3 text-xs"><span className="truncate">{file.name} · {(file.size/1024/1024).toFixed(1)} MB</span><button onClick={()=>setFiles(files.filter((_,itemIndex)=>itemIndex!==index))} className="text-red-700">Remove</button></div>)}</div></div>}
