"use client";

import Link from "next/link";
import {motion} from "motion/react";
import {cn} from "@/lib/utils";
import {getRouteEstimate,type LocatedRouteDestination} from "@/lib/journey/route";

type Marker={id:string;slug:string;name:string;latitude:number|null;longitude:number|null};

const point=(lat:number,lon:number)=>({x:32+((lon-79.6)/2.4)*166,y:376-((lat-5.8)/4.2)*344});

export function SriLankaMap({destinations,selectedIds=[],onSelect,className}:{destinations:Marker[];selectedIds?:string[];onSelect?:(id:string)=>void;className?:string}){
  const valid=destinations.filter((item):item is LocatedRouteDestination=>Number.isFinite(item.latitude)&&Number.isFinite(item.longitude));
  const {route,estimatedDistance,estimatedTravelDays}=getRouteEstimate(destinations,selectedIds);
  const routePoints=route.map(item=>{const value=point(item.latitude,item.longitude);return `${value.x},${value.y}`}).join(" ");
  return <section className={cn("grid overflow-hidden rounded-[2rem] bg-forest text-ivory md:grid-cols-[1fr_.75fr]",className)} aria-label="Sri Lanka destinations map"><div className="relative min-h-[520px] p-8"><svg viewBox="0 0 220 400" role="img" aria-label={`Map showing ${valid.length} destinations and ${route.length} selected stops`} className="mx-auto h-[480px] max-w-full"><path d="M198.4 270.3 190.6 314.7 175.7 335.1 145.2 356.3 121.7 364.6 103 374.8 88.9 376.7 73.2 371.1 53.7 346.2 47.4 316.5 39.6 282.3 36.4 262 34.1 224 27.8 176.9 38 145.4 47.4 117.7 45.8 104.7 55.2 90.9 59.9 76.1 56 61.2 63 47.4 73.2 38.1 67 24.2 63 17.8 78.7 24.2 94.3 42.7 86.5 52 106.1 61.2 120.2 79.7 133.5 102.9 145.2 126 157 149.1 164.8 176.9 172.6 190.7 184.3 213.9 190.6 237Z" fill="rgba(255,253,248,.07)" stroke="rgba(255,253,248,.4)" strokeWidth="1.5"/>{route.length>1&&<motion.polyline key={routePoints} points={routePoints} fill="none" stroke="#d7ad65" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" initial={{pathLength:0,opacity:0}} animate={{pathLength:1,opacity:1}} transition={{duration:1.2,ease:"easeInOut"}}/>}{valid.map(item=>{const {x,y}=point(item.latitude,item.longitude);const selected=selectedIds.includes(item.id);const order=selectedIds.indexOf(item.id);return <g key={item.id} transform={`translate(${x} ${y})`}><motion.circle initial={{scale:.7}} animate={{scale:selected?1.15:1}} r={selected?7:5} fill={selected?"#d7ad65":"#fffdf8"} stroke="#123d33" strokeWidth="2"/>{selected&&<text y="2.5" textAnchor="middle" fontSize="7" fontWeight="700" fill="#123d33">{order+1}</text>}<title>{item.name}</title></g>})}</svg></div><div className="bg-white/5 p-8"><p className="eyebrow mb-3 text-gold-light">{route.length?"Your route":"Across the island"}</p><h2 className="font-serif text-3xl">{route.length?"Journey map":"Choose a place on the map."}</h2>{route.length>0&&<div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-white/5 p-3"><span className="block text-xs text-ivory/50">Distance</span><strong>{estimatedDistance} km</strong></div><div className="rounded-xl bg-white/5 p-3"><span className="block text-xs text-ivory/50">Travel days</span><strong>{estimatedTravelDays||"—"}</strong></div></div>}<div className="mt-6 grid max-h-[300px] gap-2 overflow-auto pr-2">{valid.map(item=>onSelect?<button key={item.id} onClick={()=>onSelect(item.id)} className={cn("focus-ring rounded-xl px-4 py-3 text-left text-sm",selectedIds.includes(item.id)?"bg-gold text-slate":"bg-white/5 hover:bg-white/10")}>{selectedIds.includes(item.id)&&`${selectedIds.indexOf(item.id)+1}. `}{item.name}</button>:<Link key={item.id} href={`/destinations/${item.slug}`} className="focus-ring rounded-xl bg-white/5 px-4 py-3 text-sm hover:bg-white/10">{item.name}</Link>)}</div>{!valid.length&&<p className="mt-6 text-sm text-ivory/55">Destination coordinates are unavailable. Add reviewed coordinates in Supabase to enable the route.</p>}</div></section>;
}
