#!/usr/bin/env bash
set -euo pipefail
readonly ISOLATED_REF="xnsxmwgyugoqanuoyebh" PRODUCTION_REF="fstpfqlgypvktjwdeagu" POSTGRES_IMAGE="public.ecr.aws/supabase/postgres:17.6.1.147"
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)";repository_dir="$(cd "${script_dir}/.." && pwd)";environment_file="${repository_dir}/.env.authz.local";migration_file="${repository_dir}/supabase/migrations/202608120007_accounting_integrity.sql";evidence_dir="/tmp/roam-stabilization-phase8"
[[ -f "${environment_file}" && -f "${migration_file}" ]]||{ echo "BLOCKED: isolated environment or Phase 8 migration is missing.";exit 2;}
set -a
# shellcheck disable=SC1090
source "${environment_file}"
set +a
: "${AUTHZ_TEST_PROJECT_REF:?Missing isolated project ref}";: "${AUTHZ_TEST_SUPABASE_URL:?Missing isolated project URL}";: "${AUTHZ_TEST_SUPABASE_PUBLISHABLE_KEY:?Missing isolated publishable key}";: "${AUTHZ_TEST_SUPABASE_SERVICE_ROLE_KEY:?Missing isolated service key}";: "${AUTHZ_TEST_DB_URL:?Missing isolated database URL}";: "${AUTHZ_TEST_ISOLATED_PROJECT:?Missing isolated confirmation}"
if [[ "${AUTHZ_TEST_PROJECT_REF}" != "${ISOLATED_REF}" || "${AUTHZ_TEST_SUPABASE_URL}" != "https://${ISOLATED_REF}.supabase.co" || "${AUTHZ_TEST_ISOLATED_PROJECT}" != "true" || "${AUTHZ_TEST_DB_URL}" != *"${ISOLATED_REF}"* || "${AUTHZ_TEST_PROJECT_REF}" == "${PRODUCTION_REF}" || "${AUTHZ_TEST_SUPABASE_URL}" == *"${PRODUCTION_REF}"* || "${AUTHZ_TEST_DB_URL}" == *"${PRODUCTION_REF}"* ]];then echo "BLOCKED: isolated-project safety gate failed.";exit 2;fi
for role in JOURNEY_DESIGNER PARTNER_MANAGER FINANCE OPERATIONS CONTENT_MARKETING SUPER_ADMIN;do e="AUTHZ_TEST_${role}_EMAIL";p="AUTHZ_TEST_${role}_PASSWORD";[[ "${!e:-}" == *@roamceylon.test && -n "${!p:-}" ]]||{ echo "BLOCKED: a disposable synthetic identity is missing.";exit 2;};done
docker info >/dev/null 2>&1||{ echo "BLOCKED: Docker Desktop is not available.";exit 2;};mkdir -p "${evidence_dir}";chmod 700 "${evidence_dir}";shasum -a 256 "${migration_file}"|awk '{print $1}' >"${evidence_dir}/migration.sha256";chmod 600 "${evidence_dir}/migration.sha256";cd "${repository_dir}"
psql_cmd(){ docker run --rm "${POSTGRES_IMAGE}" psql "${AUTHZ_TEST_DB_URL}" -X --set ON_ERROR_STOP=1 "$@"; }
cleanup(){ psql_cmd -q -c "select set_config('roam.phase8_cleanup','on',false);select set_config('roam.financial_command','on',false);delete from public.accounting_attachments where account_id in(select id from public.journey_accounts where traveller_email like 'phase8-%@roamceylon.test');delete from public.accounting_lifecycle_history where account_id in(select id from public.journey_accounts where traveller_email like 'phase8-%@roamceylon.test');delete from public.accounting_transactions where account_id in(select id from public.journey_accounts where traveller_email like 'phase8-%@roamceylon.test');delete from public.journey_settlements where account_id in(select id from public.journey_accounts where traveller_email like 'phase8-%@roamceylon.test');delete from public.journey_accounts where traveller_email like 'phase8-%@roamceylon.test';delete from public.journey_proposal_acceptances where proposal_id in(select id from public.journey_proposals where proposal_reference like 'RCJ-PHASE8-%');delete from public.journey_proposals where proposal_reference like 'RCJ-PHASE8-%';delete from public.enquiries where email like 'phase8-%@roamceylon.test';" >/dev/null 2>&1||true; }
trap cleanup EXIT
echo "Safety gate passed: isolated project only; production rejected."
marker="$(psql_cmd -Atc "select (to_regprocedure('public.initialize_journey_account_command(uuid,uuid,numeric,date,text,text,text)') is not null)::int+(to_regprocedure('public.record_accounting_transaction_command(uuid,uuid,text,numeric,numeric,date,text,text,text,text,uuid,text,uuid,jsonb)') is not null)::int+(to_regprocedure('public.create_manual_settlement_command(uuid,uuid,text,text,numeric,date,text,text)') is not null)::int+(to_regprocedure('public.reverse_supplier_settlement_command(uuid,uuid,uuid,numeric,numeric,date,text,text)') is not null)::int+(to_regprocedure('public.close_journey_account_command(uuid,uuid,text,boolean)') is not null)::int+(exists(select 1 from pg_trigger where tgname='accounting_transactions_immutable' and not tgisinternal))::int+(exists(select 1 from pg_trigger where tgname='journey_accounts_guard_financial_basis' and not tgisinternal))::int+(exists(select 1 from pg_trigger where tgname='journey_settlements_guard_financial_basis' and not tgisinternal))::int;"|tr -d '[:space:]')"
if [[ "${marker}" == "8" ]];then echo "Phase 8 migration already detected; preserving isolated state and skipping migration application.";elif [[ "${marker}" == "0" ]];then docker run --rm -v "${migration_file}:/phase8.sql:ro" "${POSTGRES_IMAGE}" psql "${AUTHZ_TEST_DB_URL}" -X --set ON_ERROR_STOP=1 --single-transaction -f /phase8.sql >"${evidence_dir}/migration.log" 2>&1||{ echo "BLOCKED: Phase 8 migration failed; private diagnostics retained.";exit 2;};chmod 600 "${evidence_dir}/migration.log";else echo "BLOCKED: partial Phase 8 database state detected; migration was not reapplied.";exit 2;fi
psql_cmd -Atc "do \$verify\$ begin if to_regprocedure('public.accept_journey_proposal_command(uuid,text,text,jsonb)') is null then raise exception 'Phase 7 command regression';end if;if has_table_privilege('authenticated','public.accounting_transactions','INSERT') or has_table_privilege('authenticated','public.journey_accounts','UPDATE') then raise exception 'direct financial DML remains granted';end if;if (select count(*) from pg_views where schemaname='public' and viewname in('public_accommodations','website_public_settings'))<>2 then raise exception 'Phase 2 regression';end if;if (select count(*) from pg_views where schemaname='public' and viewname in('traveller_finance_reference','traveller_admin_full'))<>2 then raise exception 'Phase 5 regression';end if;end \$verify\$;" >/dev/null
echo "Phase 2-7 structural authorization and workflow gates passed."
node --env-file="${environment_file}" tests/phase8-accounting-integrity.mjs|tee "${evidence_dir}/accounting-matrix.json";chmod 600 "${evidence_dir}/accounting-matrix.json"
cleanup;trap - EXIT
echo "Synthetic financial cleanup passed."
echo "PHASE 8 ACCOUNTING INTEGRITY VERIFIED: isolated project only."
