import Link from "next/link";
import {Building2,CarFront,Check,ShieldCheck,UserRoundCheck} from "lucide-react";
import {Button} from "@/components/ui/button";

const categories=[
  {type:"accommodation",Icon:Building2,title:"List your property",copy:"Place your property inside destination-led journeys designed around how travellers want to experience Sri Lanka.",benefits:["Reach travellers planning destination-based journeys","Present rooms, facilities and authentic local character","Receive qualified enquiries reviewed by Roam Ceylon"]},
  {type:"vehicle",Icon:CarFront,title:"Register your vehicle or fleet",copy:"Support complete private journeys with dependable, comfortable transport matched to real trip requirements.",benefits:["Join complete private itineraries across Sri Lanka","Register one vehicle or an entire fleet","Receive relevant transport enquiries"]},
  {type:"guide",Icon:UserRoundCheck,title:"Join our guide network",copy:"Bring local knowledge, languages and specialist expertise to travellers seeking meaningful human guidance.",benefits:["Share your local and specialist expertise","Join journeys matching your destinations","Work with travellers seeking trusted guidance"]}
] as const;
const steps=[["01","Submit your details","Tell us about your property, transport service or guide expertise."],["02","We review your application","Our team checks relevance, quality, media and supporting information."],["03","We prepare your listing","Approved information is organised into a polished marketplace listing."],["04","Join suitable journeys","Published services may appear where they are relevant to a traveller’s journey."]];
const benefits=[["Qualified journey enquiries","Connect with travellers who have already chosen destinations and interests."],["Curated marketplace presence","Present your service within a trusted, quality-reviewed Sri Lankan network."],["Human-supported onboarding","Our team prepares listings instead of leaving partners with complex configuration."],["Relevant matching","Appear where your service fits selected destinations, experiences and itineraries."],["Long-term partnership","Build visibility through future enquiries and destination-led promotions."]];
const faqs=[["Is there a fee to apply?","No application fee is currently displayed. Any future commercial terms will be communicated clearly before you agree."],["Does applying guarantee approval?","No. Every application is reviewed for quality, relevance, accuracy and service standards."],["Can I register several properties or vehicles?","Yes. A fleet can be included in one application. Separate properties should be submitted separately so each can be reviewed properly."],["Can individual guides apply?","Yes. Licensed and specialist independent guides are welcome to apply."],["When does my listing become public?","Only after review, preparation and a separate manual publishing decision by Roam Ceylon."],["Who sets the final package price?","Roam Ceylon prepares the final traveller package price using confirmed partner rates and complete journey costs."]];

export default function Page(){
  return <><section className="bg-sand-light py-24 md:py-36"><div className="shell"><p className="eyebrow mb-5">Partner with Roam Ceylon</p><h1 className="display max-w-5xl">Bring your place, service or local expertise into unforgettable journeys.</h1><p className="prose-luxury mt-7 max-w-3xl">Join a carefully curated network of Sri Lankan accommodation providers, transport operators and local guides. Submit your details for review, and our team will work with you to prepare your listing for travellers.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild variant="accent" size="lg"><Link href="/partners/apply">Apply to become a partner</Link></Button><Button asChild variant="outline" size="lg"><Link href="#how-it-works">See how it works</Link></Button></div></div></section>
  <section className="section"><div className="shell"><p className="eyebrow mb-4">Choose your path</p><h2 className="heading max-w-3xl">A marketplace built around complete journeys.</h2><div className="mt-12 grid gap-6 lg:grid-cols-3">{categories.map(({type,Icon,title,copy,benefits})=><article key={type} className="group flex rounded-3xl border border-stone/20 bg-white p-8 transition hover:-translate-y-1 hover:border-gold/50 focus-within:ring-2 focus-within:ring-gold"><div className="flex flex-1 flex-col"><Icon className="mb-7 size-8 text-gold"/><h3 className="font-serif text-3xl">{title}</h3><p className="mt-4 text-sm leading-7 text-slate/60">{copy}</p><ul className="mt-6 grid gap-3 text-sm">{benefits.map(item=><li key={item} className="flex gap-3"><Check className="mt-0.5 size-4 shrink-0 text-gold"/>{item}</li>)}</ul><Button asChild variant="outline" className="mt-8 self-start"><Link href={{pathname:"/partners/apply",query:{type}}}>Apply as {type==="guide"?"a guide":type==="vehicle"?"a transport partner":"an accommodation partner"}</Link></Button></div></article>)}</div></div></section>
  <section id="how-it-works" className="section bg-forest text-ivory"><div className="shell"><p className="eyebrow mb-4 text-gold-light">How it works</p><h2 className="heading max-w-3xl">Reviewed by people, prepared with care.</h2><div className="mt-12 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{steps.map(([number,title,copy])=><article key={number} className="rounded-3xl border border-white/10 p-6"><span className="font-serif text-3xl text-gold-light">{number}</span><h3 className="mt-5 font-serif text-2xl">{title}</h3><p className="mt-3 text-sm leading-6 text-white/60">{copy}</p></article>)}</div></div></section>
  <section className="section"><div className="shell grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow mb-4">Why partner with us?</p><h2 className="heading">Thoughtful growth, not an open directory.</h2></div><div className="grid gap-4 sm:grid-cols-2">{benefits.map(([title,copy])=><article key={title} className="rounded-2xl border border-stone/15 bg-white p-6"><h3 className="font-serif text-xl">{title}</h3><p className="mt-3 text-sm leading-6 text-slate/60">{copy}</p></article>)}</div></div></section>
  <section className="section bg-sand-light"><div className="shell grid gap-12 lg:grid-cols-2"><div className="rounded-3xl bg-white p-8 md:p-10"><ShieldCheck className="size-9 text-gold"/><h2 className="mt-6 font-serif text-4xl">Quality comes before publication.</h2><p className="mt-5 leading-8 text-slate/65">Roam Ceylon is a curated marketplace. Every application is reviewed before a listing is created. We focus on accurate information, dependable service, clear communication and authentic Sri Lankan travel experiences.</p></div><div><p className="eyebrow mb-4">Partner requirements</p><ul className="grid gap-4 text-sm leading-6">{["Accurate business or professional information","Clear, current photos that represent the service honestly","Dependable communication and confirmed contact details","Relevant licences, registration or verification documents where applicable","Agreement that submission does not guarantee publication"].map(item=><li key={item} className="flex gap-3 rounded-2xl bg-white p-4"><Check className="mt-0.5 size-4 shrink-0 text-gold"/>{item}</li>)}</ul></div></div></section>
  <section className="section"><div className="shell max-w-4xl"><p className="eyebrow mb-4">Frequently asked questions</p><h2 className="heading">Before you apply.</h2><div className="mt-10 divide-y divide-stone/20 border-y border-stone/20">{faqs.map(([question,answer])=><details key={question} className="group py-5"><summary className="cursor-pointer list-none font-semibold">{question}<span className="float-right text-gold group-open:rotate-45">+</span></summary><p className="mt-4 max-w-3xl text-sm leading-7 text-slate/60">{answer}</p></details>)}</div></div></section>
  <section className="pb-24 md:pb-36"><div className="shell"><div className="rounded-[2.5rem] bg-forest p-10 text-ivory md:p-16"><p className="eyebrow mb-4 text-gold-light">Join the network</p><h2 className="heading max-w-3xl">Ready to bring your service into better journeys?</h2><p className="mt-5 max-w-2xl text-white/60">Tell us what makes your property, transport service or expertise distinctive. Our team will guide the next step.</p><Button asChild variant="accent" size="lg" className="mt-8"><Link href="/partners/apply">Apply to become a partner</Link></Button></div></div></section></>;
}
