"use client";

import Image from "next/image";
import {AnimatePresence,motion} from "motion/react";
import {BedDouble,Check,ChevronRight,Download,MapPin,MoonStar,NotebookPen,Plane,Sparkles,UsersRound} from "lucide-react";
import {useEffect,useMemo,useRef,useState} from "react";
import type {MouseEvent} from "react";
import {Button} from "@/components/ui/button";
import {JourneyChapter,JourneyNavigation,JourneyOpening,JourneyProgress,type JourneyChapterDefinition} from "@/components/journey/journey-builder-primitives";
import {UnescoBadge} from "@/components/destinations/unesco-badge";
import {SriLankaMap} from "@/components/map/sri-lanka-map";
import {ExperienceDiscovery} from "@/features/experiences/experience-editorial";
import {guideLanguageOptions,journeyGuidePreferenceLabel,journeyGuidePreferenceOptions,specialistGuideOptions,specialistGuidePreferenceLabel,stayPreferenceLabel,stayPreferenceOptions} from "@/lib/journey/journey-preferences";
import {completeJourneyLegs,effectiveTravelPreference,recommendedTravelPreferences,travelPreferenceLabel,travelPreferenceOptions} from "@/lib/journey/travel-preferences";
import {endpointComplete,endpointLabel,endpointRouteLocation,sriLankaAirports,type JourneyEndpoint} from "@/lib/journey/journey-endpoints";
import {arrivalDateIssue,departureDateIssue,minimumArrivalDate} from "@/lib/journey/journey-dates";
import type {JourneyBootstrap} from "@/lib/journey/journey-service";
import {availableDestinations,availableExperiences} from "@/lib/journey/journey-selectors";
import {exportJourneyPdf} from "@/lib/journey/export-journey-pdf";
import {getRouteEstimate} from "@/lib/journey/route";
import {evaluateJourneyInsights} from "@/lib/journey/journey-insights";
import {useJourneyEstimate} from "@/lib/pricing/use-journey-estimate";
import type {JourneyPricingPlan,ParticipantCounts} from "@/lib/types";
import {cn} from "@/lib/utils";
import {brand,editionDisplayName} from "@/lib/brand";
import {useDialogFocusReturn} from "@/lib/ui/use-dialog-focus-return";
import {emptyJourneyState,JourneyProvider,pricingPlanKey,useJourney,type JourneyInitialSelection,type JourneyState} from "./journey-store";
import {JourneyInsightsPanel} from "./journey-insights-panel";
import {QuotationModal} from "./quotation-modal";

const steps=["Edition","Destination","Experience","Journey Preferences","Journey Details","Journey Insights","Review"] as const;
const chapters:JourneyChapterDefinition[]=[
  {label:"Editions",phase:"Inspire"},
  {label:"Places",phase:"Choose"},
  {label:"Moments",phase:"Choose"},
  {label:"Preferences",phase:"Shape"},
  {label:"Details",phase:"Refine"},
  {label:"Insights",phase:"Refine"},
  {label:"Your Edition",phase:"Share"}
];
const stepTitles=["What kind of journey draws you in?","Where would you like to wake up?","Choose the moments that matter.","Shape each place around you.","Add the practical details.","A thoughtful second look.","Review the journey taking shape."] as const;
const stepIntros=[
  "Choose one or more Editions as the creative starting point for your private journey.",
  "Explore the island through places connected to your Editions, then keep the ones that call to you.",
  "Discover factual, place-specific experiences and choose the moments that belong in your journey.",
  "Set the character of each stay and the kind of guidance that would make the journey feel right.",
  "Add the essential timing, traveller and transport details needed to shape a coherent route.",
  "Consider a few calm observations about pace and flow. They are guidance, never judgement.",
  "See every choice together as one journey portrait. You can return to any completed chapter before sharing it."
] as const;
const budgetPreferenceOptions=[["flexible","Open to guidance"],["value_conscious","Value-conscious"],["balanced","Balanced comfort"],["premium","Premium comfort"]] as const;
const travelPaceOptions=[["relaxed","Relaxed"],["balanced","Balanced"],["fast_paced","Fast-paced"]] as const;
const journeyDetailsIssue=(state:JourneyState)=>{
  if(!endpointComplete(state.pickup))return "Complete the journey pickup point, date and time to continue.";
  if(!endpointComplete(state.dropoff))return "Complete the journey drop-off point, date and time to continue.";
  const arrivalIssue=arrivalDateIssue(state.pickup.date);
  if(arrivalIssue)return arrivalIssue;
  const departureIssue=departureDateIssue(state.pickup.date,state.dropoff.date);
  if(departureIssue)return departureIssue;
  return state.travellerCounts.adults<1?"Add at least one adult traveller to continue.":"";
};
type Card={id:string;name:string;hero_image_url:string|null;short_description:string|null;category?:string|null;unesco_information?:string|null};

function ChoiceCard({item,selected,onClick,index,kind}:{item:Card;selected:boolean;onClick:()=>void;index:number;kind:"edition"|"destination"}){
  const feature=kind==="edition"&&(index===0||index===5);
  return <button type="button" aria-pressed={selected} onClick={onClick} className={cn("group relative min-h-[23rem] overflow-hidden border text-left transition duration-300 focus-ring md:min-h-[26rem]",feature?"md:col-span-2 xl:col-span-7":"xl:col-span-5",selected?"border-gold shadow-[0_22px_65px_rgba(11,48,42,.18)]":"border-forest/15 hover:border-gold")}>
    {item.hero_image_url?<Image src={item.hero_image_url} alt={item.name} fill sizes={feature?"(max-width: 768px) 100vw, 58vw":"(max-width: 768px) 100vw, 42vw"} className="object-cover transition duration-1000 ease-out group-hover:scale-[1.025]"/>:null}
    <div className="absolute inset-0 bg-gradient-to-t from-forest via-forest/25 to-transparent"/>
    <span className={cn("absolute right-5 top-5 z-10 flex min-h-10 items-center gap-2 rounded-full border px-3 text-[.65rem] font-bold uppercase tracking-[.12em] backdrop-blur",selected?"border-gold bg-gold text-forest":"border-white/55 bg-forest/25 text-white")}><span className="grid size-4 place-items-center">{selected?<Check className="size-4"/>:null}</span>{selected?"Selected":"Select"}</span>
    {item.unesco_information?<UnescoBadge className="absolute left-5 top-5"/>:null}
    <div className="absolute inset-x-0 bottom-0 p-6 text-ivory md:p-8">{item.category?<p className="text-[.65rem] font-bold uppercase tracking-[.2em] text-gold-light">{item.category}</p>:null}<h2 className={cn("mt-3 max-w-2xl font-serif leading-[1.06]",feature?"text-4xl md:text-5xl":"text-3xl")}>{item.name}</h2><p className="mt-4 max-w-xl line-clamp-2 text-sm leading-6 text-ivory/72">{item.short_description}</p></div>
  </button>;
}

function JourneyPreferencesStep({data}:{data:JourneyBootstrap}){
  const {state,dispatch}=useJourney();
  const selectedDestinations=state.selectedDestinationIds.map(id=>data.destinations.find(item=>item.id===id)).filter((item):item is JourneyBootstrap["destinations"][number]=>Boolean(item));
  if(!selectedDestinations.length)return <Empty text="Choose at least one destination before adding journey preferences."/>;
  return <div className="mt-10 grid gap-6">
    <article className="relative overflow-hidden rounded-[2rem] border border-gold/25 bg-white p-6 shadow-[0_22px_65px_rgba(27,48,43,.10)] md:p-8"><div className="absolute inset-y-0 left-0 w-1.5 bg-gold"/><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="eyebrow">Across your whole journey</p><h2 className="mt-2 font-serif text-3xl text-slate">Your primary guide.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-stone">Choose one guiding style for the island journey. Destination specialists can still be added independently below.</p></div><span className="grid size-12 place-items-center rounded-full border border-gold/25 bg-gold/10 text-gold"><UsersRound className="size-5"/></span></div><div className="mt-7 grid gap-5 rounded-2xl bg-sand-light/70 p-5 md:grid-cols-2"><label className="grid gap-2 text-sm font-semibold text-slate"><span className="flex items-center gap-2"><UsersRound className="size-4 text-gold"/>Primary guide preference</span><select value={state.journeyGuidePreference} onChange={event=>dispatch({type:"journeyGuidePreference",value:event.target.value as typeof journeyGuidePreferenceOptions[number][0]})} className="rounded-xl border border-stone/20 bg-white px-4 py-3 text-slate outline-none focus:border-gold">{journeyGuidePreferenceOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{state.journeyGuidePreference!=="no_guide"?<div className="md:col-span-2"><p className="mb-3 text-sm font-semibold text-slate">Preferred languages <span className="font-normal text-stone">(choose all that apply)</span></p><div className="flex flex-wrap gap-2">{guideLanguageOptions.map(language=><button type="button" key={language} onClick={()=>dispatch({type:"journeyGuideLanguage",value:language})} className={cn("rounded-full border px-3 py-2 text-xs font-semibold transition",state.journeyGuideLanguages.includes(language)?"border-gold bg-gold text-forest shadow-sm":"border-stone/20 bg-white text-slate hover:border-gold")}>{state.journeyGuideLanguages.includes(language)?<Check className="mr-1 inline size-3"/>:null}{language}</button>)}</div></div>:null}<label className="grid gap-2 text-sm font-semibold text-slate md:col-span-2">Guide notes <span className="font-normal text-stone">(optional)</span><textarea rows={3} value={state.journeyGuideNotes} onChange={event=>dispatch({type:"journeyGuideNotes",value:event.target.value})} placeholder="Language nuance, guiding style, interests or any personal considerations…" className="rounded-xl border border-stone/20 bg-white px-4 py-3 leading-6 text-slate outline-none focus:border-gold"/></label></div></article>
    {selectedDestinations.map((destination,index)=>{
      const preference=state.destinationPreferences[destination.id];
      const specialistOptions=specialistGuideOptions(destination.name);
      const experiences=state.selectedExperienceIds.map(id=>data.experiences.find(item=>item.id===id)).filter((item):item is JourneyBootstrap["experiences"][number]=>item!==undefined&&item.destinationIds.includes(destination.id));
      return <article key={destination.id} className="border-t border-gold/35 pt-6 md:pt-8">
        <div className="flex flex-wrap items-end justify-between gap-3">
          <div><p className="eyebrow">Destination {String(index+1).padStart(2,"0")} · {destination.province||"Sri Lanka"}</p><h2 className="mt-2 font-serif text-4xl text-slate md:text-5xl">{destination.name}</h2></div>
          <span className="text-xs font-semibold text-stone">Shape this stay</span>
        </div>
        <div className="relative mt-6 aspect-[16/9] overflow-hidden bg-sand md:aspect-[16/7]">{destination.hero_image_url&&<Image src={destination.hero_image_url} alt={destination.image_alt||destination.name} fill quality={88} sizes="(max-width: 768px) 100vw, (max-width: 1280px) 92vw, 68vw" className="object-cover object-center"/>}<div className="absolute inset-0 bg-gradient-to-t from-slate/35 via-transparent to-transparent"/></div>
        <div className="bg-sand-light/75 p-5 md:p-7">
            <div className="border-b border-stone/15 pb-5"><p className="mb-3 text-[.65rem] font-bold uppercase tracking-[.18em] text-gold">Selected experiences</p><div className="flex flex-wrap gap-2">{experiences.length?experiences.map(experience=>{const counts=state.experienceParticipants[experience.id];const total=counts?counts.adults+counts.children+counts.infants:0;return <span key={experience.id} className="border border-gold/20 bg-ivory px-3 py-2 text-xs text-slate/75">{experience.name}{total?` · ${total} guest${total===1?"":"s"}`:""}</span>}):<span className="text-sm text-stone">No experiences selected for this destination.</span>}</div></div>
            <div className="mt-5 grid gap-5 md:grid-cols-2">
              <label className="grid gap-2 text-sm font-semibold"><span className="flex items-center gap-2"><BedDouble className="size-4 text-gold"/>Stay preference</span><select aria-label={`Stay preference for ${destination.name}`} value={preference?.stayPreference||"recommend"} onChange={event=>dispatch({type:"stayPreference",destinationId:destination.id,value:event.target.value as typeof stayPreferenceOptions[number][0]})} className="rounded-xl border border-stone/25 bg-ivory px-4 py-3 outline-none focus:border-gold">{stayPreferenceOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
              {specialistOptions.length>1?<label className="grid gap-2 text-sm font-semibold"><span className="flex items-center gap-2"><UsersRound className="size-4 text-gold"/>Optional local specialist</span><select aria-label={`Specialist guide preference for ${destination.name}`} value={preference?.specialistGuidePreference||"none"} onChange={event=>dispatch({type:"specialistGuidePreference",destinationId:destination.id,value:event.target.value})} className="rounded-xl border border-stone/25 bg-ivory px-4 py-3 outline-none focus:border-gold">{specialistOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>:<div className="rounded-xl bg-sand-light px-4 py-3 text-sm text-stone"><strong className="block text-slate">Local specialist</strong>No specialist category is currently offered for this stop.</div>}
              <label className="grid gap-2 text-sm font-semibold md:col-span-2"><span className="flex items-center gap-2"><MoonStar className="size-4 text-gold"/>Planned nights <span className="font-normal text-stone">(optional)</span></span><input aria-label={`Planned nights in ${destination.name}`} type="number" min="0" max="60" value={preference?.nights??""} onChange={event=>dispatch({type:"destinationNights",destinationId:destination.id,value:event.target.value===""?null:Number(event.target.value)})} placeholder="Leave open if you would like us to suggest the pace" className="rounded-xl border border-stone/25 bg-ivory px-4 py-3 outline-none focus:border-gold"/></label>
              <label className="grid gap-2 text-sm font-semibold md:col-span-2"><span className="flex items-center gap-2"><NotebookPen className="size-4 text-gold"/>Notes for {destination.name} <span className="font-normal text-stone">(optional)</span></span><textarea aria-label={`Notes for ${destination.name}`} rows={3} value={preference?.notes||""} onChange={event=>dispatch({type:"destinationNotes",destinationId:destination.id,value:event.target.value})} placeholder="Room style, pace, accessibility, celebrations or anything your journey designer should consider…" className="rounded-xl border border-stone/25 bg-ivory px-4 py-3 leading-6 outline-none focus:border-gold"/></label>
            </div>
          </div>
      </article>;
    })}
  </div>;
}

function EndpointEditor({kind,value,onChange,destinations}:{kind:"pickup"|"dropoff";value:JourneyEndpoint;onChange:(value:Partial<JourneyEndpoint>)=>void;destinations:JourneyBootstrap["destinations"]}){
  const pickup=kind==="pickup",airport=value.type==="airport";
  const dateInputRef=useRef<HTMLInputElement>(null);
  useEffect(()=>{if(dateInputRef.current&&pickup)dateInputRef.current.min=minimumArrivalDate()},[pickup]);
  return <article className="rounded-[2rem] border border-stone/15 bg-white p-6 shadow-[0_14px_40px_rgba(27,48,43,.06)]">
    <div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-gold/10 text-gold">{airport?<Plane className="size-5"/>:<MapPin className="size-5"/>}</span><div><p className="eyebrow">{pickup?"Journey start":"Journey end"}</p><h3 className="font-serif text-2xl">{pickup?"Arrival / pickup":"Departure / drop-off"}</h3></div></div>
    <div className="mt-6 grid gap-4 md:grid-cols-2">
      <label className="grid gap-2 text-sm font-semibold">{pickup?"Pickup":"Drop-off"} type <span className="text-gold">Required</span><select value={value.type??""} onChange={event=>onChange({type:(event.target.value||null) as JourneyEndpoint["type"],airportCode:"",location:"",flightNumber:""})} className="rounded-xl border border-stone/25 bg-ivory px-4 py-3"><option value="">Choose one</option><option value="airport">Airport {pickup?"arrival":"departure"}</option><option value="other">Other {pickup?"pickup":"drop-off"} location</option></select></label>
      {airport?<label className="grid gap-2 text-sm font-semibold">Airport <span className="text-gold">Required</span><select value={value.airportCode} onChange={event=>onChange({airportCode:event.target.value})} className="rounded-xl border border-stone/25 bg-ivory px-4 py-3"><option value="">Choose airport</option>{sriLankaAirports.map(item=><option key={item.code} value={item.code}>{item.code} · {item.name}</option>)}</select></label>:value.type==="other"?<label className="grid gap-2 text-sm font-semibold">{pickup?"Pickup":"Drop-off"} location <span className="text-gold">Required</span><input list={`${kind}-locations`} value={value.location} onChange={event=>onChange({location:event.target.value})} placeholder="Hotel, address or meeting point" className="rounded-xl border border-stone/25 bg-ivory px-4 py-3"/><datalist id={`${kind}-locations`}>{destinations.map(item=><option key={item.id} value={item.name}/>)}</datalist></label>:null}
      <label className="grid gap-2 text-sm font-semibold">Date <span className="text-gold">Required</span><input ref={dateInputRef} required type="date" value={value.date} onChange={event=>onChange({date:event.target.value})} className="rounded-xl border border-stone/25 bg-ivory px-4 py-3"/>{pickup?<small className="font-normal text-stone">Choose a date at least 14 days from today.</small>:null}</label>
      <label className="grid gap-2 text-sm font-semibold">Time <span className="text-gold">Required</span><input required type="time" value={value.time} onChange={event=>onChange({time:event.target.value})} className="rounded-xl border border-stone/25 bg-ivory px-4 py-3"/></label>
      {airport?<label className="grid gap-2 text-sm font-semibold md:col-span-2">Flight number <span className="font-normal text-stone">(optional)</span><input value={value.flightNumber} onChange={event=>onChange({flightNumber:event.target.value})} placeholder={pickup?"Arrival flight":"Departure flight"} className="rounded-xl border border-stone/25 bg-ivory px-4 py-3"/></label>:null}
    </div>
  </article>;
}

function JourneyDetailsStep({data,validationMessage}:{data:JourneyBootstrap;validationMessage:string}){
  const {state,dispatch}=useJourney();
  const minimumTravellers=Object.values(state.experienceParticipants).reduce((maximum,counts)=>({adults:Math.max(maximum.adults,counts.adults),children:Math.max(maximum.children,counts.children),infants:Math.max(maximum.infants,counts.infants)}),{adults:0,children:0,infants:0});
  const setTraveller=(key:keyof ParticipantCounts,value:number)=>dispatch({type:"travellers",counts:{...state.travellerCounts,[key]:value}});
  const travellers=state.travellerCounts.adults+state.travellerCounts.children+state.travellerCounts.infants;
  const suggestions=recommendedTravelPreferences(travellers).map(travelPreferenceLabel);
  const legs=completeJourneyLegs(state.selectedDestinationIds,Boolean(state.pickup.type),Boolean(state.dropoff.type));
  const locationName=(key:string)=>key==="pickup"?endpointLabel(state.pickup,"pickup"):key==="dropoff"?endpointLabel(state.dropoff,"dropoff"):data.destinations.find(item=>`destination:${item.id}`===key)?.name||"Journey stop";
  return <div className="mt-10">
    <div className="grid gap-5"><EndpointEditor kind="pickup" value={state.pickup} destinations={data.destinations} onChange={value=>dispatch({type:"pickup",value})}/><EndpointEditor kind="dropoff" value={state.dropoff} destinations={data.destinations} onChange={value=>dispatch({type:"dropoff",value})}/></div><div className="mt-5 grid gap-4 rounded-2xl bg-sand-light p-5 md:grid-cols-2">{(["adults","children","infants"] as const).map(key=><label key={key} className="grid gap-2 text-sm font-semibold">{key[0].toUpperCase()+key.slice(1)} <span className="text-gold">Required</span><input required type="number" min={key==="adults"?Math.max(1,minimumTravellers[key]):minimumTravellers[key]} value={state.travellerCounts[key]} onChange={event=>setTraveller(key,Number(event.target.value))} className="rounded-xl border border-stone/30 bg-white px-4 py-3"/>{minimumTravellers[key]>0&&<small className="font-normal text-stone">Minimum {minimumTravellers[key]} — already joining selected experiences.</small>}</label>)}<label className="grid gap-2 text-sm font-semibold">Preferred pace<select value={state.travelPace} onChange={event=>dispatch({type:"pace",value:event.target.value as JourneyState["travelPace"]})} className="rounded-xl border border-stone/30 bg-white px-4 py-3">{travelPaceOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold">Journey budget style<select value={state.budgetPreference} onChange={event=>dispatch({type:"budget",value:event.target.value})} className="rounded-xl border border-stone/30 bg-white px-4 py-3">{budgetPreferenceOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold md:col-span-2">Accessibility or mobility considerations <span className="font-normal text-stone">(optional)</span><textarea rows={3} value={state.accessibilityRequirements} onChange={event=>dispatch({type:"accessibility",value:event.target.value})} placeholder="Share anything that may help us plan access, walking distances or a gentler pace." className="rounded-xl border border-stone/30 bg-white px-4 py-3 leading-6"/></label>{validationMessage?<p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-800 md:col-span-2">{validationMessage}</p>:null}</div>
    <div className="mt-8"><p className="eyebrow">Getting around</p><h2 className="mt-2 font-serif text-3xl">One preference, with room for exceptions.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-stone">Choose the transport style you expect for most of the journey. Change only the legs that should feel different; {brand.name} confirms availability later.</p><label className="mt-5 grid max-w-xl gap-2 text-sm font-semibold">Default journey transport<select value={state.globalTravelPreference} onChange={event=>dispatch({type:"globalTravelPreference",value:event.target.value as typeof travelPreferenceOptions[number][0]})} className="rounded-xl border border-stone/25 bg-white px-4 py-3">{travelPreferenceOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{suggestions.length?<p className="mt-3 text-xs font-semibold text-forest">Well suited to {travellers} traveller{travellers===1?"":"s"}: {suggestions.join(" · ")}</p>:null}</div>
    <div className="mt-5 grid gap-4">{legs.length?legs.map(leg=>{const override=state.travelPreferencesByLeg[leg.key]?.travelPreference;const from=locationName(leg.fromLocationKey),to=locationName(leg.toLocationKey);return <article key={leg.key} className="grid items-center gap-4 rounded-2xl border border-stone/15 bg-white p-5 md:grid-cols-[1fr_auto_1fr_1.2fr]"><div><p className="eyebrow">From</p><strong>{from}</strong></div><ChevronRight className="text-gold"/><div><p className="eyebrow">To</p><strong>{to}</strong></div><label className="grid gap-2 text-xs font-bold uppercase tracking-widest text-stone">Transport preference<select value={override??""} onChange={event=>dispatch({type:"travelPreference",legKey:leg.key,value:event.target.value?event.target.value as typeof travelPreferenceOptions[number][0]:null})} className="rounded-xl border border-stone/25 bg-ivory px-3 py-2.5 text-sm font-normal normal-case tracking-normal"><option value="">Journey default · {travelPreferenceLabel(state.globalTravelPreference)}</option>{travelPreferenceOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></article>}):<Empty text="Complete the pickup, destinations and drop-off to build the full transport route."/>}</div>
    {state.selectedDestinationIds.length>0&&<div className="mt-8"><SriLankaMap destinations={data.destinations} selectedIds={state.selectedDestinationIds} pickup={state.pickup} dropoff={state.dropoff}/></div>}
  </div>;
}

const insightsFor=(state:JourneyState,data:JourneyBootstrap)=>evaluateJourneyInsights({selectedDestinationIds:state.selectedDestinationIds,selectedExperienceIds:state.selectedExperienceIds,destinations:data.destinations,experiences:data.experiences,destinationPreferences:state.destinationPreferences,travelPreferencesByLeg:state.travelPreferencesByLeg,pickup:state.pickup,dropoff:state.dropoff,globalTravelPreference:state.globalTravelPreference,travelDates:state.travelDates,travellerCounts:state.travellerCounts,budgetPreference:state.budgetPreference,travelPace:state.travelPace,accessibilityRequirements:state.accessibilityRequirements});

function JourneyInsightsStep({data,onAction}:{data:JourneyBootstrap;onAction:(step:number)=>void}){const {state}=useJourney();return <JourneyInsightsPanel result={insightsFor(state,data)} onAction={onAction}/>}

function ReviewStep({data,onAction}:{data:JourneyBootstrap;onAction:(step:number)=>void}){
  const {state}=useJourney();
  const legs=completeJourneyLegs(state.selectedDestinationIds,Boolean(state.pickup.type),Boolean(state.dropoff.type));
  const locationName=(key:string)=>key==="pickup"?endpointLabel(state.pickup,"pickup"):key==="dropoff"?endpointLabel(state.dropoff,"dropoff"):data.destinations.find(item=>`destination:${item.id}`===key)?.name||"Journey stop";
  return <div className="mt-10 grid gap-6">
    <article className="rounded-3xl border border-gold/25 bg-sand-light p-6 md:p-8"><p className="eyebrow">Arrival / pickup</p><h2 className="mt-2 font-serif text-3xl">{endpointLabel(state.pickup,"pickup")}</h2><div className="mt-5 grid gap-4 md:grid-cols-3"><ReviewItem label="Date" value={state.pickup.date}/><ReviewItem label="Time" value={state.pickup.time}/>{state.pickup.flightNumber?<ReviewItem label="Flight" value={state.pickup.flightNumber}/>:null}</div></article>
    <article className="rounded-3xl bg-forest p-6 text-ivory md:p-8"><p className="eyebrow text-gold-light">Guide preference</p><div className="mt-5 grid gap-5 md:grid-cols-2"><ReviewItem label="Primary journey guide" value={journeyGuidePreferenceLabel(state.journeyGuidePreference)} dark/><ReviewItem label="Preferred languages" value={state.journeyGuidePreference==="no_guide"?"Not required":state.journeyGuideLanguages.join(", ")||"Open to recommendation"} dark/>{state.journeyGuideNotes?<div className="md:col-span-2"><ReviewItem label="Guide notes" value={state.journeyGuideNotes} dark/></div>:null}</div></article>
    {state.selectedDestinationIds.map((destinationId,index)=>{const destination=data.destinations.find(item=>item.id===destinationId);if(!destination)return null;const preference=state.destinationPreferences[destinationId];const experiences=state.selectedExperienceIds.map(id=>data.experiences.find(item=>item.id===id)).filter((item):item is JourneyBootstrap["experiences"][number]=>item!==undefined&&item.destinationIds.includes(destinationId));return <article key={destinationId} className="rounded-3xl border border-stone/15 bg-white p-6 md:p-8"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Stop {index+1}</p><h2 className="mt-2 font-serif text-3xl">{destination.name}</h2></div><MapPin className="text-gold"/></div><div className="mt-6 grid gap-5 border-t border-stone/15 pt-6 md:grid-cols-2"><ReviewItem label="Stay preference" value={stayPreferenceLabel(preference?.stayPreference||"recommend")}/><ReviewItem label="Local specialist" value={specialistGuidePreferenceLabel(destination.name,preference?.specialistGuidePreference||"none")}/><ReviewItem label="Planned nights" value={preference?.nights===null||preference?.nights===undefined?"Open for your journey designer":`${preference.nights} night${preference.nights===1?"":"s"}`}/><div className="md:col-span-2"><p className="text-[.65rem] font-bold uppercase tracking-widest text-gold">Experiences</p><div className="mt-2 flex flex-wrap gap-2">{experiences.length?experiences.map(item=><span key={item.id} className="rounded-full bg-sand-light px-3 py-2 text-xs">{item.name}</span>):<span className="text-sm text-stone">No experiences selected.</span>}</div></div>{preference?.notes&&<div className="md:col-span-2"><ReviewItem label="Destination notes" value={preference.notes}/></div>}</div></article>})}
    <article className="rounded-3xl bg-forest p-6 text-ivory md:p-8"><p className="eyebrow text-gold-light">Traveller details</p><div className="mt-5 grid gap-5 md:grid-cols-2"><ReviewItem label="Travel dates" value={`${state.pickup.date} to ${state.dropoff.date}`} dark/><ReviewItem label="Travellers" value={`${state.travellerCounts.adults+state.travellerCounts.children+state.travellerCounts.infants}`} dark/><ReviewItem label="Preferred pace" value={travelPaceOptions.find(([value])=>value===state.travelPace)?.[1]||"Balanced"} dark/><ReviewItem label="Budget style" value={budgetPreferenceOptions.find(([value])=>value===state.budgetPreference)?.[1]||"Open to guidance"} dark/>{state.accessibilityRequirements?<div className="md:col-span-2"><ReviewItem label="Accessibility considerations" value={state.accessibilityRequirements} dark/></div>:null}</div><div className="mt-6 border-t border-ivory/10 pt-6"><p className="text-[.65rem] font-bold uppercase tracking-widest text-gold-light">Complete transport route · default {travelPreferenceLabel(state.globalTravelPreference)}</p><div className="mt-3 grid gap-3">{legs.map(leg=><div key={leg.key} className="flex flex-wrap items-center justify-between gap-2 rounded-xl bg-ivory/5 px-4 py-3 text-sm"><span>{locationName(leg.fromLocationKey)} → {locationName(leg.toLocationKey)}</span><strong className="text-gold-light">{travelPreferenceLabel(effectiveTravelPreference(state.travelPreferencesByLeg,leg.key,state.globalTravelPreference))}</strong></div>)}</div></div></article>
    <article className="rounded-3xl border border-gold/25 bg-sand-light p-6 md:p-8"><p className="eyebrow">Departure / drop-off</p><h2 className="mt-2 font-serif text-3xl">{endpointLabel(state.dropoff,"dropoff")}</h2><div className="mt-5 grid gap-4 md:grid-cols-3"><ReviewItem label="Date" value={state.dropoff.date}/><ReviewItem label="Time" value={state.dropoff.time}/>{state.dropoff.flightNumber?<ReviewItem label="Flight" value={state.dropoff.flightNumber}/>:null}</div></article>
    <JourneyInsightsPanel result={insightsFor(state,data)} onAction={onAction} compact/>
  </div>;
}

function ReviewItem({label,value,dark=false}:{label:string;value:string;dark?:boolean}){return <div><p className={cn("text-[.65rem] font-bold uppercase tracking-widest",dark?"text-gold-light":"text-gold")}>{label}</p><p className={cn("mt-2 text-sm leading-6",dark?"text-ivory/75":"text-slate/70")}>{value}</p></div>}

function Builder({data}:{data:JourneyBootstrap}){
  const {state,dispatch}=useJourney();
  const step=state.currentStep;
  const setStep=(value:number)=>dispatch({type:"step",value});
  const [quotationOpen,setQuotationOpen]=useState(false);
  const rememberQuotationOpener=useDialogFocusReturn(quotationOpen);
  const [detailsAttempted,setDetailsAttempted]=useState(false);
  const detailsIssue=journeyDetailsIssue(state);
  const continueJourney=()=>{if(step===4&&detailsIssue){setDetailsAttempted(true);return}setDetailsAttempted(false);setStep(step+1)};
  const openQuotation=(event:MouseEvent<HTMLButtonElement>)=>{if(detailsIssue){setDetailsAttempted(true);setStep(4);return}rememberQuotationOpener(event.currentTarget);setQuotationOpen(true)};
  const destinations=useMemo(()=>availableDestinations(data.destinations,state.selectedThemeIds),[data.destinations,state.selectedThemeIds]);
  const experiences=useMemo(()=>availableExperiences(data.experiences,state.selectedDestinationIds,state.selectedThemeIds),[data.experiences,state.selectedDestinationIds,state.selectedThemeIds]);
  const current=step===0?data.themes.map(theme=>({...theme,name:editionDisplayName(theme)})):destinations;
  const selected=step===0?state.selectedThemeIds:state.selectedDestinationIds;
  const field=step===0?"selectedThemeIds":"selectedDestinationIds";
  const estimateRequest={selectedDestinationIds:state.selectedDestinationIds,selectedExperienceIds:state.selectedExperienceIds,selectedPricingPlanIds:state.selectedPricingPlanIds,destinationPreferences:state.destinationPreferences,journeyGuidePreference:state.journeyGuidePreference,pickup:state.pickup,dropoff:state.dropoff,globalTravelPreference:state.globalTravelPreference,travelPreferencesByLeg:state.travelPreferencesByLeg,travelDates:state.travelDates,travellerCounts:state.travellerCounts,experienceParticipants:state.experienceParticipants};
  const journeyEstimate=useJourneyEstimate(estimateRequest);
  const openingImage=data.themes.find(theme=>theme.hero_image_url)?.hero_image_url??data.destinations.find(destination=>destination.hero_image_url)?.hero_image_url??null;
  return <><AnimatePresence initial={false}>{step===0?<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><JourneyOpening image={openingImage}/></motion.div>:null}</AnimatePresence>
    <JourneyProgress chapters={chapters} current={step} onSelect={setStep}/>
    <main className="journey-builder shell grid gap-10 py-10 md:py-16 xl:grid-cols-[minmax(0,1fr)_minmax(20rem,23rem)] xl:gap-10 2xl:grid-cols-[minmax(0,1fr)_24rem] 2xl:gap-12">
    <AnimatePresence mode="wait"><motion.div key={step} className="min-w-0" initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-12}} transition={{duration:.28}}>
      <JourneyChapter phase={chapters[step].phase} title={stepTitles[step]} intro={stepIntros[step]}>
        {step<2?<><div className={cn("mt-10 grid gap-5 md:grid-cols-2",step===0&&"xl:grid-cols-12")}>{current.map((item,index)=><ChoiceCard key={item.id} item={item} index={index} kind={step===0?"edition":"destination"} selected={selected.includes(item.id)} onClick={()=>dispatch({type:"toggle",field,id:item.id})}/>)}</div>{step===1&&<div className="mt-10 border-t border-forest/15 pt-10"><p className="eyebrow mb-5">Read the island</p><SriLankaMap destinations={destinations} selectedIds={state.selectedDestinationIds} onSelect={id=>dispatch({type:"toggle",field:"selectedDestinationIds",id})}/></div>}</>:null}
        {step===2?<ExperienceDiscovery compact experiences={experiences} globalTravellers={state.travellerCounts} selectedIds={state.selectedExperienceIds} participantsByExperience={state.experienceParticipants} selectedPricingPlanIds={state.selectedPricingPlanIds} onInclude={(experience,participants,travellers,pricingPlanId)=>{dispatch({type:"travellers",counts:travellers});dispatch({type:"includeExperience",experienceId:experience.id,counts:participants,pricingPlanId})}} onRemove={experience=>dispatch({type:"removeExperience",experienceId:experience.id})} onParticipantsChange={(experience,participants,pricingPlanId)=>dispatch({type:"experienceParticipants",experienceId:experience.id,counts:participants,pricingPlanId})}/>:null}
        {step===3?<JourneyPreferencesStep data={data}/>:null}{step===4?<JourneyDetailsStep data={data} validationMessage={detailsAttempted?detailsIssue:""}/>:null}{step===5?<JourneyInsightsStep data={data} onAction={setStep}/>:null}{step===6?<ReviewStep data={data} onAction={setStep}/>:null}
        <JourneyNavigation step={step} total={steps.length} onBack={()=>setStep(step-1)} onContinue={continueJourney} onSubmit={openQuotation} submitDisabled={!state.selectedDestinationIds.length}/>
      </JourneyChapter>
    </motion.div></AnimatePresence>
    <Summary data={data} estimateState={journeyEstimate} onQuotation={openQuotation}/>
  </main><QuotationModal open={quotationOpen} onClose={()=>setQuotationOpen(false)} onSubmitted={()=>dispatch({type:"hydrate",state:emptyJourneyState})} state={state} quote={journeyEstimate.estimate} data={data}/></>;
}

function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-stone/30 p-8 text-sm text-stone">{text}</div>}

function Summary({data,estimateState,onQuotation}:{data:JourneyBootstrap;estimateState:ReturnType<typeof useJourneyEstimate>;onQuotation:(event:MouseEvent<HTMLButtonElement>)=>void}){
  const {state}=useJourney();
  const [exporting,setExporting]=useState(false);
  const selectedPlanName=(item:{id:string;pricingPlans:JourneyPricingPlan[]})=>item.pricingPlans.find(plan=>plan.id===state.selectedPricingPlanIds[pricingPlanKey("experience",item.id)])?.name||item.pricingPlans[0]?.name||null;
  const pickupRoute=state.pickup.type?endpointRouteLocation(state.pickup,"pickup",data.destinations):null;
  const dropoffRoute=state.dropoff.type?endpointRouteLocation(state.dropoff,"dropoff",data.destinations):null;
  const completeRouteDestinations=[...data.destinations,...(pickupRoute?[pickupRoute]:[]),...(dropoffRoute?[dropoffRoute]:[])];
  const completeRouteIds=[...(pickupRoute?[pickupRoute.id]:[]),...state.selectedDestinationIds,...(dropoffRoute?[dropoffRoute.id]:[])];
  const route=getRouteEstimate(completeRouteDestinations,completeRouteIds);
  const {estimate,loading}=estimateState;
  const travellers=state.travellerCounts.adults+state.travellerCounts.children+state.travellerCounts.infants;
  const selectedDestinations=state.selectedDestinationIds.map(id=>data.destinations.find(item=>item.id===id)).filter((item):item is JourneyBootstrap["destinations"][number]=>Boolean(item));
  const legs=completeJourneyLegs(state.selectedDestinationIds,Boolean(state.pickup.type),Boolean(state.dropoff.type));
  const locationName=(key:string)=>key==="pickup"?endpointLabel(state.pickup,"pickup"):key==="dropoff"?endpointLabel(state.dropoff,"dropoff"):data.destinations.find(item=>`destination:${item.id}`===key)?.name||"Journey stop";
  const travelSummary=legs.map(leg=>`${locationName(leg.fromLocationKey)} to ${locationName(leg.toLocationKey)} - ${travelPreferenceLabel(effectiveTravelPreference(state.travelPreferencesByLeg,leg.key,state.globalTravelPreference))}`).join("; ");
  const routeCoordinates=completeRouteIds.flatMap(id=>{const item=completeRouteDestinations.find(destination=>destination.id===id);return item&&Number.isFinite(item.latitude)&&Number.isFinite(item.longitude)?[{name:item.name,latitude:Number(item.latitude),longitude:Number(item.longitude)}]:[]});
  const exportPdf=async()=>{setExporting(true);try{const specialists=selectedDestinations.flatMap(item=>{const label=specialistGuidePreferenceLabel(item.name,state.destinationPreferences[item.id]?.specialistGuidePreference||"none");return label==="None"?[]:[`${item.name}: ${label}`]});await exportJourneyPdf({themes:state.selectedThemeIds.map(id=>data.themes.find(item=>item.id===id)).filter((theme):theme is JourneyBootstrap["themes"][number]=>Boolean(theme)).map(editionDisplayName),destinations:selectedDestinations.map(item=>item.name),routeCoordinates,experiences:state.selectedExperienceIds.map(id=>{const item=data.experiences.find(experience=>experience.id===id);if(!item)return null;const plan=selectedPlanName(item);const counts=state.experienceParticipants[item.id];const participants=counts?counts.adults+counts.children+counts.infants:0;return `${item.name}${participants?` - ${participants} participant${participants===1?"":"s"}`:""}${plan?` - ${plan}`:""}`}).filter((name):name is string=>Boolean(name)),accommodations:selectedDestinations.map(item=>`${item.name} - ${stayPreferenceLabel(state.destinationPreferences[item.id]?.stayPreference||"recommend")}`),vehicle:travelSummary||null,guide:`${journeyGuidePreferenceLabel(state.journeyGuidePreference)}${state.journeyGuideLanguages.length?` (${state.journeyGuideLanguages.join(", ")})`:""}${specialists.length?`; Specialists: ${specialists.join("; ")}`:""}`,travelDates:state.travelDates,travellerCounts:state.travellerCounts,estimatedDistance:route.estimatedDistance,estimatedTravelDays:route.estimatedTravelDays,quote:estimate});}finally{setExporting(false)}};
  const ranged=estimate?.status==="estimated_range";
  const money=(value:number|null)=>value===null?"—":value.toLocaleString("en-US",{maximumFractionDigits:0});
  return <aside aria-label="Your Ceylon Edition journey summary" className="h-fit min-w-0 overflow-hidden border border-gold/30 bg-forest text-ivory shadow-[0_28px_80px_rgba(11,48,42,.16)] xl:sticky xl:top-28">
    <div className="border-b border-ivory/10 bg-ivory/5 p-7"><div className="flex items-center gap-3"><Sparkles className="text-gold-light"/><p className="eyebrow text-gold-light">Your Ceylon Edition</p></div><h2 className="mt-4 font-serif text-3xl leading-tight">The journey taking shape.</h2><p className="mt-3 text-xs leading-5 text-ivory/55">A live portrait of the choices you make in each chapter.</p></div><div className="p-7">
    {[[state.selectedThemeIds,data.themes,"Editions"],[state.selectedDestinationIds,data.destinations,"Destinations"]].map(([ids,items,label])=><div className="border-t border-ivory/10 py-5" key={label as string}><p className="mb-3 text-[.65rem] font-bold uppercase tracking-widest text-gold-light">{label as string}</p><div className="flex flex-wrap gap-2">{(ids as string[]).length?(ids as string[]).map(id=>{const item=(items as Card[]).find(candidate=>candidate.id===id);return <span key={id} className="rounded-full bg-ivory/10 px-3 py-1 text-xs">{label==="Editions"&&item?editionDisplayName(item):item?.name}</span>}):<span className="text-sm text-ivory/40">Nothing selected yet</span>}</div></div>)}
    <div className="border-t border-ivory/10 py-5"><p className="mb-3 text-[.65rem] font-bold uppercase tracking-widest text-gold-light">Experiences</p><div className="flex flex-wrap gap-2">{state.selectedExperienceIds.length?state.selectedExperienceIds.map(id=>{const item=data.experiences.find(experience=>experience.id===id);const counts=state.experienceParticipants[id];const plan=item?selectedPlanName(item):null;return <span key={id} className="rounded-full bg-ivory/10 px-3 py-1 text-xs">{item?.name}{counts?` · ${counts.adults+counts.children+counts.infants}`:""}{plan?` · ${plan}`:""}</span>}):<span className="text-sm text-ivory/40">Nothing selected yet</span>}</div></div>
    <div className="border-t border-ivory/10 py-5"><p className="mb-3 text-[.65rem] font-bold uppercase tracking-widest text-gold-light">Preferences & plan</p><div className="grid gap-3 text-sm text-ivory/70"><div><strong className="text-ivory">Primary guide</strong><span className="mt-1 block text-xs">{journeyGuidePreferenceLabel(state.journeyGuidePreference)}{state.journeyGuideLanguages.length?` · ${state.journeyGuideLanguages.join(", ")}`:""}</span></div>{selectedDestinations.map(item=>{const preference=state.destinationPreferences[item.id];const specialist=specialistGuidePreferenceLabel(item.name,preference?.specialistGuidePreference||"none");return <div key={item.id}><strong className="text-ivory">{item.name}</strong><span className="mt-1 block text-xs">{stayPreferenceLabel(preference?.stayPreference||"recommend")}{specialist!=="None"?` · ${specialist}`:""}</span></div>})}{legs.length?<div className="grid gap-2 border-t border-ivory/10 pt-3">{legs.map(leg=><span key={leg.key} className="text-xs">{locationName(leg.fromLocationKey)} → {locationName(leg.toLocationKey)} · {travelPreferenceLabel(effectiveTravelPreference(state.travelPreferencesByLeg,leg.key,state.globalTravelPreference))}</span>)}</div>:null}{!selectedDestinations.length&&<span className="text-ivory/40">Nothing selected yet</span>}</div></div>
    <div className="border-t border-ivory/10 py-5"><div className="flex justify-between text-sm"><span>{travellers?`${travellers} travellers`:"Travellers not set"}</span><span>{route.estimatedDistance} km</span></div>{loading?<p className="mt-4 text-sm text-ivory/50">Refining your estimate…</p>:ranged?<div className="mt-5 grid gap-3"><p className="text-[.65rem] font-bold uppercase tracking-widest text-gold-light">Your estimated journey</p><div><strong className="block font-serif text-3xl">{estimate.currency} {money(estimate.perPersonMin)} – {money(estimate.perPersonMax)}</strong><span className="text-xs text-ivory/55">per person</span></div><p className="text-xs text-ivory/70">For {travellers} traveller{travellers===1?"":"s"} · {estimate.durationDays} day{estimate.durationDays===1?"":"s"}</p><p className="text-xs text-ivory/50">Based on your current journey preferences.</p><div className="flex justify-between border-t border-ivory/10 pt-3 text-xs text-ivory/65"><span>Estimated journey total</span><span>{estimate.currency} {money(estimate.totalMin)} – {money(estimate.totalMax)}</span></div><p className="text-xs leading-5 text-ivory/55">{estimate.message}</p><details className="border-t border-ivory/10 pt-3 text-xs text-ivory/60"><summary className="cursor-pointer font-semibold text-ivory/80">What affects this estimate?</summary><ul className="mt-3 grid gap-1 pl-4">{estimate.factors.map(factor=><li key={factor} className="list-disc">{factor}</li>)}</ul></details></div>:state.selectedDestinationIds.length?<div className="mt-4 rounded-2xl bg-ivory/5 p-4"><p className="font-serif text-xl text-ivory">Your planning range is taking shape</p><p className="mt-2 text-xs leading-5 text-ivory/55">{estimate?.message??"Complete the journey details shown in the builder so we can present a dependable estimate before you request your proposal."}</p></div>:<p className="mt-4 text-sm text-ivory/40">Select destinations to shape your estimate.</p>}</div>
    <Button onClick={onQuotation} disabled={!state.selectedDestinationIds.length||state.currentStep<steps.length-1} variant="accent" className="mb-3 w-full">{state.currentStep<steps.length-1?"Review journey to continue":"Request Journey Proposal"}</Button>
    <Button onClick={exportPdf} disabled={!state.selectedDestinationIds.length||exporting} variant="outline" className="w-full border-ivory/20 text-ivory hover:bg-ivory/10"><Download/>{exporting?"Preparing PDF...":"Export Journey Summary"}</Button>
    <div className="mt-4 flex items-center gap-2 text-xs text-ivory/55"><MapPin className="size-4"/>Review and revise every choice before requesting your quote.</div>
    </div></aside>;
}

export function JourneyBuilder({data,initialSelection}:{data:JourneyBootstrap;initialSelection?:JourneyInitialSelection}){return <JourneyProvider data={data} initialSelection={initialSelection}><Builder data={data}/></JourneyProvider>}
