"use client";

import Image from "next/image";
import {AnimatePresence,motion} from "motion/react";
import {BedDouble,Check,ChevronLeft,ChevronRight,Download,MapPin,MoonStar,NotebookPen,Plane,Sparkles,UsersRound} from "lucide-react";
import {useMemo,useState} from "react";
import {Button} from "@/components/ui/button";
import {UnescoBadge} from "@/components/destinations/unesco-badge";
import {SriLankaMap} from "@/components/map/sri-lanka-map";
import {ExperienceDiscovery} from "@/features/experiences/experience-editorial";
import {guideLanguageOptions,journeyGuidePreferenceLabel,journeyGuidePreferenceOptions,specialistGuideOptions,specialistGuidePreferenceLabel,stayPreferenceLabel,stayPreferenceOptions} from "@/lib/journey/journey-preferences";
import {completeJourneyLegs,effectiveTravelPreference,recommendedTravelPreferences,travelPreferenceLabel,travelPreferenceOptions} from "@/lib/journey/travel-preferences";
import {endpointComplete,endpointLabel,endpointRouteLocation,sriLankaAirports,type JourneyEndpoint} from "@/lib/journey/journey-endpoints";
import type {JourneyBootstrap} from "@/lib/journey/journey-service";
import {availableDestinations,availableExperiences} from "@/lib/journey/journey-selectors";
import {exportJourneyPdf} from "@/lib/journey/export-journey-pdf";
import {getRouteEstimate} from "@/lib/journey/route";
import {evaluateJourneyInsights} from "@/lib/journey/journey-insights";
import {useJourneyEstimate} from "@/lib/pricing/use-journey-estimate";
import type {JourneyPricingPlan,ParticipantCounts} from "@/lib/types";
import {cn} from "@/lib/utils";
import {emptyJourneyState,JourneyProvider,pricingPlanKey,useJourney,type JourneyInitialSelection,type JourneyState} from "./journey-store";
import {JourneyInsightsPanel} from "./journey-insights-panel";
import {QuotationModal} from "./quotation-modal";

const steps=["Theme","Destination","Experience","Journey Preferences","Journey Details","Journey Insights","Review"] as const;
const stepTitles=["What kind of journey draws you in?","Where would you like to wake up?","Choose the moments that matter.","Shape each place around you.","Add the practical details.","A thoughtful second look.","Review the journey taking shape."] as const;
const budgetPreferenceOptions=[["flexible","Open to guidance"],["value_conscious","Value-conscious"],["balanced","Balanced comfort"],["premium","Premium comfort"]] as const;
const travelPaceOptions=[["relaxed","Relaxed"],["balanced","Balanced"],["fast_paced","Fast-paced"]] as const;
const journeyDetailsIssue=(state:JourneyState)=>!endpointComplete(state.pickup)?"Complete the journey pickup point, date and time to continue.":!endpointComplete(state.dropoff)?"Complete the journey drop-off point, date and time to continue.":state.dropoff.date<state.pickup.date?"Drop-off must be on or after pickup.":state.travellerCounts.adults<1?"Add at least one adult traveller to continue.":"";
type Card={id:string;name:string;hero_image_url:string|null;short_description:string|null;category?:string|null;unesco_information?:string|null};

function ChoiceCard({item,selected,onClick}:{item:Card;selected:boolean;onClick:()=>void}){
  return <button onClick={onClick} className={cn("group overflow-hidden rounded-3xl border bg-white text-left transition",selected?"border-gold ring-2 ring-gold/25":"border-stone/15 hover:-translate-y-1")}>
    <div className="relative aspect-[16/9] bg-sand">{item.hero_image_url&&<Image src={item.hero_image_url} alt={item.name} fill sizes="50vw" className="object-cover transition duration-700 group-hover:scale-105"/>}{item.unesco_information&&<UnescoBadge className="absolute bottom-4 left-4"/>}<span className={cn("absolute right-4 top-4 grid size-8 place-items-center rounded-full border backdrop-blur",selected?"border-gold bg-gold text-white":"border-white/50 bg-slate/30 text-white")}>{selected&&<Check className="size-4"/>}</span></div>
    <div className="p-5">{item.category&&<p className="text-xs font-bold uppercase tracking-widest text-gold">{item.category}</p>}<h2 className="mt-2 font-serif text-2xl">{item.name}</h2><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate/60">{item.short_description}</p></div>
  </button>;
}

function JourneyPreferencesStep({data}:{data:JourneyBootstrap}){
  const {state,dispatch}=useJourney();
  const selectedDestinations=state.selectedDestinationIds.map(id=>data.destinations.find(item=>item.id===id)).filter((item):item is JourneyBootstrap["destinations"][number]=>Boolean(item));
  if(!selectedDestinations.length)return <Empty text="Choose at least one destination before adding journey preferences."/>;
  return <div className="mt-10 grid gap-6">
    <article className="relative overflow-hidden rounded-[2rem] border border-gold/25 bg-white p-6 shadow-[0_22px_65px_rgba(27,48,43,.10)] md:p-8"><div className="absolute inset-y-0 left-0 w-1.5 bg-gold"/><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="eyebrow">Across your whole journey</p><h2 className="mt-2 font-serif text-3xl text-slate">Your primary guide.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-stone">Choose one guiding style for the island journey. Destination specialists can still be added independently below.</p></div><span className="grid size-12 place-items-center rounded-full border border-gold/25 bg-gold/10 text-gold"><UsersRound className="size-5"/></span></div><div className="mt-7 grid gap-5 rounded-2xl bg-sand-light/70 p-5 md:grid-cols-2"><label className="grid gap-2 text-sm font-semibold text-slate"><span className="flex items-center gap-2"><UsersRound className="size-4 text-gold"/>Primary guide preference</span><select value={state.journeyGuidePreference} onChange={event=>dispatch({type:"journeyGuidePreference",value:event.target.value as typeof journeyGuidePreferenceOptions[number][0]})} className="rounded-xl border border-stone/20 bg-white px-4 py-3 text-slate outline-none focus:border-gold">{journeyGuidePreferenceOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{state.journeyGuidePreference!=="no_guide"?<div className="md:col-span-2"><p className="mb-3 text-sm font-semibold text-slate">Preferred languages <span className="font-normal text-stone">(choose all that apply)</span></p><div className="flex flex-wrap gap-2">{guideLanguageOptions.map(language=><button type="button" key={language} onClick={()=>dispatch({type:"journeyGuideLanguage",value:language})} className={cn("rounded-full border px-3 py-2 text-xs font-semibold transition",state.journeyGuideLanguages.includes(language)?"border-gold bg-gold text-forest shadow-sm":"border-stone/20 bg-white text-slate hover:border-gold")}>{state.journeyGuideLanguages.includes(language)?<Check className="mr-1 inline size-3"/>:null}{language}</button>)}</div></div>:null}<label className="grid gap-2 text-sm font-semibold text-slate md:col-span-2">Guide notes <span className="font-normal text-stone">(optional)</span><textarea rows={3} value={state.journeyGuideNotes} onChange={event=>dispatch({type:"journeyGuideNotes",value:event.target.value})} placeholder="Language nuance, guiding style, interests or any personal considerations…" className="rounded-xl border border-stone/20 bg-white px-4 py-3 leading-6 text-slate outline-none focus:border-gold"/></label></div></article>
    {selectedDestinations.map((destination,index)=>{
      const preference=state.destinationPreferences[destination.id];
      const specialistOptions=specialistGuideOptions(destination.name);
      const experiences=state.selectedExperienceIds.map(id=>data.experiences.find(item=>item.id===id)).filter((item):item is JourneyBootstrap["experiences"][number]=>item!==undefined&&item.destinationIds.includes(destination.id));
      return <article key={destination.id} className="overflow-hidden rounded-[2rem] border border-stone/15 bg-white shadow-[0_18px_55px_rgba(27,48,43,.08)]">
        <div className="grid md:grid-cols-[220px_1fr]">
          <div className="relative min-h-52 bg-sand md:min-h-full">{destination.hero_image_url&&<Image src={destination.hero_image_url} alt={destination.image_alt||destination.name} fill sizes="220px" className="object-cover"/>}<div className="absolute inset-0 bg-gradient-to-t from-slate/65 via-transparent to-transparent"/><span className="absolute bottom-5 left-5 rounded-full bg-ivory/90 px-3 py-1 text-[.65rem] font-bold uppercase tracking-[.18em] text-forest">Stop {index+1}</span></div>
          <div className="p-6 md:p-8">
            <p className="eyebrow">Preferences in {destination.province||"Sri Lanka"}</p><h2 className="mt-2 font-serif text-3xl">{destination.name}</h2>
            <div className="mt-6 border-y border-stone/15 py-5"><p className="mb-3 text-[.65rem] font-bold uppercase tracking-[.18em] text-gold">Selected experiences</p><div className="flex flex-wrap gap-2">{experiences.length?experiences.map(experience=>{const counts=state.experienceParticipants[experience.id];const total=counts?counts.adults+counts.children+counts.infants:0;return <span key={experience.id} className="rounded-full bg-sand-light px-3 py-2 text-xs text-slate/75">{experience.name}{total?` · ${total} guest${total===1?"":"s"}`:""}</span>}):<span className="text-sm text-stone">No experiences selected for this destination.</span>}</div></div>
            <div className="mt-6 grid gap-5 md:grid-cols-2">
              <label className="grid gap-2 text-sm font-semibold"><span className="flex items-center gap-2"><BedDouble className="size-4 text-gold"/>Stay preference</span><select aria-label={`Stay preference for ${destination.name}`} value={preference?.stayPreference||"recommend"} onChange={event=>dispatch({type:"stayPreference",destinationId:destination.id,value:event.target.value as typeof stayPreferenceOptions[number][0]})} className="rounded-xl border border-stone/25 bg-ivory px-4 py-3 outline-none focus:border-gold">{stayPreferenceOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
              {specialistOptions.length>1?<label className="grid gap-2 text-sm font-semibold"><span className="flex items-center gap-2"><UsersRound className="size-4 text-gold"/>Optional local specialist</span><select aria-label={`Specialist guide preference for ${destination.name}`} value={preference?.specialistGuidePreference||"none"} onChange={event=>dispatch({type:"specialistGuidePreference",destinationId:destination.id,value:event.target.value})} className="rounded-xl border border-stone/25 bg-ivory px-4 py-3 outline-none focus:border-gold">{specialistOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>:<div className="rounded-xl bg-sand-light px-4 py-3 text-sm text-stone"><strong className="block text-slate">Local specialist</strong>No specialist category is currently offered for this stop.</div>}
              <label className="grid gap-2 text-sm font-semibold md:col-span-2"><span className="flex items-center gap-2"><MoonStar className="size-4 text-gold"/>Planned nights <span className="font-normal text-stone">(optional)</span></span><input aria-label={`Planned nights in ${destination.name}`} type="number" min="0" max="60" value={preference?.nights??""} onChange={event=>dispatch({type:"destinationNights",destinationId:destination.id,value:event.target.value===""?null:Number(event.target.value)})} placeholder="Leave open if you would like us to suggest the pace" className="rounded-xl border border-stone/25 bg-ivory px-4 py-3 outline-none focus:border-gold"/></label>
              <label className="grid gap-2 text-sm font-semibold md:col-span-2"><span className="flex items-center gap-2"><NotebookPen className="size-4 text-gold"/>Notes for {destination.name} <span className="font-normal text-stone">(optional)</span></span><textarea aria-label={`Notes for ${destination.name}`} rows={3} value={preference?.notes||""} onChange={event=>dispatch({type:"destinationNotes",destinationId:destination.id,value:event.target.value})} placeholder="Room style, pace, accessibility, celebrations or anything your journey designer should consider…" className="rounded-xl border border-stone/25 bg-ivory px-4 py-3 leading-6 outline-none focus:border-gold"/></label>
            </div>
          </div>
        </div>
      </article>;
    })}
  </div>;
}

function EndpointEditor({kind,value,onChange,destinations}:{kind:"pickup"|"dropoff";value:JourneyEndpoint;onChange:(value:Partial<JourneyEndpoint>)=>void;destinations:JourneyBootstrap["destinations"]}){
  const pickup=kind==="pickup",airport=value.type==="airport";
  return <article className="rounded-[2rem] border border-stone/15 bg-white p-6 shadow-[0_14px_40px_rgba(27,48,43,.06)]"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-gold/10 text-gold">{airport?<Plane className="size-5"/>:<MapPin className="size-5"/>}</span><div><p className="eyebrow">{pickup?"Journey start":"Journey end"}</p><h3 className="font-serif text-2xl">{pickup?"Arrival / pickup":"Departure / drop-off"}</h3></div></div><div className="mt-6 grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">{pickup?"Pickup":"Drop-off"} type <span className="text-gold">Required</span><select value={value.type??""} onChange={event=>onChange({type:(event.target.value||null) as JourneyEndpoint["type"],airportCode:"",location:"",flightNumber:""})} className="rounded-xl border border-stone/25 bg-ivory px-4 py-3"><option value="">Choose one</option><option value="airport">Airport {pickup?"arrival":"departure"}</option><option value="other">Other {pickup?"pickup":"drop-off"} location</option></select></label>{airport?<label className="grid gap-2 text-sm font-semibold">Airport <span className="text-gold">Required</span><select value={value.airportCode} onChange={event=>onChange({airportCode:event.target.value})} className="rounded-xl border border-stone/25 bg-ivory px-4 py-3"><option value="">Choose airport</option>{sriLankaAirports.map(item=><option key={item.code} value={item.code}>{item.code} · {item.name}</option>)}</select></label>:value.type==="other"?<label className="grid gap-2 text-sm font-semibold">{pickup?"Pickup":"Drop-off"} location <span className="text-gold">Required</span><input list={`${kind}-locations`} value={value.location} onChange={event=>onChange({location:event.target.value})} placeholder="Hotel, address or meeting point" className="rounded-xl border border-stone/25 bg-ivory px-4 py-3"/><datalist id={`${kind}-locations`}>{destinations.map(item=><option key={item.id} value={item.name}/>)}</datalist></label>:null}<label className="grid gap-2 text-sm font-semibold">Date <span className="text-gold">Required</span><input required type="date" value={value.date} onChange={event=>onChange({date:event.target.value})} className="rounded-xl border border-stone/25 bg-ivory px-4 py-3"/></label><label className="grid gap-2 text-sm font-semibold">Time <span className="text-gold">Required</span><input required type="time" value={value.time} onChange={event=>onChange({time:event.target.value})} className="rounded-xl border border-stone/25 bg-ivory px-4 py-3"/></label>{airport?<label className="grid gap-2 text-sm font-semibold md:col-span-2">Flight number <span className="font-normal text-stone">(optional)</span><input value={value.flightNumber} onChange={event=>onChange({flightNumber:event.target.value})} placeholder={pickup?"Arrival flight":"Departure flight"} className="rounded-xl border border-stone/25 bg-ivory px-4 py-3"/></label>:null}</div></article>;
}

function JourneyDetailsStep({data,validationMessage}:{data:JourneyBootstrap;validationMessage:string}){
  const {state,dispatch}=useJourney();
  const minimumTravellers=Object.values(state.experienceParticipants).reduce((maximum,counts)=>({adults:Math.max(maximum.adults,counts.adults),children:Math.max(maximum.children,counts.children),infants:Math.max(maximum.infants,counts.infants)}),{adults:0,children:0,infants:0});
  const setTraveller=(key:keyof ParticipantCounts,value:number)=>dispatch({type:"travellers",counts:{...state.travellerCounts,[key]:value}});
  const travellers=state.travellerCounts.adults+state.travellerCounts.children+state.travellerCounts.infants;
  const suggestions=recommendedTravelPreferences(travellers).map(travelPreferenceLabel);
  const legs=completeJourneyLegs(state.selectedDestinationIds,Boolean(state.pickup.type),Boolean(state.dropoff.type));
  const locationName=(key:string)=>key==="pickup"?endpointLabel(state.pickup,"pickup"):key==="dropoff"?endpointLabel(state.dropoff,"dropoff"):data.destinations.find(item=>`destination:${item.id}`===key)?.name||"Journey stop";
  return <div className="mt-10">
    <div className="grid gap-5"><EndpointEditor kind="pickup" value={state.pickup} destinations={data.destinations} onChange={value=>dispatch({type:"pickup",value})}/><EndpointEditor kind="dropoff" value={state.dropoff} destinations={data.destinations} onChange={value=>dispatch({type:"dropoff",value})}/></div><div className="mt-5 grid gap-4 rounded-2xl bg-sand-light p-5 md:grid-cols-2">{(["adults","children","infants"] as const).map(key=><label key={key} className="grid gap-2 text-sm font-semibold">{key[0].toUpperCase()+key.slice(1)} <span className="text-gold">Required</span><input required type="number" min={key==="adults"?Math.max(1,minimumTravellers[key]):minimumTravellers[key]} value={state.travellerCounts[key]} onChange={event=>setTraveller(key,Number(event.target.value))} className="rounded-xl border border-stone/30 bg-white px-4 py-3"/>{minimumTravellers[key]>0&&<small className="font-normal text-stone">Minimum {minimumTravellers[key]} — already joining selected experiences.</small>}</label>)}<label className="grid gap-2 text-sm font-semibold">Preferred pace<select value={state.travelPace} onChange={event=>dispatch({type:"pace",value:event.target.value as JourneyState["travelPace"]})} className="rounded-xl border border-stone/30 bg-white px-4 py-3">{travelPaceOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold">Journey budget style<select value={state.budgetPreference} onChange={event=>dispatch({type:"budget",value:event.target.value})} className="rounded-xl border border-stone/30 bg-white px-4 py-3">{budgetPreferenceOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold md:col-span-2">Accessibility or mobility considerations <span className="font-normal text-stone">(optional)</span><textarea rows={3} value={state.accessibilityRequirements} onChange={event=>dispatch({type:"accessibility",value:event.target.value})} placeholder="Share anything that may help us plan access, walking distances or a gentler pace." className="rounded-xl border border-stone/30 bg-white px-4 py-3 leading-6"/></label>{validationMessage?<p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-800 md:col-span-2">{validationMessage}</p>:null}</div>
    <div className="mt-8"><p className="eyebrow">Getting around</p><h2 className="mt-2 font-serif text-3xl">One preference, with room for exceptions.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-stone">Choose the transport style you expect for most of the journey. Change only the legs that should feel different; Roam Ceylon confirms availability later.</p><label className="mt-5 grid max-w-xl gap-2 text-sm font-semibold">Default journey transport<select value={state.globalTravelPreference} onChange={event=>dispatch({type:"globalTravelPreference",value:event.target.value as typeof travelPreferenceOptions[number][0]})} className="rounded-xl border border-stone/25 bg-white px-4 py-3">{travelPreferenceOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{suggestions.length?<p className="mt-3 text-xs font-semibold text-forest">Well suited to {travellers} traveller{travellers===1?"":"s"}: {suggestions.join(" · ")}</p>:null}</div>
    <div className="mt-5 grid gap-4">{legs.length?legs.map(leg=>{const override=state.travelPreferencesByLeg[leg.key]?.travelPreference;const from=locationName(leg.fromLocationKey),to=locationName(leg.toLocationKey);return <article key={leg.key} className="grid items-center gap-4 rounded-2xl border border-stone/15 bg-white p-5 md:grid-cols-[1fr_auto_1fr_1.2fr]"><div><p className="eyebrow">From</p><strong>{from}</strong></div><ChevronRight className="text-gold"/><div><p className="eyebrow">To</p><strong>{to}</strong></div><label className="grid gap-2 text-xs font-bold uppercase tracking-widest text-stone">Transport preference<select value={override??""} onChange={event=>dispatch({type:"travelPreference",legKey:leg.key,value:event.target.value?event.target.value as typeof travelPreferenceOptions[number][0]:null})} className="rounded-xl border border-stone/25 bg-ivory px-3 py-2.5 text-sm font-normal normal-case tracking-normal"><option value="">Journey default · {travelPreferenceLabel(state.globalTravelPreference)}</option>{travelPreferenceOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></article>}):<Empty text="Complete the pickup, destinations and drop-off to build the full transport route."/>}</div>
    {state.selectedDestinationIds.length>0&&<div className="mt-8"><SriLankaMap destinations={data.destinations} selectedIds={state.selectedDestinationIds} pickup={state.pickup} dropoff={state.dropoff}/></div>}
  </div>;
}

const insightsFor=(state:JourneyState,data:JourneyBootstrap)=>evaluateJourneyInsights({selectedDestinationIds:state.selectedDestinationIds,selectedExperienceIds:state.selectedExperienceIds,destinations:data.destinations,experiences:data.experiences,destinationPreferences:state.destinationPreferences,travelPreferencesByLeg:state.travelPreferencesByLeg,pickup:state.pickup,dropoff:state.dropoff,globalTravelPreference:state.globalTravelPreference,travelDates:state.travelDates,travellerCounts:state.travellerCounts,budgetPreference:state.budgetPreference,travelPace:state.travelPace,accessibilityRequirements:state.accessibilityRequirements});

function JourneyInsightsStep({data,onAction}:{data:JourneyBootstrap;onAction:(step:number)=>void}){const {state}=useJourney();return <JourneyInsightsPanel result={insightsFor(state,data)} onAction={onAction}/>}

function ReviewStep({data,onAction}:{data:JourneyBootstrap;onAction:(step:number)=>void}){
  const {state}=useJourney();
  const legs=completeJourneyLegs(state.selectedDestinationIds,Boolean(state.pickup.type),Boolean(state.dropoff.type));
  const locationName=(key:string)=>key==="pickup"?endpointLabel(state.pickup,"pickup"):key==="dropoff"?endpointLabel(state.dropoff,"dropoff"):data.destinations.find(item=>`destination:${item.id}`===key)?.name||"Journey stop";
  return <div className="mt-10 grid gap-6">
    <article className="rounded-3xl border border-gold/25 bg-sand-light p-6 md:p-8"><p className="eyebrow">Arrival / pickup</p><h2 className="mt-2 font-serif text-3xl">{endpointLabel(state.pickup,"pickup")}</h2><div className="mt-5 grid gap-4 md:grid-cols-3"><ReviewItem label="Date" value={state.pickup.date}/><ReviewItem label="Time" value={state.pickup.time}/>{state.pickup.flightNumber?<ReviewItem label="Flight" value={state.pickup.flightNumber}/>:null}</div></article>
    <article className="rounded-3xl bg-forest p-6 text-ivory md:p-8"><p className="eyebrow text-gold-light">Guide preference</p><div className="mt-5 grid gap-5 md:grid-cols-2"><ReviewItem label="Primary journey guide" value={journeyGuidePreferenceLabel(state.journeyGuidePreference)} dark/><ReviewItem label="Preferred languages" value={state.journeyGuidePreference==="no_guide"?"Not required":state.journeyGuideLanguages.join(", ")||"Open to recommendation"} dark/>{state.journeyGuideNotes?<div className="md:col-span-2"><ReviewItem label="Guide notes" value={state.journeyGuideNotes} dark/></div>:null}</div></article>
    {state.selectedDestinationIds.map((destinationId,index)=>{const destination=data.destinations.find(item=>item.id===destinationId);if(!destination)return null;const preference=state.destinationPreferences[destinationId];const experiences=state.selectedExperienceIds.map(id=>data.experiences.find(item=>item.id===id)).filter((item):item is JourneyBootstrap["experiences"][number]=>item!==undefined&&item.destinationIds.includes(destinationId));return <article key={destinationId} className="rounded-3xl border border-stone/15 bg-white p-6 md:p-8"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Stop {index+1}</p><h2 className="mt-2 font-serif text-3xl">{destination.name}</h2></div><MapPin className="text-gold"/></div><div className="mt-6 grid gap-5 border-t border-stone/15 pt-6 md:grid-cols-2"><ReviewItem label="Stay preference" value={stayPreferenceLabel(preference?.stayPreference||"recommend")}/><ReviewItem label="Local specialist" value={specialistGuidePreferenceLabel(destination.name,preference?.specialistGuidePreference||"none")}/><ReviewItem label="Planned nights" value={preference?.nights===null||preference?.nights===undefined?"Open for your journey designer":`${preference.nights} night${preference.nights===1?"":"s"}`}/><div className="md:col-span-2"><p className="text-[.65rem] font-bold uppercase tracking-widest text-gold">Experiences</p><div className="mt-2 flex flex-wrap gap-2">{experiences.length?experiences.map(item=><span key={item.id} className="rounded-full bg-sand-light px-3 py-2 text-xs">{item.name}</span>):<span className="text-sm text-stone">No experiences selected.</span>}</div></div>{preference?.notes&&<div className="md:col-span-2"><ReviewItem label="Destination notes" value={preference.notes}/></div>}</div></article>})}
    <article className="rounded-3xl bg-forest p-6 text-ivory md:p-8"><p className="eyebrow text-gold-light">Traveller details</p><div className="mt-5 grid gap-5 md:grid-cols-2"><ReviewItem label="Travel dates" value={`${state.pickup.date} to ${state.dropoff.date}`} dark/><ReviewItem label="Travellers" value={`${state.travellerCounts.adults+state.travellerCounts.children+state.travellerCounts.infants}`} dark/><ReviewItem label="Preferred pace" value={travelPaceOptions.find(([value])=>value===state.travelPace)?.[1]||"Balanced"} dark/><ReviewItem label="Budget style" value={budgetPreferenceOptions.find(([value])=>value===state.budgetPreference)?.[1]||"Open to guidance"} dark/>{state.accessibilityRequirements?<div className="md:col-span-2"><ReviewItem label="Accessibility considerations" value={state.accessibilityRequirements} dark/></div>:null}</div><div className="mt-6 border-t border-ivory/10 pt-6"><p className="text-[.65rem] font-bold uppercase tracking-widest text-gold-light">Complete transport route · default {travelPreferenceLabel(state.globalTravelPreference)}</p><div className="mt-3 grid gap-3">{legs.map(leg=><div key={leg.key} className="flex flex-wrap items-center justify-between gap-2 rounded-xl bg-ivory/5 px-4 py-3 text-sm"><span>{locationName(leg.fromLocationKey)} → {locationName(leg.toLocationKey)}</span><strong className="text-gold-light">{travelPreferenceLabel(effectiveTravelPreference(state.travelPreferencesByLeg,leg.key,state.globalTravelPreference))}</strong></div>)}</div></div></article>
    <article className="rounded-3xl border border-gold/25 bg-sand-light p-6 md:p-8"><p className="eyebrow">Departure / drop-off</p><h2 className="mt-2 font-serif text-3xl">{endpointLabel(state.dropoff,"dropoff")}</h2><div className="mt-5 grid gap-4 md:grid-cols-3"><ReviewItem label="Date" value={state.dropoff.date}/><ReviewItem label="Time" value={state.dropoff.time}/>{state.dropoff.flightNumber?<ReviewItem label="Flight" value={state.dropoff.flightNumber}/>:null}</div></article>
    <JourneyInsightsPanel result={insightsFor(state,data)} onAction={onAction} compact/>
  </div>;
}

function ReviewItem({label,value,dark=false}:{label:string;value:string;dark?:boolean}){return <div><p className={cn("text-[.65rem] font-bold uppercase tracking-widest",dark?"text-gold-light":"text-gold")}>{label}</p><p className={cn("mt-2 text-sm leading-6",dark?"text-ivory/75":"text-slate/70")}>{value}</p></div>}

function Builder({data}:{data:JourneyBootstrap}){
  const {state,dispatch}=useJourney();
  const step=state.currentStep;
  const setStep=(value:number)=>dispatch({type:"step",value});
  const [quotationOpen,setQuotationOpen]=useState(false);
  const [detailsAttempted,setDetailsAttempted]=useState(false);
  const detailsIssue=journeyDetailsIssue(state);
  const continueJourney=()=>{if(step===4&&detailsIssue){setDetailsAttempted(true);return}setDetailsAttempted(false);setStep(step+1)};
  const openQuotation=()=>{if(detailsIssue){setDetailsAttempted(true);setStep(4);return}setQuotationOpen(true)};
  const destinations=useMemo(()=>availableDestinations(data.destinations,state.selectedThemeIds),[data.destinations,state.selectedThemeIds]);
  const experiences=useMemo(()=>availableExperiences(data.experiences,state.selectedDestinationIds,state.selectedThemeIds),[data.experiences,state.selectedDestinationIds,state.selectedThemeIds]);
  const current=step===0?data.themes:destinations;
  const selected=step===0?state.selectedThemeIds:state.selectedDestinationIds;
  const field=step===0?"selectedThemeIds":"selectedDestinationIds";
  const estimateRequest={selectedDestinationIds:state.selectedDestinationIds,selectedExperienceIds:state.selectedExperienceIds,selectedPricingPlanIds:state.selectedPricingPlanIds,destinationPreferences:state.destinationPreferences,journeyGuidePreference:state.journeyGuidePreference,pickup:state.pickup,dropoff:state.dropoff,globalTravelPreference:state.globalTravelPreference,travelPreferencesByLeg:state.travelPreferencesByLeg,travelDates:state.travelDates,travellerCounts:state.travellerCounts,experienceParticipants:state.experienceParticipants};
  const journeyEstimate=useJourneyEstimate(estimateRequest);
  return <><div className="shell grid gap-8 py-12 lg:grid-cols-[1fr_340px]">
    <section>
      <div className="mb-10 flex gap-2 overflow-x-auto">{steps.map((label,index)=><button key={label} onClick={()=>index<=step&&setStep(index)} className={cn("flex min-w-fit items-center gap-2 rounded-full px-4 py-2 text-xs font-bold",index===step?"bg-forest text-ivory":index<step?"bg-sand text-forest":"bg-stone/10 text-stone")}>{index<step?<Check className="size-3"/>:index+1} {label}</button>)}</div>
      <AnimatePresence mode="wait"><motion.div key={step} initial={{opacity:0,x:22}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-18}}>
        <p className="eyebrow mb-3">Step {step+1} of {steps.length}</p><h1 className="font-serif text-4xl md:text-6xl">{stepTitles[step]}</h1><p className="mt-4 max-w-2xl text-slate/60">{step===1&&!state.selectedThemeIds.length?"Choose a theme to reveal its linked destinations.":step===2&&!state.selectedDestinationIds.length?"Choose a destination to reveal its linked experiences.":step===3?"Tell us what feels right in each destination. Your journey designer will choose the individual partners later.":step===4?"Add your dates and party size, then shape how you would like to travel between each destination.":step===5?"Consider these gentle observations, or continue without changing a thing.":step===6?"Check every preference before asking us to shape the proposal.":"Shape each choice as you move through your journey."}</p>
        {step<2?<><div className="mt-10 grid gap-5 md:grid-cols-2">{current.map(item=><ChoiceCard key={item.id} item={item} selected={selected.includes(item.id)} onClick={()=>dispatch({type:"toggle",field,id:item.id})}/>)}</div>{step===1&&<div className="mt-10"><SriLankaMap destinations={destinations} selectedIds={state.selectedDestinationIds} onSelect={id=>dispatch({type:"toggle",field:"selectedDestinationIds",id})}/></div>}</>:null}
        {step===2?<ExperienceDiscovery compact experiences={experiences} globalTravellers={state.travellerCounts} selectedIds={state.selectedExperienceIds} participantsByExperience={state.experienceParticipants} selectedPricingPlanIds={state.selectedPricingPlanIds} onInclude={(experience,participants,travellers,pricingPlanId)=>{dispatch({type:"travellers",counts:travellers});dispatch({type:"includeExperience",experienceId:experience.id,counts:participants,pricingPlanId})}} onRemove={experience=>dispatch({type:"removeExperience",experienceId:experience.id})} onParticipantsChange={(experience,participants,pricingPlanId)=>dispatch({type:"experienceParticipants",experienceId:experience.id,counts:participants,pricingPlanId})}/>:null}
        {step===3?<JourneyPreferencesStep data={data}/>:null}{step===4?<JourneyDetailsStep data={data} validationMessage={detailsAttempted?detailsIssue:""}/>:null}{step===5?<JourneyInsightsStep data={data} onAction={setStep}/>:null}{step===6?<ReviewStep data={data} onAction={setStep}/>:null}
        <div className="mt-10 flex justify-between"><Button variant="ghost" disabled={step===0} onClick={()=>setStep(step-1)}><ChevronLeft/>Back</Button>{step<steps.length-1?<Button onClick={continueJourney}>Continue<ChevronRight/></Button>:<Button onClick={openQuotation} disabled={!state.selectedDestinationIds.length} variant="accent">Request Journey Proposal</Button>}</div>
      </motion.div></AnimatePresence>
    </section>
    <Summary data={data} estimateState={journeyEstimate} onQuotation={openQuotation}/>
  </div><QuotationModal open={quotationOpen} onClose={()=>setQuotationOpen(false)} onSubmitted={()=>dispatch({type:"hydrate",state:emptyJourneyState})} state={state} quote={journeyEstimate.estimate}/></>;
}

function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-stone/30 p-8 text-sm text-stone">{text}</div>}

function Summary({data,estimateState,onQuotation}:{data:JourneyBootstrap;estimateState:ReturnType<typeof useJourneyEstimate>;onQuotation:()=>void}){
  const {state}=useJourney();
  const [exporting,setExporting]=useState(false);
  const selectedPlanName=(item:{id:string;pricingPlans:JourneyPricingPlan[]})=>item.pricingPlans.find(plan=>plan.id===state.selectedPricingPlanIds[pricingPlanKey("experience",item.id)])?.name||item.pricingPlans[0]?.name||null;
  const pickupRoute=state.pickup.type?endpointRouteLocation(state.pickup,"pickup",data.destinations):null;
  const dropoffRoute=state.dropoff.type?endpointRouteLocation(state.dropoff,"dropoff",data.destinations):null;
  const completeRouteDestinations=[...data.destinations,...(pickupRoute?[pickupRoute]:[]),...(dropoffRoute?[dropoffRoute]:[])];
  const completeRouteIds=[...(pickupRoute?[pickupRoute.id]:[]),...state.selectedDestinationIds,...(dropoffRoute?[dropoffRoute.id]:[])];
  const route=getRouteEstimate(completeRouteDestinations,completeRouteIds);
  const {estimate,loading}=estimateState;
  const travellers=state.travellerCounts.adults+state.travellerCounts.children+state.travellerCounts.infants;
  const selectedDestinations=state.selectedDestinationIds.map(id=>data.destinations.find(item=>item.id===id)).filter((item):item is JourneyBootstrap["destinations"][number]=>Boolean(item));
  const legs=completeJourneyLegs(state.selectedDestinationIds,Boolean(state.pickup.type),Boolean(state.dropoff.type));
  const locationName=(key:string)=>key==="pickup"?endpointLabel(state.pickup,"pickup"):key==="dropoff"?endpointLabel(state.dropoff,"dropoff"):data.destinations.find(item=>`destination:${item.id}`===key)?.name||"Journey stop";
  const travelSummary=legs.map(leg=>`${locationName(leg.fromLocationKey)} to ${locationName(leg.toLocationKey)} - ${travelPreferenceLabel(effectiveTravelPreference(state.travelPreferencesByLeg,leg.key,state.globalTravelPreference))}`).join("; ");
  const routeCoordinates=completeRouteIds.flatMap(id=>{const item=completeRouteDestinations.find(destination=>destination.id===id);return item&&Number.isFinite(item.latitude)&&Number.isFinite(item.longitude)?[{name:item.name,latitude:Number(item.latitude),longitude:Number(item.longitude)}]:[]});
  const exportPdf=async()=>{setExporting(true);try{const specialists=selectedDestinations.flatMap(item=>{const label=specialistGuidePreferenceLabel(item.name,state.destinationPreferences[item.id]?.specialistGuidePreference||"none");return label==="None"?[]:[`${item.name}: ${label}`]});await exportJourneyPdf({themes:state.selectedThemeIds.map(id=>data.themes.find(item=>item.id===id)?.name).filter((name):name is string=>Boolean(name)),destinations:selectedDestinations.map(item=>item.name),routeCoordinates,experiences:state.selectedExperienceIds.map(id=>{const item=data.experiences.find(experience=>experience.id===id);if(!item)return null;const plan=selectedPlanName(item);const counts=state.experienceParticipants[item.id];const participants=counts?counts.adults+counts.children+counts.infants:0;return `${item.name}${participants?` - ${participants} participant${participants===1?"":"s"}`:""}${plan?` - ${plan}`:""}`}).filter((name):name is string=>Boolean(name)),accommodations:selectedDestinations.map(item=>`${item.name} - ${stayPreferenceLabel(state.destinationPreferences[item.id]?.stayPreference||"recommend")}`),vehicle:travelSummary||null,guide:`${journeyGuidePreferenceLabel(state.journeyGuidePreference)}${state.journeyGuideLanguages.length?` (${state.journeyGuideLanguages.join(", ")})`:""}${specialists.length?`; Specialists: ${specialists.join("; ")}`:""}`,travelDates:state.travelDates,travellerCounts:state.travellerCounts,estimatedDistance:route.estimatedDistance,estimatedTravelDays:route.estimatedTravelDays,quote:estimate});}finally{setExporting(false)}};
  const ranged=estimate?.status==="estimated_range";
  const money=(value:number|null)=>value===null?"—":value.toLocaleString("en-US",{maximumFractionDigits:0});
  return <aside className="h-fit rounded-3xl bg-forest p-7 text-ivory lg:sticky lg:top-28">
    <div className="mb-6 flex items-center gap-3"><Sparkles className="text-gold-light"/><h2 className="font-serif text-2xl">Your journey</h2></div>
    {[[state.selectedThemeIds,data.themes,"Themes"],[state.selectedDestinationIds,data.destinations,"Destinations"]].map(([ids,items,label])=><div className="border-t border-ivory/10 py-5" key={label as string}><p className="mb-3 text-[.65rem] font-bold uppercase tracking-widest text-gold-light">{label as string}</p><div className="flex flex-wrap gap-2">{(ids as string[]).length?(ids as string[]).map(id=><span key={id} className="rounded-full bg-ivory/10 px-3 py-1 text-xs">{(items as Card[]).find(item=>item.id===id)?.name}</span>):<span className="text-sm text-ivory/40">Nothing selected yet</span>}</div></div>)}
    <div className="border-t border-ivory/10 py-5"><p className="mb-3 text-[.65rem] font-bold uppercase tracking-widest text-gold-light">Experiences</p><div className="flex flex-wrap gap-2">{state.selectedExperienceIds.length?state.selectedExperienceIds.map(id=>{const item=data.experiences.find(experience=>experience.id===id);const counts=state.experienceParticipants[id];const plan=item?selectedPlanName(item):null;return <span key={id} className="rounded-full bg-ivory/10 px-3 py-1 text-xs">{item?.name}{counts?` · ${counts.adults+counts.children+counts.infants}`:""}{plan?` · ${plan}`:""}</span>}):<span className="text-sm text-ivory/40">Nothing selected yet</span>}</div></div>
    <div className="border-t border-ivory/10 py-5"><p className="mb-3 text-[.65rem] font-bold uppercase tracking-widest text-gold-light">Preferences & plan</p><div className="grid gap-3 text-sm text-ivory/70"><div><strong className="text-ivory">Primary guide</strong><span className="mt-1 block text-xs">{journeyGuidePreferenceLabel(state.journeyGuidePreference)}{state.journeyGuideLanguages.length?` · ${state.journeyGuideLanguages.join(", ")}`:""}</span></div>{selectedDestinations.map(item=>{const preference=state.destinationPreferences[item.id];const specialist=specialistGuidePreferenceLabel(item.name,preference?.specialistGuidePreference||"none");return <div key={item.id}><strong className="text-ivory">{item.name}</strong><span className="mt-1 block text-xs">{stayPreferenceLabel(preference?.stayPreference||"recommend")}{specialist!=="None"?` · ${specialist}`:""}</span></div>})}{legs.length?<div className="grid gap-2 border-t border-ivory/10 pt-3">{legs.map(leg=><span key={leg.key} className="text-xs">{locationName(leg.fromLocationKey)} → {locationName(leg.toLocationKey)} · {travelPreferenceLabel(effectiveTravelPreference(state.travelPreferencesByLeg,leg.key,state.globalTravelPreference))}</span>)}</div>:null}{!selectedDestinations.length&&<span className="text-ivory/40">Nothing selected yet</span>}</div></div>
    <div className="border-t border-ivory/10 py-5"><div className="flex justify-between text-sm"><span>{travellers?`${travellers} travellers`:"Travellers not set"}</span><span>{route.estimatedDistance} km</span></div>{loading?<p className="mt-4 text-sm text-ivory/50">Refining your estimate…</p>:ranged?<div className="mt-5 grid gap-3"><p className="text-[.65rem] font-bold uppercase tracking-widest text-gold-light">Your estimated journey</p><div><strong className="block font-serif text-3xl">{estimate.currency} {money(estimate.perPersonMin)} – {money(estimate.perPersonMax)}</strong><span className="text-xs text-ivory/55">per person</span></div><p className="text-xs text-ivory/70">For {travellers} traveller{travellers===1?"":"s"} · {estimate.durationDays} day{estimate.durationDays===1?"":"s"}</p><p className="text-xs text-ivory/50">Based on your current journey preferences.</p><div className="flex justify-between border-t border-ivory/10 pt-3 text-xs text-ivory/65"><span>Estimated journey total</span><span>{estimate.currency} {money(estimate.totalMin)} – {money(estimate.totalMax)}</span></div><p className="text-xs leading-5 text-ivory/55">{estimate.message}</p><details className="border-t border-ivory/10 pt-3 text-xs text-ivory/60"><summary className="cursor-pointer font-semibold text-ivory/80">What affects this estimate?</summary><ul className="mt-3 grid gap-1 pl-4">{estimate.factors.map(factor=><li key={factor} className="list-disc">{factor}</li>)}</ul></details></div>:state.selectedDestinationIds.length?<div className="mt-4 rounded-2xl bg-ivory/5 p-4"><p className="font-serif text-xl text-ivory">Your planning range is taking shape</p><p className="mt-2 text-xs leading-5 text-ivory/55">Complete the journey details shown in the builder so we can present a dependable estimate before you request your proposal.</p></div>:<p className="mt-4 text-sm text-ivory/40">Select destinations to shape your estimate.</p>}</div>
    <Button onClick={onQuotation} disabled={!state.selectedDestinationIds.length||state.currentStep<steps.length-1} variant="accent" className="mb-3 w-full">{state.currentStep<steps.length-1?"Review journey to continue":"Request Journey Proposal"}</Button>
    <Button onClick={exportPdf} disabled={!state.selectedDestinationIds.length||exporting} variant="outline" className="w-full border-ivory/20 text-ivory hover:bg-ivory/10"><Download/>{exporting?"Preparing PDF...":"Export Journey Summary"}</Button>
    <div className="mt-4 flex items-center gap-2 text-xs text-ivory/55"><MapPin className="size-4"/>Review and revise every choice before requesting your quote.</div>
  </aside>;
}

export function JourneyBuilder({data,initialSelection}:{data:JourneyBootstrap;initialSelection?:JourneyInitialSelection}){return <JourneyProvider data={data} initialSelection={initialSelection}><Builder data={data}/></JourneyProvider>}
