-- Premium destination editorial catalogue: coast and marine journeys.
-- Content only: no schema, relationships, pricing or journey logic are changed.

with catalog as (
  select * from jsonb_to_recordset($catalog$[
    {
      "slug":"arugambay",
      "short_description":"A storied east-coast surf town where point breaks, lagoons and unhurried beach life meet the edge of the wild.",
      "full_description":"Arugam Bay is best known for the long, clean lines of its main point break, yet the place reveals more when explored beyond the surf. Sandy lanes lead to cafés and small guesthouses, fishing boats return at first light, and nearby lagoons and dry-zone landscapes bring wildlife remarkably close to the coast. The mood is sociable but relaxed, with sunrise sessions and slow evenings setting the rhythm.",
      "why_visit":"Come for world-class surf conditions, stay for the east coast’s easy pace and the contrast between ocean, lagoon and dry-zone wilderness.",
      "historical_importance":null,
      "cultural_significance":"The bay remains connected to Muslim and Tamil coastal communities, fishing traditions and the sacred landscapes around nearby Muhudu Maha Viharaya and Okanda. Respectful dress is appreciated away from the beach.",
      "unesco_information":null,
      "nature_wildlife":"Lagoons and scrubland around Pottuvil support elephants, crocodiles, water birds and monkeys. Wildlife encounters should be made with licensed, low-impact operators and generous distance.",
      "best_time_to_visit":"May to September usually offers the most reliable surf and driest east-coast weather. November to February is quieter and wetter, with some seasonal businesses reducing hours.",
      "weather":"Warm year-round, commonly 27–33°C. The east coast is generally driest from May to September, while the northeast monsoon brings more rain and occasional rough seas from November into February.",
      "local_highlights":["Sunrise surf at Main Point and nearby breaks","Lagoon safaris through quiet bird habitat","Fishing-village mornings and relaxed beach evenings","Elephant Rock viewpoints and coastal walks","A day journey towards Kumana’s wetlands"],
      "nearby_attractions":["Pottuvil Lagoon","Muhudu Maha Viharaya","Elephant Rock","Kumana National Park","Okanda coastal sanctuary"],
      "travel_tips":["Match surf breaks to your ability and use an experienced local instructor.","Carry cash because smaller businesses may not accept cards.","Keep a respectful distance from elephants seen outside protected areas.","Plan transfers in advance; the east-coast journey is long but rewarding."]
    },
    {
      "slug":"balapitiya",
      "short_description":"A southern river town opening onto the Madu Ganga’s mangroves, islands and quietly cinematic waterways.",
      "full_description":"Balapitiya is the gateway to one of the south coast’s most absorbing wetland landscapes. The Madu Ganga threads between mangrove banks, cinnamon-growing islands and small waterside communities before meeting the sea. It is a place for an early boat journey, patient birdwatching and a closer view of how river and coastal life overlap.",
      "why_visit":"Choose Balapitiya for a softer adventure: intimate waterways, village stories and nature close to the established southern-coast route.",
      "historical_importance":null,
      "cultural_significance":"River islands support long-standing fishing, cinnamon and Buddhist traditions. The best visits favour community knowledge and avoid staged wildlife handling.",
      "unesco_information":null,
      "nature_wildlife":"The Madu Ganga wetland includes mangroves, mudflats and islands used by water birds, reptiles and aquatic life. Its value lies in the complete estuarine system rather than any single sighting.",
      "best_time_to_visit":"December to April often brings brighter, calmer conditions. Early morning is rewarding throughout the year, with fewer boats and better wildlife activity.",
      "weather":"Tropical and humid, usually 26–31°C. Rain is possible year-round, with wetter spells during the southwest monsoon and the inter-monsoon months.",
      "local_highlights":["A quiet morning boat journey on the Madu Ganga","Mangrove channels and island scenery","Traditional cinnamon cultivation","Water birds along the estuary","A slow transition between river and coast"],
      "nearby_attractions":["Ahungalla","Ambalangoda","Kosgoda","Bentota","Hikkaduwa"],
      "travel_tips":["Choose a licensed operator who avoids feeding or handling wildlife.","Travel early for cooler temperatures and quieter waterways.","Carry insect protection and a light rain layer.","Ask before photographing residents on the smaller islands."]
    },
    {
      "slug":"bentota",
      "short_description":"A polished southwest-coast escape pairing a broad golden beach with river adventures, gardens and refined stays.",
      "full_description":"Bentota balances beach time with a surprising variety of experiences. The wide shore invites long walks and restful days, while the Bentota River offers watersports and gentler journeys through palm-lined channels. Elegant architecture, landscaped gardens and easy rail access give the area a composed character that works especially well at the beginning or end of an island itinerary.",
      "why_visit":"Visit for an effortless coastal stay with enough river, design and cultural interest to make every day feel different.",
      "historical_importance":null,
      "cultural_significance":"Bentota’s modern identity is closely linked to Sri Lankan tropical modernism, especially the work and gardens associated with Geoffrey and Bevis Bawa in the surrounding area.",
      "unesco_information":null,
      "nature_wildlife":"Riverbanks, wetlands and the nearby Madu Ganga support birds and estuarine life. Sea-turtle conservation projects operate along the wider coast and should be selected for responsible practices.",
      "best_time_to_visit":"December to April is usually best for calmer seas and sunnier beach days. River experiences remain possible for much of the year, adjusted around rainfall.",
      "weather":"Warm and humid, generally 26–31°C. The southwest monsoon is most influential from May to September, with additional showers often around October and November.",
      "local_highlights":["Long golden-beach walks","Bentota River adventures and sunset cruises","Lunuganga’s landscape and design legacy","Brief Garden near Beruwala","Thoughtful resort stays with easy Colombo access"],
      "nearby_attractions":["Lunuganga","Brief Garden","Beruwala","Kosgoda","Balapitiya and Madu Ganga"],
      "travel_tips":["Confirm sea conditions before swimming or watersports.","Reserve garden visits in advance where required.","Use reputable operators with clear safety equipment for river activities.","Allow time for traffic when transferring to Colombo or the airport."]
    },
    {
      "slug":"hikkaduwa",
      "short_description":"A lively southern beach town with reef encounters, surf breaks and an easy social energy beside the Indian Ocean.",
      "full_description":"Hikkaduwa brings together several versions of the south coast in one compact place. There are surf breaks for different abilities, a busy ribbon of cafés and small hotels, and a protected marine area just offshore. Its energy is brighter than the quieter beaches nearby, making it well suited to travellers who enjoy activity and choice.",
      "why_visit":"Choose Hikkaduwa for accessible surf, coastal nightlife and the chance to experience a coral-reef environment close to Galle.",
      "historical_importance":null,
      "cultural_significance":"The town grew from a fishing settlement into one of Sri Lanka’s earliest beach destinations. Fishing and Buddhist village life remain present beyond the tourism strip.",
      "unesco_information":null,
      "nature_wildlife":"Hikkaduwa National Park protects a fringing coral reef and associated marine life. Reef experiences should never involve standing on coral, touching animals or feeding turtles.",
      "best_time_to_visit":"November to April generally brings calmer water, clearer snorkelling and favourable surf on the southwest coast.",
      "weather":"Warm and humid year-round, around 26–31°C. May to September is typically wetter and seas can be rougher under the southwest monsoon.",
      "local_highlights":["Surf sessions for beginner and experienced riders","Glass-bottom or snorkelling views of the reef","Sunset cafés and an easy-going social scene","A short journey to Galle Fort","Quieter village and temple life inland"],
      "nearby_attractions":["Galle Fort","Seenigama temple","Ambalangoda","Madu Ganga","Unawatuna"],
      "travel_tips":["Never stand on coral or touch marine wildlife.","Check currents and use guarded swimming areas where available.","Choose reef operators with clear conservation standards.","Expect a livelier atmosphere than on the more secluded southern beaches."]
    },
    {
      "slug":"kalpitiya",
      "short_description":"A wind-shaped peninsula of lagoons, sandbars and open water, celebrated for kitesurfing and marine encounters.",
      "full_description":"Kalpitiya feels elemental: steady wind over the lagoon, fishing boats on the horizon and narrow strips of land between sea and water. Kitesurfers are drawn by the seasonal conditions, while offshore excursions reveal dolphins and the wider marine landscape. The peninsula remains working and local, rewarding travellers who value activity over polish.",
      "why_visit":"Come for Sri Lanka’s leading kitesurfing environment and a remote coastal character that feels distinct from the southern beach circuit.",
      "historical_importance":"Kalpitiya’s position on old maritime routes is reflected in its colonial-era Dutch Fort and the layered trading history of the peninsula.",
      "cultural_significance":"Fishing communities, churches, mosques and coastal villages give the peninsula a diverse identity. Tourism works best when it supports local operators and respects working shorelines.",
      "unesco_information":null,
      "nature_wildlife":"The Bar Reef marine area, lagoon habitats and offshore waters support coral, dolphins, seabirds and seasonal whale sightings. Conditions and sightings are never guaranteed.",
      "best_time_to_visit":"May to October is the principal southwest-wind kitesurf season; December to March offers a second, gentler wind period and is often preferred for offshore wildlife trips.",
      "weather":"Hot, sunny and relatively dry, commonly 27–33°C. Wind is a defining seasonal feature; brief monsoon showers and changing sea conditions remain possible.",
      "local_highlights":["Kitesurfing across the lagoon and ocean","Dolphin-watching with responsible operators","Remote sandbars and fishing villages","Kalpitiya Dutch Fort","A slower peninsula landscape away from resort crowds"],
      "nearby_attractions":["Bar Reef marine area","Dutch Fort Kalpitiya","Alankuda coast","Puttalam Lagoon","Wilpattu National Park"],
      "travel_tips":["Book qualified kitesurf instruction suited to your ability.","Treat wildlife sightings as a privilege, not a guarantee.","Use operators who maintain distance from dolphin pods.","Carry sun protection; shade can be limited on the water."]
    },
    {
      "slug":"kalutara",
      "short_description":"A river-meets-ocean town where sacred landmarks, tropical gardens and restorative coastal stays sit within easy reach of Colombo.",
      "full_description":"Kalutara offers a gentle introduction to the southwest coast. The broad Kalu Ganga reaches the ocean beside the town’s distinctive white stupa, while resort gardens and Ayurveda programmes create space to slow down. It is less about a checklist of sights than a comfortable transition into island time.",
      "why_visit":"Choose Kalutara for convenient coastal calm, considered wellness and a glimpse of local religious life without travelling far from Colombo.",
      "historical_importance":"The area’s river crossing and coastal position shaped its trading importance, while Richmond Castle reflects the architectural ambitions of the early twentieth century.",
      "cultural_significance":"Kalutara Bodhiya and the riverside stupa are active places of Buddhist devotion. The custom of pausing or offering a coin when passing the Bodhi tree remains widely observed.",
      "unesco_information":null,
      "nature_wildlife":"The Kalu Ganga estuary, coast and nearby gardens support water birds and tropical plant life, offering nature in a soft, accessible form.",
      "best_time_to_visit":"December to April generally provides the most reliable beach weather. Ayurveda and garden stays remain appealing throughout the year.",
      "weather":"Tropical, humid and warm, usually 26–31°C. Rainfall is higher during the southwest monsoon and inter-monsoon periods.",
      "local_highlights":["Kalutara Bodhiya and riverside stupa","Restorative Ayurveda programmes","Richmond Castle and its gardens","Kalu Ganga sunsets","Easy access to the southern coastal railway"],
      "nearby_attractions":["Richmond Castle","Beruwala","Bentota","Brief Garden","Colombo"],
      "travel_tips":["Dress modestly and remove footwear at sacred sites.","Allow extra road time during commuter hours.","Discuss wellness treatments and medical considerations in advance.","Confirm sea conditions before swimming."]
    },
    {
      "slug":"mirissa",
      "short_description":"A palm-framed southern bay known for ocean mornings, whale-watching journeys and relaxed evenings by the sea.",
      "full_description":"Mirissa curves around a photogenic bay where fishing boats, surf and beach cafés share the shoreline. Before sunrise, boats head into deeper water in search of whales; later, the pace returns to swimming, coastal viewpoints and unhurried meals. The town is popular, yet quieter moments remain easy to find at the edges of the day.",
      "why_visit":"Visit for a classic southern beach stay with access to responsible whale watching, gentle surf and an inviting food scene.",
      "historical_importance":null,
      "cultural_significance":"Mirissa remains linked to the working fisheries of Sri Lanka’s south coast. Visitors should remember that harbours and landing beaches are workplaces as well as points of departure.",
      "unesco_information":null,
      "nature_wildlife":"Deep waters south of the island are used by blue whales and other cetaceans. Responsible trips maintain distance, limit pursuit and accept that wildlife cannot be guaranteed.",
      "best_time_to_visit":"November to April usually provides calmer seas and the most comfortable beach conditions. Whale sightings vary naturally and should never be presented as certain.",
      "weather":"Warm and humid, generally 26–31°C. The southwest monsoon brings rougher seas and more rain from roughly May to September.",
      "local_highlights":["Responsible whale-watching departures","Crescent-bay swimming in calm conditions","Sunrise at Coconut Tree Hill","Gentle surf and oceanfront cafés","Seafood linked to the working harbour"],
      "nearby_attractions":["Weligama","Matara Fort and temple sites","Polhena","Dondra Head","Galle Fort"],
      "travel_tips":["Select whale-watching operators that follow recognised distance and speed practices.","Take seasickness precautions before early boat departures.","Avoid cliff edges and exposed viewpoints in strong wind.","Confirm current swimming conditions locally."]
    },
    {
      "slug":"mountlavinia",
      "short_description":"A heritage beach suburb where Colombo’s city energy gives way to sea views, railway rhythms and sunset dining.",
      "full_description":"Mount Lavinia offers the coast without leaving the capital region. Trains trace the shore, fishing craft gather beyond the beach, and the historic hotel overlooking the bay recalls an earlier era of Colombo life. It is best enjoyed as an easy afternoon, a first night after arrival or a relaxed base for combining city and sea.",
      "why_visit":"Choose Mount Lavinia for a convenient beach pause, sunset seafood and quick access to Colombo’s galleries, markets and restaurants.",
      "historical_importance":"The suburb’s best-known landmark is the Mount Lavinia Hotel, developed from a colonial governor’s residence and closely associated with the area’s nineteenth-century story.",
      "cultural_significance":"The beach is part of everyday metropolitan life, shared by families, fishers, walkers and diners rather than existing only as a visitor enclave.",
      "unesco_information":null,
      "nature_wildlife":null,
      "best_time_to_visit":"December to April usually offers the brightest beach weather. Sunset is the most atmospheric time throughout the year when conditions are clear.",
      "weather":"Hot, humid and coastal, commonly 26–31°C. Southwest-monsoon rain is most influential from May to September, with additional inter-monsoon showers.",
      "local_highlights":["Sunset over the Colombo coastline","Seafood beside the beach","The heritage atmosphere of Mount Lavinia Hotel","Coastal train journeys","Easy access to contemporary Colombo"],
      "nearby_attractions":["Colombo","Dehiwala","Attidiya wetland","Gangaramaya Temple","National Museum of Colombo"],
      "travel_tips":["Use designated railway crossings and stay well clear of the tracks.","Check local advice before swimming because currents and water conditions vary.","Allow extra time for Colombo traffic.","Reserve popular sunset dining on weekends."]
    },
    {
      "slug":"nilaveli",
      "short_description":"A quiet ribbon of pale sand and clear east-coast water, with direct access to the marine life of Pigeon Island.",
      "full_description":"Nilaveli is defined by space: a long, lightly developed beach, warm shallow water in season and an open horizon. Offshore, Pigeon Island adds a protected marine dimension, while Trincomalee’s harbour and temples are close enough for cultural contrast. The result is a beach stay that feels calm without being isolated.",
      "why_visit":"Visit for restful east-coast beach days, seasonal snorkelling and an easy pairing with Trincomalee’s history and sacred sites.",
      "historical_importance":null,
      "cultural_significance":"The surrounding coast is shared by Tamil fishing communities and visitors. Respect for working boats, village spaces and local dress expectations matters away from resort beaches.",
      "unesco_information":null,
      "nature_wildlife":"Pigeon Island National Park protects coral reef habitat with reef fish, turtles and blacktip reef sharks. Visitor pressure makes careful, no-contact behaviour essential.",
      "best_time_to_visit":"May to September generally brings the calmest east-coast seas and clearest water. Conditions become wetter and less predictable during the northeast monsoon.",
      "weather":"Warm throughout the year, commonly 27–33°C. The east coast is driest in the middle of the year and wetter from November into February.",
      "local_highlights":["Long, uncrowded beach walks","Seasonal snorkelling at Pigeon Island","Calm-water swimming when conditions permit","Sea views across to the island","Easy day trips into Trincomalee"],
      "nearby_attractions":["Pigeon Island National Park","Trincomalee","Koneswaram Temple","Fort Frederick","Uppuveli"],
      "travel_tips":["Do not touch or stand on coral.","Use reef-safe sun protection and follow national-park instructions.","Visit Pigeon Island early to reduce crowd pressure.","Confirm sea conditions because boat services are weather dependent."]
    },
    {
      "slug":"pasikudah",
      "short_description":"A serene east-coast bay known for shallow turquoise water, gentle beach days and a spacious resort landscape.",
      "full_description":"Pasikudah’s great appeal is the bay itself. In the calm season, its shallow water extends gently from a pale sweep of sand, creating an easy setting for families and travellers who prefer an unhurried sea. Beyond the resorts, village life and the wider Batticaloa coast add context to a destination best enjoyed slowly.",
      "why_visit":"Choose Pasikudah for calm-season swimming, generous space and a relaxed east-coast stay with little pressure to do too much.",
      "historical_importance":null,
      "cultural_significance":"Tamil coastal communities and fishing traditions shape the wider region. Thoughtful visits should support local businesses beyond the resort environment.",
      "unesco_information":null,
      "nature_wildlife":"The bay includes seagrass and shallow marine habitats. Watersports and boat activity should be managed carefully to avoid damage to sensitive nearshore ecosystems.",
      "best_time_to_visit":"May to September is usually best for sunnier weather and calmer east-coast seas. Some facilities operate more quietly during the wetter northeast monsoon.",
      "weather":"Hot and tropical, generally 27–33°C. Mid-year is usually drier; heavier rain is more likely from November through February.",
      "local_highlights":["Shallow calm-season swimming","Long, spacious beach days","Sunrise over the Bay of Bengal","Gentle paddle and watersport options","A slower resort stay near Batticaloa"],
      "nearby_attractions":["Batticaloa","Kalkudah Beach","Batticaloa Lagoon","Kokkadicholai temple area","Vakarai coast"],
      "travel_tips":["Confirm seasonal sea conditions before swimming.","Carry sun protection because shade is limited on the open beach.","Plan cultural outings with a local guide for context.","Support village restaurants and producers where practical."]
    },
    {
      "slug":"tangalle",
      "short_description":"A secluded southern-coast base of sweeping beaches, oceanfront wellness and quiet access to lagoons and wildlife.",
      "full_description":"Tangalle sits where the south coast becomes wilder and more spacious. Rocky coves alternate with long beaches, boutique stays disappear into tropical gardens and the pace naturally slows. It works beautifully for restorative days, yet Rekawa, Bundala and the deep south’s cultural landscapes remain within reach.",
      "why_visit":"Visit for privacy, considered wellness and a more elemental southern coastline away from the busiest beach towns.",
      "historical_importance":"Tangalle’s harbour and surviving Dutch-era fort reflect the strategic importance of this southern coastal point.",
      "cultural_significance":"Fishing, Buddhist village life and Ayurveda remain part of the region’s identity. Temple and village visits are most rewarding with local context and modest dress.",
      "unesco_information":null,
      "nature_wildlife":"Nearby lagoons and wetlands support rich birdlife, while the Rekawa coast is associated with marine-turtle nesting. Visits must follow conservation guidance and avoid lights, noise and handling.",
      "best_time_to_visit":"December to April usually offers calmer beach weather. Wildlife and wellness experiences continue year-round, adjusted for rain and sea conditions.",
      "weather":"Warm and humid, generally 26–31°C. Rain is possible throughout the year, with wetter spells linked to monsoon and inter-monsoon periods.",
      "local_highlights":["Quiet coves and long southern beaches","Oceanfront yoga and Ayurveda","Rekawa’s conservation landscape","Tangalle lagoon and birdlife","Day journeys into the deep south"],
      "nearby_attractions":["Rekawa","Mulkirigala Rock Temple","Bundala National Park","Hiriketiya","Kataragama"],
      "travel_tips":["Many beaches have strong currents; swim only with reliable local guidance.","Follow turtle-viewing rules and never use flash.","Reserve longer wellness programmes before arrival.","Allow realistic road time for day trips into wildlife areas."]
    },
    {
      "slug":"trinco",
      "short_description":"A many-layered harbour city of cliff-top temples, sheltered beaches and compelling Tamil coastal culture.",
      "full_description":"Trincomalee is shaped by one of the world’s great natural harbours. Fort walls, sacred cliffs and working waterfronts reveal centuries of strategic and spiritual importance, while nearby beaches soften the city’s intensity. It is a destination where history, faith and the sea remain visibly intertwined.",
      "why_visit":"Come for the rare combination of harbour history, living Hindu tradition, east-coast beaches and seasonal marine experiences.",
      "historical_importance":"Trincomalee’s protected harbour drew successive regional and European powers. Fort Frederick and Swami Rock retain evidence of its long military and maritime significance.",
      "cultural_significance":"Koneswaram Temple is an important Hindu shrine and active place of worship. The city’s Tamil identity is expressed through temples, food, language and coastal community life.",
      "unesco_information":null,
      "nature_wildlife":"The deep harbour, offshore waters and nearby reefs support dolphins, whales and marine life. Seasonal excursions should use responsible operators and maintain respectful distances.",
      "best_time_to_visit":"May to September usually brings the driest weather and calmest east-coast seas. Temple and city visits remain rewarding beyond this window, with rain adjustments.",
      "weather":"Warm year-round, often 27–33°C. Mid-year is typically drier, while the northeast monsoon brings more rain from November into February.",
      "local_highlights":["Koneswaram Temple above Swami Rock","Fort Frederick and harbour views","The hot springs at Kanniya","Seafood and Tamil coastal flavours","Beach time at Uppuveli or Nilaveli"],
      "nearby_attractions":["Nilaveli","Pigeon Island National Park","Uppuveli","Kanniya hot springs","Seruwila"],
      "travel_tips":["Dress modestly and remove footwear at temple areas.","Check whether photography is appropriate in active worship spaces.","Choose marine operators who follow wildlife-distance guidance.","Plan outdoor visits early or late to avoid the strongest heat."]
    },
    {
      "slug":"weligama",
      "short_description":"A broad southern bay where beginner-friendly surf, fishing heritage and contemporary coastal life share the water.",
      "full_description":"Weligama’s generous bay makes learning to surf feel approachable. Boards line the sand, fishing craft work offshore and cafés bring a modern energy to the waterfront. Beyond the lessons, the town offers an easy base for Mirissa, the south-coast food scene and slower wellness days.",
      "why_visit":"Choose Weligama for accessible surf instruction, a lively local town and a central base for exploring the southern coast.",
      "historical_importance":"The area is associated with the Kushtarajagala figure and long-standing maritime and fishing traditions along the Matara coast.",
      "cultural_significance":"Traditional stilt fishing is part of the region’s visual identity, although staged displays are common. The working market, harbour and neighbourhood temples offer a more grounded view of local life.",
      "unesco_information":null,
      "nature_wildlife":"The bay’s relatively sheltered shape supports seasonal beginner surf and coastal birdlife. Marine activities should avoid litter, wildlife disturbance and overcrowding.",
      "best_time_to_visit":"November to April normally provides the cleanest surf and most settled southwest-coast weather. Beginner lessons operate more selectively outside the main season.",
      "weather":"Warm and humid, usually 26–31°C. The southwest monsoon brings wetter weather and rougher conditions from roughly May to September.",
      "local_highlights":["Beginner surf in the broad bay","Weligama fish market and working coast","Cafés and contemporary coastal dining","Kushtarajagala monument","Easy access to Mirissa and the south coast"],
      "nearby_attractions":["Mirissa","Kushtarajagala","Midigama","Matara","Galle Fort"],
      "travel_tips":["Use a reputable surf school with correctly sized equipment.","Keep clear of fishing craft and working areas.","Treat stilt-fishing photographs respectfully and agree any fee first.","Confirm swimming conditions outside the main dry season."]
    }
  ]$catalog$::jsonb) as c(
    slug text,
    short_description text,
    full_description text,
    why_visit text,
    historical_importance text,
    cultural_significance text,
    unesco_information text,
    nature_wildlife text,
    best_time_to_visit text,
    weather text,
    local_highlights jsonb,
    nearby_attractions jsonb,
    travel_tips jsonb
  )
)
update public.destinations as d
set
  short_description = c.short_description,
  full_description = c.full_description,
  why_visit = c.why_visit,
  historical_importance = c.historical_importance,
  cultural_significance = c.cultural_significance,
  unesco_information = c.unesco_information,
  nature_wildlife = c.nature_wildlife,
  best_time_to_visit = c.best_time_to_visit,
  weather = c.weather,
  local_highlights = c.local_highlights,
  nearby_attractions = c.nearby_attractions,
  travel_tips = c.travel_tips,
  updated_at = now()
from catalog as c
where d.slug = c.slug;
