begin;

-- Sporting Sri Lanka is a spectator-and-participation sports theme. It is
-- intentionally separate from Thrill & Adventure and owns no adventure cards.
alter table public.themes
  add column if not exists highlights jsonb not null default '[]'::jsonb,
  add column if not exists badges jsonb not null default '[]'::jsonb;

do $$ begin
  alter table public.themes add constraint themes_highlights_array check (jsonb_typeof(highlights)='array');
exception when duplicate_object then null; end $$;
do $$ begin
  alter table public.themes add constraint themes_badges_array check (jsonb_typeof(badges)='array');
exception when duplicate_object then null; end $$;

update public.themes set
  name='Sporting Sri Lanka',
  short_description='Experience Sri Lanka through its rich sporting culture, iconic venues and world-class sporting experiences.',
  full_description=$copy$Sport in Sri Lanka is a social language. Cricket fills grounds, school fields and neighbourhood lanes; historic golf clubs preserve a distinctive sporting heritage; and the high country adds its own equestrian traditions. Sporting Sri Lanka turns those worlds into carefully arranged days with clear access, considered transfers and time to understand the people and places behind the occasion.

This is not an adventure itinerary. It is for travellers who want to watch a major fixture, share a friendly game with local players, walk an established course or build a journey around the atmosphere of an iconic venue. Every event-led experience remains subject to official dates, legitimate admission and venue conditions.$copy$,
  hero_image_url='https://upload.wikimedia.org/wikipedia/commons/0/00/Floodlighted_RPS_International_Cricket_Stadium.jpg',
  image_alt='A floodlit cricket match at R. Premadasa International Cricket Stadium in Colombo',
  gallery='["https://upload.wikimedia.org/wikipedia/commons/e/e2/Sri_Lanka_vs_Australia_cricket_game_in_Colombo.jpg","https://upload.wikimedia.org/wikipedia/commons/f/f7/Galle_International_Stadium.jpg","https://upload.wikimedia.org/wikipedia/commons/8/8a/Royal_Colombo_Golf_Club_006_(cropped).jpg","https://upload.wikimedia.org/wikipedia/commons/5/54/LK-nuwara-eliya-golf.jpg","https://upload.wikimedia.org/wikipedia/commons/d/d8/Nuwara_Eliya_Racecourse.jpg"]'::jsonb,
  highlights='["International cricket at landmark grounds in Colombo, Kandy, Galle and Hambantota","Private golf days across Colombo, Kandy, Nuwara Eliya and the southern coast","A hosted local cricket session shaped around people rather than performance","High-country horse riding arranged with an approved local operator","Fixture-led journeys with legitimate access and transparent inclusions"]'::jsonb,
  badges='["Cricket Culture","Iconic Venues","Golf Journeys","Sporting Heritage","Roam Ceylon Recommended"]'::jsonb,
  why_choose='["Experience the island through sporting traditions Sri Lankans genuinely care about.","Combine spectator occasions and active sporting days without duplicating adventure activities.","Receive careful coordination around venue access, equipment, dress codes and transfers.","Build a private route around official fixtures and confirmed supplier availability."]'::jsonb,
  suggested_itinerary='["Begin in Colombo with cricket culture and a round at Royal Colombo Golf Club.","Continue to Kandy for a Pallekele fixture or the championship course at Victoria.","Travel through Nuwara Eliya for its historic golf club and high-country equestrian culture.","Finish on the south coast with Galle cricket or resort golf in Hambantota."]'::jsonb,
  travel_inspiration='Follow the sound of leather on willow, the quiet line of a fairway and the shared rituals that make sport part of Sri Lankan life.',
  seo_title='Sporting Sri Lanka | Cricket, Golf & Sporting Journeys',
  seo_description='Discover premium cricket, golf, horse riding and sporting-culture experiences across Colombo, Kandy, Galle, Hambantota and Nuwara Eliya.',
  image_source='Wikimedia Commons',
  image_credit='Wikimedia Commons contributors; retain per-file attribution and licence records',
  image_status='needs_review',needs_image_review=true,
  image_review_notes='Five activity-specific editorial images selected. Confirm each Commons file licence and attribution before production asset ingestion.',
  status='published',active=true,updated_at=now()
where slug='sporting';

insert into public.destinations(name,slug,province,region,short_description,full_description,hero_image_url,image_alt,latitude,longitude,display_order,coming_soon,status,active,image_status,needs_image_review,image_review_notes)
values('Hambantota','hambantota','Southern Province','Deep South','A southern sporting gateway shaped by international cricket, coastal resort golf and the open landscapes of Sri Lanka’s dry zone.','Hambantota brings a different scale to the southern journey: broad dry-zone horizons, a major international cricket venue and resort golf beside the Indian Ocean. It works best as part of a considered deep-south route, with sporting days balanced by coastal landscapes and nearby wildlife country.','https://upload.wikimedia.org/wikipedia/commons/c/ca/Mahinda_Rajapaksa_International_Cricket_Stadium.jpg','Mahinda Rajapaksa International Cricket Stadium in Hambantota',6.1241,81.1185,35,false,'published',true,'needs_review',true,'Verify the Commons licence and replace with a wider Hambantota destination image when the general destination editorial pass is completed.')
on conflict(slug) do update set status='published',active=true,updated_at=now();

delete from public.theme_destinations where theme_id=(select id from public.themes where slug='sporting');
insert into public.theme_destinations(theme_id,destination_id)
select t.id,d.id from public.themes t cross join public.destinations d
where t.slug='sporting' and d.slug in ('colombo','kandy','galle','hambantota','nuwaraeliya');

create temporary table sporting_catalogue on commit drop as
select * from jsonb_to_recordset($catalog$[
  {"slug":"sri-lanka-international-cricket-matchday","name":"Watch an International Cricket Match","category":"Sporting Events","short":"Feel the pulse of Sri Lankan cricket at a confirmed international fixture with legitimate admission and a carefully planned matchday.","about":"Cricket is one of Sri Lanka’s great shared rituals. This experience is built around an officially confirmed Test, ODI or T20 fixture and names the match, venue, date, ticket category and included services before acceptance. Roam Ceylon coordinates the day around legitimate access, realistic travel times and the particular atmosphere of the host city; no speculative fixture or unverified resale ticket is offered.","duration":"Fixture dependent: approximately 4 hours for a T20, a full day for an ODI, or selected days of a Test","difficulty":"Easy spectator experience; heat, crowds, stairs and accessibility vary by venue","season":"Official international fixture dates only","hero":"https://upload.wikimedia.org/wikipedia/commons/0/00/Floodlighted_RPS_International_Cricket_Stadium.jpg","alt":"A floodlit international cricket match at R. Premadasa Stadium in Colombo","gallery":["https://upload.wikimedia.org/wikipedia/commons/e/e2/Sri_Lanka_vs_Australia_cricket_game_in_Colombo.jpg","https://upload.wikimedia.org/wikipedia/commons/2/23/R_Premadasa_Stadium.jpg","https://upload.wikimedia.org/wikipedia/commons/9/9d/The_clouds_roll_in.jpg","https://upload.wikimedia.org/wikipedia/commons/f/f7/Galle_International_Stadium.jpg","https://upload.wikimedia.org/wikipedia/commons/c/ce/Pallekele_International_Cricket_Stadium.jpg"],"highlights":["Admission to a confirmed official fixture","A named ticket and seating category","Private transfer coordination when selected","Local context on the match, ground and host city"],"unique_points":["A real fixture-led product rather than a generic stadium visit","Sri Lankan crowd culture interpreted with local context","Multiple iconic grounds supported through one canonical experience"],"included":["Verified match ticket when explicitly confirmed","Fixture and entry coordination","Services itemised in the accepted proposal"],"know":["Fixtures, start times and venues may change","Weather interruptions follow organiser policy","Identification and prohibited-item rules vary by ground"],"nearby":["Colombo city","Galle Fort","Kandy","Hambantota coast"],"tips":["Keep the day free from tight onward travel","Carry identification matching ticket requirements","Use sun protection for daytime seating"],"badges":["Signature Experience","Sporting Event","Seasonal","Advance Booking Recommended","Most Popular","Roam Ceylon Recommended"],"destinations":["colombo","kandy","galle","hambantota"],"family":true,"children":true,"private":false,"featured":true},
  {"slug":"cricket-with-local-players","name":"Cricket with Local Players","category":"Sports Culture","short":"Share a friendly cricket session with local players and discover how the game lives beyond Sri Lanka’s international grounds.","about":"This hosted session is about connection, not elite coaching. A local club, school alumni group or community host welcomes travellers for an informal game adapted to the group’s ability and available ground. The proposal confirms the host, venue, format and equipment in advance, protects school and community settings from intrusive tourism, and keeps the encounter respectful and genuinely participatory.","duration":"Approximately 2–3 hours","difficulty":"Easy to moderate; adapted to the group","season":"Year-round, subject to weather and ground availability","hero":"https://upload.wikimedia.org/wikipedia/commons/0/0d/Battle_of_Two_Cities_2008.jpg","alt":"Local cricket players taking part in a Sri Lankan match","gallery":["https://upload.wikimedia.org/wikipedia/commons/8/89/Bigmatch2016_2.jpg","https://upload.wikimedia.org/wikipedia/commons/7/7a/Bigmatch2016-2.jpg","https://upload.wikimedia.org/wikipedia/commons/6/6c/Dharmaraja-Kingswood.JPG","https://upload.wikimedia.org/wikipedia/commons/1/1c/Richmond-Mahinda_Big_Match.jpg","https://upload.wikimedia.org/wikipedia/commons/4/45/Percy%2C_Beloved_Sri_Lankan_cricket_fan.jpg"],"highlights":["A friendly hosted game","Format adjusted to ability and time","Shared cricket stories and local sporting culture","Equipment arranged when confirmed"],"unique_points":["A people-first sporting exchange","Suitable for mixed experience levels","Hosted only with the venue’s clear consent"],"included":["Local host","Basic cricket equipment when confirmed","Water and private transfers only when itemised"],"know":["This is not professional coaching","Ground access is supplier dependent","Respectful dress and photography consent are required"],"nearby":["Colombo","Kandy","Galle"],"tips":["Wear light sports clothing and trainers","Tell the designer about mobility or experience level","Ask before photographing participants"],"badges":["Local Sporting Experience","Family Friendly","Sports Culture","Roam Ceylon Recommended"],"destinations":["colombo","kandy","galle"],"family":true,"children":true,"private":true,"featured":true},
  {"slug":"colombo-royal-golf-private-round","name":"Royal Colombo Golf Club Experience","category":"Golf","short":"Play a private round within Colombo’s historic golfing landscape, with tee time and visitor requirements confirmed before travel.","about":"Royal Colombo Golf Club offers a rare sporting pause inside the capital. Roam Ceylon arranges the day around confirmed visitor access, tee time, handicap requirements, equipment needs and club etiquette. The experience is deliberately unhurried, leaving room for the course’s history and the contrast between its green fairways and the city beyond.","duration":"Approximately 4–5 hours for 18 holes","difficulty":"Active; golfing ability and current club requirements apply","season":"Year-round; mornings are generally cooler","hero":"https://upload.wikimedia.org/wikipedia/commons/8/8a/Royal_Colombo_Golf_Club_006_(cropped).jpg","alt":"The clubhouse and grounds of Royal Colombo Golf Club","gallery":["https://upload.wikimedia.org/wikipedia/commons/5/55/Royal_Colombo_Golf_Club_006.jpg","https://upload.wikimedia.org/wikipedia/commons/1/17/Royal_Colombo_Golf_Club_007.jpg","https://upload.wikimedia.org/wikipedia/commons/4/47/Royal_Colombo_Golf_Club_011.jpg","https://upload.wikimedia.org/wikipedia/commons/8/8a/Royal_Colombo_Golf_Club_006_(cropped).jpg","https://upload.wikimedia.org/wikipedia/commons/5/55/Royal_Colombo_Golf_Club_006.jpg"],"highlights":["Confirmed visitor tee time","Historic city golf setting","Equipment and caddie requirements coordinated","Private transfers when selected"],"unique_points":["A long-established Sri Lankan golf institution","A sporting experience within central Colombo","Club access handled as a confirmed arrangement"],"included":["Tee-time coordination","Green fee only when itemised","Equipment, caddie and transfer only when itemised"],"know":["Visitor access and handicap rules must be reconfirmed","Club dress code applies","Rates are quoted after availability confirmation"],"nearby":["Cinnamon Gardens","National Museum","Independence Square"],"tips":["Share handicap and rental needs early","Carry suitable golf shoes and collared attire","Choose an early tee time in warmer months"],"badges":["Golf Journey","Sporting Heritage","Luxury Upgrade Available","Advance Booking Recommended"],"destinations":["colombo"],"family":false,"children":false,"private":true,"featured":true},
  {"slug":"victoria-golf-country-resort-experience","name":"Victoria Golf & Country Resort Experience","category":"Golf","short":"Play a championship hill-country course framed by the Victoria Reservoir and the folded landscapes east of Kandy.","about":"Victoria’s 18-hole course at Digana is as much a landscape journey as a round of golf. Dramatic changes in elevation, reservoir views and carefully placed hazards reward thoughtful play. Roam Ceylon confirms tee time, current visitor rules, caddie or buggy needs and equipment before building the day into a Kandy itinerary.","duration":"Approximately 4–5 hours for 18 holes","difficulty":"Active; course conditions suit established golfers, with academy options subject to confirmation","season":"Year-round; conditions vary with hill-country rain","hero":"https://upload.wikimedia.org/wikipedia/commons/e/ea/Victoria_golf_course.JPG","alt":"Victoria golf course in Sri Lanka’s hill country","gallery":["https://upload.wikimedia.org/wikipedia/commons/e/ea/Victoria_golf_course.JPG","https://images.pexels.com/photos/274133/pexels-photo-274133.jpeg?auto=compress&cs=tinysrgb&w=1600","https://images.pexels.com/photos/114972/pexels-photo-114972.jpeg?auto=compress&cs=tinysrgb&w=1600","https://images.pexels.com/photos/54123/pexels-photo-54123.jpeg?auto=compress&cs=tinysrgb&w=1600","https://images.pexels.com/photos/1325735/pexels-photo-1325735.jpeg?auto=compress&cs=tinysrgb&w=1600"],"highlights":["18-hole championship course","Victoria Reservoir and hill-country views","Academy and practice options when confirmed","Stay-and-play planning available"],"unique_points":["A strategic course shaped by dramatic terrain","A natural addition to a private Kandy journey","Suitable for a dedicated golf day or longer stay"],"included":["Tee-time coordination","Green fee only when itemised","Caddie, buggy, clubs and transfer only when itemised"],"know":["Current green fees and visitor rules require confirmation","Golf attire is required","Journey time from central Kandy must be allowed"],"nearby":["Kandy","Victoria Reservoir","Bambaragala"],"tips":["Share handicap and club-rental needs early","Allow a full day from central Kandy","Carry a light rain layer"],"badges":["Signature Golf","Photography Spot","Luxury Upgrade Available","Advance Booking Recommended"],"destinations":["kandy"],"family":false,"children":false,"private":true,"featured":true},
  {"slug":"nuwara-eliya-golf-club-experience","name":"Nuwara Eliya Golf Club Experience","category":"Golf","short":"Play amid cool high-country air, mature trees and the sporting heritage of one of Sri Lanka’s most distinctive hill stations.","about":"Nuwara Eliya Golf Club brings together sporting tradition and the atmosphere of the high country. The course runs through the town’s green heart, making a round feel woven into the destination rather than isolated from it. Visitor access, tee time, handicap documentation, equipment and caddie requirements are confirmed before the day is proposed.","duration":"Approximately 4–5 hours for 18 holes","difficulty":"Active; visitor and handicap requirements apply","season":"Year-round; February to April is popular, with rain possible in any month","hero":"https://upload.wikimedia.org/wikipedia/commons/5/54/LK-nuwara-eliya-golf.jpg","alt":"The green course of Nuwara Eliya Golf Club in Sri Lanka’s high country","gallery":["https://upload.wikimedia.org/wikipedia/commons/7/7d/NE_Golf_Club_(1).jpg","https://upload.wikimedia.org/wikipedia/commons/4/41/NE_Golf_Club_(2).jpg","https://upload.wikimedia.org/wikipedia/commons/e/e6/Nuwara_Eliya_golf_course-clubhouse.jpg","https://upload.wikimedia.org/wikipedia/commons/2/2b/Nuwara_Eliya_golf_course-greens.jpg","https://upload.wikimedia.org/wikipedia/commons/6/60/Nuwara_Eliya_golf_course.jpg"],"highlights":["Historic high-country golf setting","Cooler mountain climate","Confirmed visitor round","Easy pairing with tea-country stays"],"unique_points":["A course embedded in Nuwara Eliya’s townscape","A strong sense of Sri Lankan golfing heritage","A refined contrast to tropical coastal golf"],"included":["Tee-time coordination","Green fee only when itemised","Caddie, equipment and transfer only when itemised"],"know":["Visitor reservation and handicap rules apply","Weather can change quickly","Club dress standards must be observed"],"nearby":["Victoria Park","Lake Gregory","Tea country"],"tips":["Bring a light layer for cool mornings","Submit handicap details early","Keep wet-weather gear available"],"badges":["Golf Journey","Sporting Heritage","Photography Spot","Advance Booking Recommended"],"destinations":["nuwaraeliya"],"family":false,"children":false,"private":true,"featured":true},
  {"slug":"shangri-la-hambantota-golf-experience","name":"Shangri-La Hambantota Golf Experience","category":"Golf","short":"Play an ocean-edge resort course that moves through coconut palms, water and the contours of a former sapphire mine.","about":"Shangri-La Hambantota’s 18-hole course is a complete southern sporting day. Its landscaped zones move from coconut plantation to water-framed greens and dune country near the Indian Ocean. Roam Ceylon coordinates the round with the resort, confirms caddie, cart and equipment needs, and can shape it into a stay-and-play journey without presenting an unverified package price.","duration":"Approximately 4–5 hours for 18 holes","difficulty":"Active; three tee positions support different playing levels","season":"Year-round, with wind and tropical weather considered","hero":"https://sitecore-cd.shangri-la.com/-/media/Shangri-La/hambantota_shangrila/golf/202412_SLHT_Golf-Course-2_1920x940.jpg","alt":"The golf course at Shangri-La Hambantota beside Sri Lanka’s southern coast","gallery":["https://sitecore-cd.shangri-la.com/-/media/Shangri-La/hambantota_shangrila/golf/Tournament.jpg","https://sitecore-cd.shangri-la.com/-/media/Shangri-La/hambantota_shangrila/golf/202412_SLHT_Golf-Course-5_1920x940.jpg","https://sitecore-cd.shangri-la.com/-/media/Shangri-La/hambantota_shangrila/golf/golf-landscape-1920x940.jpg","https://sitecore-cd.shangri-la.com/-/media/Shangri-La/hambantota_shangrila/golf/202412_SLHT_Golf-Course-7_1920x940.jpg","https://sitecore-cd.shangri-la.com/-/media/Shangri-La/hambantota_shangrila/golf/202412_SLHT_Golf-Course-2_1920x940.jpg"],"highlights":["18-hole coastal resort course","Coconut, sapphire-mine and dune landscapes","Equipment hire and carts subject to confirmation","Stay-and-play option"],"unique_points":["Sri Lanka’s first resort golf destination","Ocean views and distinctive course zones","A premium sporting anchor for the deep south"],"included":["Tee-time coordination","Green fee only when itemised","Caddie, cart, equipment and stay only when itemised"],"know":["Caddies are mandatory according to the resort’s published guidance","Soft-spike golf shoes and proper golf attire are required","Current rates and facilities must be reconfirmed"],"nearby":["Hambantota coast","Bundala","Tissamaharama"],"tips":["Reserve equipment well ahead","Allow for wind on ocean-facing holes","Pair the round with a restful resort night"],"badges":["Luxury Golf","Photography Spot","Luxury Upgrade Available","Advance Booking Recommended"],"destinations":["hambantota"],"family":false,"children":false,"private":true,"featured":true},
  {"slug":"horse-riding-in-nuwara-eliya","name":"Horse Riding in Nuwara Eliya","category":"Horse Riding","short":"Discover Nuwara Eliya’s equestrian character through a private ride arranged to the traveller’s ability and a verified local operator.","about":"Horse riding belongs naturally to Nuwara Eliya’s sporting story, but the quality of the operator matters more than a generic promise. Roam Ceylon publishes the experience as a curated request: the final proposal identifies the licensed or insured operator, horse, route, duration, supervision and safety equipment. Gentle introductory rides are prioritised over unverified trail claims.","duration":"Approximately 45–90 minutes, confirmed by operator and ability","difficulty":"Easy to moderate; rider age, weight and experience restrictions may apply","season":"Year-round in suitable weather and ground conditions","hero":"https://upload.wikimedia.org/wikipedia/commons/d/d8/Nuwara_Eliya_Racecourse.jpg","alt":"The historic racecourse landscape in Nuwara Eliya","gallery":["https://upload.wikimedia.org/wikipedia/commons/a/ad/Racecourse_Grand_Stand.jpg","https://upload.wikimedia.org/wikipedia/commons/1/1c/Racecourse%2C_Nuwara_Eliya.jpg","https://upload.wikimedia.org/wikipedia/commons/5/53/SL_Nuwara_Eliya_asv2020-01_img12_racecourse.jpg","https://upload.wikimedia.org/wikipedia/commons/c/c7/Nuwara_Eliya_Town_Hall_and_racecourseGround.jpg","https://upload.wikimedia.org/wikipedia/commons/d/d8/Nuwara_Eliya_Racecourse.jpg"],"highlights":["Private ability-matched session","High-country equestrian setting","Operator, horse and route named in the proposal","Safety equipment confirmed before acceptance"],"unique_points":["A quiet sporting experience rooted in Nuwara Eliya’s equestrian identity","Designed around welfare and operator verification","Suitable as a gentle high-country interlude"],"included":["Horse and handler or instructor when confirmed","Helmet and safety equipment when confirmed","Private transfer only when itemised"],"know":["Publication does not guarantee instant availability","Operator insurance, horse welfare and route permission require confirmation","Age, weight and ability limits may apply"],"nearby":["Nuwara Eliya Racecourse","Victoria Park","Lake Gregory"],"tips":["Share riding experience and approximate weight privately with the designer","Wear long trousers and closed shoes","Do not proceed if the named operator or safety equipment changes"],"badges":["Horse Riding","Sporting Heritage","Couples Favourite","Advance Booking Recommended"],"destinations":["nuwaraeliya"],"family":true,"children":true,"private":true,"featured":true}
]$catalog$::jsonb) as x(slug text,name text,category text,short text,about text,duration text,difficulty text,season text,hero text,alt text,gallery jsonb,highlights jsonb,unique_points jsonb,included jsonb,know jsonb,nearby jsonb,tips jsonb,badges jsonb,destinations jsonb,family boolean,children boolean,private boolean,featured boolean);

insert into public.experiences(name,slug,category,short_description,full_description,hero_image_url,image_alt,gallery,gallery_alt_texts,duration,difficulty,best_season,highlights,unique_points,included,things_to_know,nearby_attractions,traveller_tips,badges,family_friendly,suitable_for_children,private_option,priority,featured,status,active,seo_title,seo_description,image_source,image_credit,image_status,needs_image_review,image_review_notes)
select name,slug,category,short,about,hero,alt,gallery,'[]'::jsonb,duration,difficulty,season,highlights,unique_points,included,know,nearby,tips,badges,family,children,private,case when featured then 'must-do'::public.experience_priority else 'popular'::public.experience_priority end,featured,'published',true,name||' | Roam Ceylon',short,'Wikimedia Commons, official venue media, and temporary editorial reference photography','Per-image source retained in the URLs; complete the production attribution register before launch','needs_review',true,'Content is publish-ready. Confirm usage rights/attribution for every image and replace temporary generic golf references with venue-approved assets before public launch.'
from sporting_catalogue
on conflict(slug) do update set name=excluded.name,category=excluded.category,short_description=excluded.short_description,full_description=excluded.full_description,hero_image_url=excluded.hero_image_url,image_alt=excluded.image_alt,gallery=excluded.gallery,duration=excluded.duration,difficulty=excluded.difficulty,best_season=excluded.best_season,highlights=excluded.highlights,unique_points=excluded.unique_points,included=excluded.included,things_to_know=excluded.things_to_know,nearby_attractions=excluded.nearby_attractions,traveller_tips=excluded.traveller_tips,badges=excluded.badges,family_friendly=excluded.family_friendly,suitable_for_children=excluded.suitable_for_children,private_option=excluded.private_option,priority=excluded.priority,featured=excluded.featured,status='published',active=true,seo_title=excluded.seo_title,seo_description=excluded.seo_description,image_source=excluded.image_source,image_credit=excluded.image_credit,image_status=excluded.image_status,needs_image_review=excluded.needs_image_review,image_review_notes=excluded.image_review_notes,updated_at=now();

-- Sporting owns only the seven approved products. Existing adventure theme links
-- on every other experience remain untouched.
delete from public.experience_themes where theme_id=(select id from public.themes where slug='sporting');
insert into public.experience_themes(experience_id,theme_id)
select e.id,t.id from sporting_catalogue c join public.experiences e on e.slug=c.slug cross join public.themes t where t.slug='sporting';

delete from public.experience_destinations ed using sporting_catalogue c,public.experiences e where e.slug=c.slug and ed.experience_id=e.id;
insert into public.experience_destinations(experience_id,destination_id)
select e.id,d.id from sporting_catalogue c join public.experiences e on e.slug=c.slug cross join lateral jsonb_array_elements_text(c.destinations) ds(slug) join public.destinations d on d.slug=ds.slug;

do $$
declare bad_count integer; bad_gallery integer; destination_count integer;
begin
  select count(*) into bad_count from public.experience_themes et join public.experiences e on e.id=et.experience_id join public.themes t on t.id=et.theme_id where t.slug='sporting' and e.slug not in (select slug from sporting_catalogue);
  select count(*) into bad_gallery from sporting_catalogue where jsonb_array_length(gallery)<>5;
  select count(*) into destination_count from public.theme_destinations td join public.themes t on t.id=td.theme_id where t.slug='sporting';
  if bad_count<>0 or bad_gallery<>0 or destination_count<>5 then raise exception 'Sporting Sri Lanka validation failed: mappings %, galleries %, destinations %',bad_count,bad_gallery,destination_count; end if;
end $$;

commit;
